### ISSUE TITLE
Problem displaying end gateway after enabling shader on 1.17

### ISSUE THREAD

**Issue by czhangdev** [IrisShaders/Iris#430] opened 2021-06-26 15:06 UTC
**Describe the bug**
when shaders are enabled, end gateway wouldn't display properly, would only display the particles

**To Reproduce**
Steps to reproduce the behaviour:
1.Enable Shader (Currently Tested Shaders: PTGI; Sildurs)
2./setblock ~ ~ ~ minecraft:end_gateway
3.See issue

**Expected behaviour**
Should see end gateway and particles produced by end gateway.

**Screenshots**

**System (please complete the following information):**
 - OS: Windows Server 2022 Datacenter Technical Preview
 - GPU: GTX1650
 - Minecraft Version: Minecraft 1.17 with Fabric 0.11.6

**Additional context**
Tested on my friends computer, same problem happens again, tried both multi and single player, problem still persists.

**Comment by yitzy299** [comment] 2021-06-26 15:37
Duplicate of #361

**Closed by yitzy299** 2021-06-26 15:37 UTC
Labels: bug
