### ISSUE TITLE
Failure to compile shaders with mesa drivers and intel

### ISSUE THREAD

**Issue by AlsoNiko** [IrisShaders/Iris#350] opened 2021-06-10 01:02 UTC
Seemily a crash on igpus for 1.17, reported by someone using vega 8 and intel 620. report is from the 620 user. 
[message (5).txt](https://github.com/IrisShaders/Iris/files/6627685/message.5.txt)

**Comment by IMS212** [comment] 2021-06-10 06:03
This seems to be an issue with mesa drivers. After testing on discord, we were able to reproduce the issue on an UHD 630 and RX 590, but not an RTX 3060 ti with the proprietary NVIDIA drivers.

**Comment by AlsoNiko** [comment] 2021-06-10 15:52
[latest (4).log](https://github.com/IrisShaders/Iris/files/6632812/latest.4.log)
Adding here because it is the same issue, though for some reason it boots on MacOS and not linux? 
That's either caused by something apple does, or it being a 640 and not a 630 or 620

**Comment by IMS212** [comment] 2021-06-10 15:54
The issue is likely caused by the mesa drivers on Linux, as the title states. We were not able to reproduce this on arch linux with the proprietary nvidia drivers.

**Comment by AlsoNiko** [comment] 2021-06-10 15:56
This log is not on Linux, it's on macos, leading me to wonder if it also happens on windows

**Comment by TheRealM18** [comment] 2021-06-10 16:01
@AlsoNiko on 1.17 I can not get my shaders to load, the packs, but on 1.16.5 they work. here is the specs of the pc according to minecraft.

[23:11:38] [Render thread/INFO]: CPU: 4x Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
[23:11:38] [Render thread/INFO]: GPU: Intel(R) HD Graphics 4400 (Supports OpenGL 3.2.0 - Build 20.19.15.4642)

that being said, im also on windows.

**Comment by TheRealM18** [comment] 2021-06-10 16:20
[latest.log](https://github.com/IrisShaders/Iris/files/6632967/latest.log)


my log file btw

**Comment by mineland-0066** [comment] 2021-06-10 22:36
can confirm its probably the mesa drivers. im using pop os with mesa drivers on an intel celeron e1500 with and amd Radeon hd 6450 gpu and the shaders wont apply. Cant try on linux nor with the amdgpu pro drivers since they arent updated for modern linux
[latest_logs.txt](https://github.com/IrisShaders/Iris/files/6634741/latest_logs.txt)
^^ here are my console logs during this event

**Comment by yitzy299** [comment] 2021-06-11 17:52
This isn't just present with mesa drivers - I can reproduce this on intel/windows

**Comment by AlsoNiko** [comment] 2021-06-11 17:55
Yes, the issue has had this included, it seems to crash with all intel, and mesa drivers for AMD meaning that AMD windows users are fine, but intel users are out of luck. I think the recent devlog shows a fix for this but it may still not work on windows.

**Comment by AlsoNiko** [comment] 2021-06-11 18:20
Noted in issue #271 there are issues with Mesa drivers on both versions, not just 1.17

**Comment by williambl** [comment] 2021-06-11 21:36
I personally only have this issue on 1.17 (with mesa amd drivers)

**Comment by AlsoNiko** [comment] 2021-06-11 21:37
It's a much less consistent issue, but it has been demonstrated a few times, hence why it's being changed to a general issue with mesa

**Comment by mineland-0066** [comment] 2021-06-11 22:02
Ive read something online about the amd mesa drivers for my gpu that it might have to do with the mesa shader backend. It seems like it has trouble not only in minecraft but a lot lf other programs aswell (blender for example)
Another thing that happens only in linux+mesa is that fabulous graphics are conpleately dead, showing a weird 3d effect only looking normal through transparent blocks like water. (See https://gitlab.freedesktop.org/mesa/mesa/-/issues/4026)
Cant say anything for the intel users tho since my laptop cant run opengl 3 to test it out.

**Comment by thecoder-001** [comment] 2021-06-13 07:37
With the latest commit, ominous seems to be fixed though complementary still fails to compile.
System info: intel 5000, macOS
Here's the log file (contains log for loading ominous, complementary & bsl): [pastebin](https://paste.ee/p/w0NK2) / [latest.log](https://github.com/IrisShaders/Iris/files/6643467/latest.log).

**Comment by AlsoNiko** [comment] 2021-06-18 14:10
The pack tested was all different versions of sildurs, possibly an issue with the legacy intel driver? Doesn't seem like this happened on 1.16.5, only 1.17. Using the latest 1.0.2 build of iris
[latest (14).log](https://github.com/IrisShaders/Iris/files/6677515/latest.14.log)
![unknown](https://user-images.githubusercontent.com/64978191/122574059-42e70f00-d01d-11eb-9a1f-c8eee01e0d4a.png)

**Comment by hellosway** [comment] 2021-06-18 18:09
Sildurs works for me on intel mac, only windom and comp fails to compile

**Comment by AlsoNiko** [comment] 2021-06-25 16:04
This seems to be fixed as of now, but more testing is needed

**Comment by mineland-0066** [comment] 2021-06-25 21:21
![2021-06-25_16 19 19](https://user-images.githubusercontent.com/60583383/123486209-36405900-d5d1-11eb-8213-816b1d41d709.png)
was able to enable them in my system with the latest 1.17 build from source. Neato

**Comment by AlsoNiko** [comment] 2021-06-27 16:24
![image](https://user-images.githubusercontent.com/64978191/123552094-97d40500-d742-11eb-82f4-b9e330ca01e8.png)
Issue still persists on 1.17 latest.

**Comment by coderbot16** [comment] 2021-06-27 16:25
Cannot reproduce on my Mesa drivers. More information is needed - log files, etc.

**Comment by AlsoNiko** [comment] 2021-06-27 16:30
The only log that I have currently is this one 
[latest (14).log](https://github.com/IrisShaders/Iris/files/6677515/latest.14.log)
trying to gather more as we speak, getting an old laptop out.

**Comment by coderbot16** [comment] 2021-06-27 17:06
Closing this in favor of #441 since the issue on Mesa / mac described here has been fixed in the development versions, and the other issue being tracked here appears to be distinct.

**Closed by coderbot16** 2021-06-27 17:06 UTC
Labels: bug, high priority, more information needed
