### ISSUE TITLE
Water flicking when you leave spawn region

### ISSUE THREAD

**Issue by Farych** [IrisShaders/Iris#556] opened 2021-07-16 10:56 UTC
### What happened?

Here is a troubles with water when you leave area near spawn. 
Nothing happens if i change shaders to other one, i try about 9 different packs.

### Screenshots

Video: https://youtu.be/Wshxe0YWLic

### Iris and Minecraft Version

iris-mc1.16.5-1.1.0+rev.6ad325a

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia RTX 2080 Super

### Java Version

Java 1.8.0_51 64bit

**Comment by Farych** [comment] 2021-07-16 15:41
Actually anything start flicking if you away from spawn, On the border of the world, the blocks lose their proportions and sizes, they shake. There is no such problem on Optifine, as it seems to me, if Iris is trying to be a worthy analogue, then this point should be fixed.

**Comment by IMS212** [comment] 2021-07-16 15:51
this is the same as #334, and only happens 1 million+ blocks away from spawn in most cases. The cause is due to the cameraPosition float losing precision far out on Iris.

**Comment by coderbot16** [comment] 2021-09-09 19:37
Closing as a duplicate of #334

**Closed by coderbot16** 2021-09-09 19:37 UTC
Labels: bug
