### ISSUE TITLE
[mod compatibility] Some shaders are weird with MCXR

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1499] opened 2022-06-18 14:18 UTC
### What happened?

Some shaders are weird with MCXR

https://www.veed.io/view/0b20cf4b-aca8-4a9e-8385-9d387172c9ff

![image](https://user-images.githubusercontent.com/68275908/174442487-e84e425a-526c-45ab-a069-e55b75e63e87.png)

### Relevant log output

```shell
[16:17:23] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[16:17:23] [main/INFO]: Loading 60 mods:
	- com_electronwill_night-config_core 3.6.5 via mcxr-core
	- com_electronwill_night-config_toml 3.6.5 via mcxr-core
	- fabric 0.56.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via fabric
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.13+b2a4a624a9 via fabric
	- fabric-blockrenderlayer-v1 1.1.18+9ff28f40a9 via fabric
	- fabric-command-api-v1 1.2.5+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.1+cda9839ba9 via fabric
	- fabric-commands-v0 0.2.22+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.27+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.1.0+4a3ec384a9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.0.1+2a5b9210a9 via fabric
	- fabric-dimensions-v1 2.1.27+72da3b3da9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.25+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.4+767db26ea9 via fabric
	- fabric-item-groups-v0 0.3.23+9ff28f40a9 via fabric
	- fabric-key-binding-api-v1 1.0.18+9ff28f40a9 via fabric
	- fabric-keybindings-v0 0.2.16+df3654b3a9 via fabric
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
	- fabric-loot-api-v2 1.0.1+9e7660c6a9 via fabric
	- fabric-loot-tables-v1 1.1.1+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.8+33fbc738a9 via fabric
	- fabric-models-v0 0.3.15+9ff28f40a9 via fabric
	- fabric-networking-api-v1 1.0.27+7fe97409a9 via fabric
	- fabric-networking-v0 0.3.14+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.5+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-registry-sync-v0 0.9.16+92cf9a3ea9 via fabric
	- fabric-renderer-api-v1 1.0.8+9ff28f40a9 via fabric
	- fabric-renderer-indigo 0.6.6+9ff28f40a9 via fabric
	- fabric-renderer-registries-v1 3.2.18+df3654b3a9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-rendering-v0 1.1.20+df3654b3a9 via fabric
	- fabric-rendering-v1 1.10.14+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.3+9e7660c6a9 via fabric
	- fabric-screen-api-v1 1.0.23+9ff28f40a9 via fabric
	- fabric-screen-handler-api-v1 1.2.6+9ff28f40a9 via fabric
	- fabric-textures-v0 1.0.18+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabricloader 0.14.8
	- fart 1.0.0 via mcxr-play
	- iris 1.2.5
	- java 17
	- mcxr-core 0.2.2
	- mcxr-play 0.2.2
	- minecraft 1.19
	- org_anarres_jcpp 1.4.14 via iris
	- org_joml_joml 1.10.4 via mcxr-core
	- org_lwjgl_lwjgl-openxr 3.3.1 via mcxr-play
	- sodium 0.4.2+build.16
[16:17:24] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/loic/.local/share/PolyMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[16:17:24] [main/INFO]: Compatibility level set to JAVA_16
[16:17:24] [main/INFO]: Compatibility level set to JAVA_17
[16:17:24] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[16:17:25] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[16:17:26] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[16:17:26] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[16:17:30] [main/INFO]: Building optimized datafixer
[16:17:33] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[16:17:33] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:17:34] [Render thread/INFO]: Setting user: Lolothepro29
[16:17:35] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[16:17:35] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=2 on mixins.iris.json:texture.MixinAbstractTexture from mod iris::handler$zlm000$iris$afterGenerateId exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[16:17:36] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[16:17:36] [ForkJoinPool.commonPool-worker-1/WARN]: [Iris Update Check] Unable to download https://github.com/IrisShaders/Iris-Update-Index/releases/download/test/updateIndex.json
[16:17:38] [Render thread/INFO]: Debug functionality is disabled.
[16:17:38] [Render thread/INFO]: Profile: HIGH (+0 options changed by user)
[16:17:42] [Render thread/INFO]: Using shaderpack: ComplementaryShaders_v4.5.zip
[ALSOFT] (EE) Failed to set real-time priority for thread: Opération non permise (1)
[16:17:44] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[16:17:44] [Render thread/INFO]: Hardware information:
[16:17:44] [Render thread/INFO]: CPU: 12x AMD Ryzen 5 1600 Six-Core Processor
[16:17:44] [Render thread/INFO]: GPU: NVIDIA GeForce GTX 1070/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 515.43.04)
[16:17:44] [Render thread/INFO]: OS: Linux (5.17.0-15.1-liquorix-amd64)
[16:17:46] [Render thread/INFO]: Narrator library successfully loaded
[16:17:46] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Fart, Iris, [MCXR] Core, [MCXR] Play, Sodium)
[16:17:47] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[16:17:48] [Render thread/WARN]: [Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[16:17:51] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[16:17:51] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[ALSOFT] (EE) Failed to set real-time priority for thread: Opération non permise (1)
[16:17:51] [Render thread/INFO]: OpenAL initialized on device Family 17h (Models 00h-0fh) HD Audio Controller Stéréo analogique
[16:17:51] [Render thread/INFO]: Sound engine started
[16:17:52] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[16:17:52] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[16:17:52] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[16:17:52] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[16:17:52] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[16:17:52] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[16:17:52] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[16:17:54] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[16:17:55] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[16:17:55] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[16:17:55] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[16:18:10] [Render thread/INFO]: Loaded 7 recipes
[16:18:11] [Render thread/INFO]: Loaded 1179 advancements
[16:18:13] [Render thread/INFO]: Applied 0 biome modifications to 0 of 63 new biomes in 3.793 ms
[16:18:14] [Server thread/INFO]: Starting integrated minecraft server version 1.19
[16:18:14] [Server thread/INFO]: Generating keypair
[16:18:15] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[16:18:20] [Worker-Bootstrap-1/INFO]: 4256 Datafixer optimizations took 50576 milliseconds
[16:18:20] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[16:18:21] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[16:18:21] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[16:18:21] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[16:18:21] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[16:18:21] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[16:18:21] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[16:18:21] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[16:18:21] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[16:18:21] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[16:18:21] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[16:18:21] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[16:18:21] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[16:18:21] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[16:18:22] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[16:18:22] [Render thread/INFO]: Préparation de la zone d'apparition : 36 %
[16:18:23] [Render thread/INFO]: Time elapsed: 7991 ms
[16:18:23] [Server thread/INFO]: Changing view distance to 12, from 10
[16:18:23] [Server thread/INFO]: Changing simulation distance to 12, from 0
[16:18:23] [Netty Local Client IO #0/INFO]: Received login packet
[16:18:23] [Netty Server IO #1/INFO]: Received XR login packet from a0e1beb2-3608-4c97-bdef-629979a9a048
[16:18:23] [Server thread/INFO]: Lolothepro29[local:E:c3aed5c7] logged in with entity id 290 at (74.09937615112891, 80.36589166384259, -64.61738455722302)
[16:18:23] [Server thread/INFO]: Lolothepro29 a rejoint la partie
[16:18:24] [Render thread/INFO]: Started 6 worker threads
[16:18:25] [Render thread/INFO]: Loaded 0 advancements
[16:18:30] [Render thread/INFO]: Destroying pipeline OVERWORLD
[16:18:30] [Render thread/INFO]: Shaders are disabled because enableShaders is set to false in iris.properties
[16:18:30] [Render thread/INFO]: Shaders are disabled
[16:18:30] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[16:18:30] [Render thread/INFO]: Stopping worker threads
[16:18:30] [Render thread/INFO]: Started 6 worker threads
[16:18:30] [Render thread/INFO]: [CHAT] Shaders disabled!
[16:18:30] [Render thread/INFO]: Destroying pipeline OVERWORLD
[16:18:30] [Render thread/INFO]: Profile: HIGH (+0 options changed by user)
[16:18:31] [Render thread/INFO]: Using shaderpack: ComplementaryShaders_v4.5.zip
[16:18:31] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[16:18:31] [Render thread/WARN]: [Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[16:18:32] [Render thread/INFO]: Stopping worker threads
[16:18:32] [Render thread/INFO]: Started 6 worker threads
[16:18:32] [Render thread/INFO]: [CHAT] Shaders basculés sur ComplementaryShaders_v4.5.zip !
[16:18:34] [Render thread/INFO]: Destroying pipeline OVERWORLD
[16:18:34] [Render thread/INFO]: Shaders are disabled because enableShaders is set to false in iris.properties
[16:18:34] [Render thread/INFO]: Shaders are disabled
[16:18:34] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[16:18:34] [Render thread/INFO]: Stopping worker threads
[16:18:34] [Render thread/INFO]: Started 6 worker threads
[16:18:34] [Render thread/INFO]: [CHAT] Shaders disabled!
[16:18:34] [Render thread/INFO]: Destroying pipeline OVERWORLD
[16:18:34] [Render thread/INFO]: Profile: HIGH (+0 options changed by user)
[16:18:35] [Render thread/INFO]: Using shaderpack: ComplementaryShaders_v4.5.zip
[16:18:35] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[16:18:35] [Render thread/WARN]: [Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[16:18:35] [Render thread/INFO]: Stopping worker threads
[16:18:35] [Render thread/INFO]: Started 6 worker threads
[16:18:35] [Render thread/INFO]: [CHAT] Shaders basculés sur ComplementaryShaders_v4.5.zip !
[16:18:38] [Server thread/INFO]: Saving and pausing game...
[16:18:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Avess]'/minecraft:overworld
[16:18:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Avess]'/minecraft:the_nether
[16:18:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Avess]'/minecraft:the_end
[16:18:38] [Server thread/INFO]: Lolothepro29 lost connection: Déconnecté(e)
[16:18:38] [Server thread/INFO]: Lolothepro29 a quitté la partie
[16:18:38] [Server thread/INFO]: Stopping singleplayer server as player logged out
[16:18:38] [Server thread/INFO]: Stopping server
[16:18:38] [Server thread/INFO]: Saving players
[16:18:38] [Server thread/INFO]: Saving worlds
[16:18:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Avess]'/minecraft:overworld
[16:18:40] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Avess]'/minecraft:the_nether
[16:18:40] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Avess]'/minecraft:the_end
[16:18:40] [Server thread/INFO]: ThreadedAnvilChunkStorage (Avess): All chunks are saved
[16:18:40] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[16:18:40] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[16:18:40] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[16:18:40] [Render thread/INFO]: Stopping worker threads
[16:18:41] [Render thread/INFO]: Stopping!
```

### Minecraft Version

Minecraft 1.18.2

### Iris Version

iris-mc-1.18.2-1.2.5

### Sodium Version

sodium 0.4.2

### Operating System

Ubuntu 22.04

### What is your GPU?

GTX 1070

### Java Version

Java 17

**Comment by ggraycious** [comment] 2022-06-21 23:02
bump

**Comment by IMS212** [comment] 2022-06-22 01:10
debump

We don’t have enough info to find the cause yet

**Comment by coderbot16** [comment] 2022-07-14 04:05
Seems to be a duplicate of https://github.com/IrisShaders/Iris/issues/1491

**Closed by coderbot16** 2022-07-14 04:05 UTC
Labels: bug
