### ISSUE TITLE
No black outlines on blocks

### ISSUE THREAD

**Issue by Kisielson** [IrisShaders/Iris#546] opened 2021-07-15 11:48 UTC
### What happened?

No black outlines on block on any shaders. When I disable the shaders everything is ok

### Screenshots

![2021-07-15_13 46 10](https://user-images.githubusercontent.com/87478472/125783007-5dbfaa48-0cc6-40b0-ade5-a32e4110ab6a.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.0 for minecraft 1.17

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

AMD RX 570

### Java Version

Java 16

**Comment by TabulateJarl8** [comment] 2021-07-17 00:42
I believe this is a duplicate of #403. Recommending that this is closed

**Closed** 2021-07-17 00:43 UTC
Labels: bug
