### ISSUE TITLE
Minecraft Crashes whenever I join a world

### ISSUE THREAD

**Issue by EinfachStam** [IrisShaders/Iris#1613] opened 2022-08-28 11:16 UTC
### Minecraft Version

Minecraft Fabric 1.19.2

### Iris Version

iris-mc1.19.2-1.2.7

### Sodium Version

sodium-fabric-mc1.19-0.4.2

### Operating System

Windows 11

### What is your GPU?

NVidia GeForce RTX 2070 Super

### Java Version

Java 16

### Reproduction Steps

1. Start Minecraft
2. Choose if you want to join a Singleplayer world or a Multiplayer server (both produces the same crash)
3. Join a world or serve
[latest.log](https://github.com/IrisShaders/Iris/files/9439534/latest.log)
[crash-2022-08-28_13.11.38-client.txt](https://github.com/IrisShaders/Iris/files/9439535/crash-2022-08-28_13.11.38-client.txt)

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2022-08-28 13:11:38
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "field_3911" because "this.field_4015.field_1724" is null
	at net.minecraft.class_757.method_3188(class_757.java:1012)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_757.method_3188(class_757.java:1012)

-- Affected level --
Details:
	All players: 24 total; [class_745['Jwnk'/1098918, l='ClientLevel', x=376.50, y=36.00, z=554.50], class_745['sp00ky666'/1106991, l='ClientLevel', x=376.50, y=37.00, z=554.50], class_745['Fuzzle_Bee'/1100800, l='ClientLevel', x=356.19, y=35.00, z=544.79], class_745['siren06'/1105294, l='ClientLevel', x=375.81, y=39.02, z=565.46], class_745['SlenderGuyYT'/1096586, l='ClientLevel', x=358.87, y=36.00, z=563.15], class_745['Bambiithyst'/1106486, l='ClientLevel', x=371.40, y=35.00, z=560.29], class_745['Arazhul1795'/1106081, l='ClientLevel', x=370.62, y=35.00, z=548.37], class_745['GiganticFlame20'/1094990, l='ClientLevel', x=365.35, y=38.00, z=553.08], class_745['CypnX'/1089048, l='ClientLevel', x=336.43, y=36.00, z=567.28], class_745['DarthDorse'/1105785, l='ClientLevel', x=414.69, y=29.99, z=547.28], class_745['WbClyde'/1098796, l='ClientLevel', x=351.16, y=35.00, z=543.44], class_745['Davidag0611'/1106682, l='ClientLevel', x=376.50, y=36.00, z=554.50], class_745['DerGehasste'/1099703, l='ClientLevel', x=374.26, y=36.00, z=571.70], class_745['xCrystalz_'/1103492, l='ClientLevel', x=413.58, y=38.00, z=554.14], class_745['Sorbetes'/1104705, l='ClientLevel', x=370.09, y=36.00, z=568.85], class_745['LapisGames'/1106388, l='ClientLevel', x=376.50, y=36.00, z=554.50], class_745['zzTaco'/1104901, l='ClientLevel', x=376.50, y=36.00, z=554.50], class_745['Emmyp0ps'/1098306, l='ClientLevel', x=357.57, y=36.00, z=574.73], class_745['NevvR'/1103590, l='ClientLevel', x=376.50, y=36.00, z=554.50], class_745['JackIsAJack'/1105687, l='ClientLevel', x=376.50, y=36.00, z=554.50], class_745['LukynkaCZE'/1068878, l='ClientLevel', x=365.30, y=38.00, z=556.81], class_745['Crysaphine'/1085234, l='ClientLevel', x=353.79, y=37.00, z=553.74], class_745['a_bad_idea'/1106584, l='ClientLevel', x=376.50, y=36.00, z=554.50], class_745['EAron3'/1102878, l='ClientLevel', x=361.86, y=36.00, z=558.97]]
	Chunk stats: 1024, 207
	Level dimension: minecraft:temp_world_ffde0254-9844-4f64-aebf-8fb4aebfc7bb
	Level spawn location: World: (8,-63,8), Section: (at 8,1,8 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 31821 game time, 1 day time
	Server brand: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.class_746.method_3135()" because "this.field_3729.field_1724" is null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: No
	Packs: Default, HardcorePack, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, 10677ec27d959cbde59c3768253a75ccc48e5261, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 540133016 bytes (515 MiB) / 939524096 bytes (896 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37561.81
	Virtual memory used (MB): 14090.62
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		betterf3: BetterF3 1.3.2
		bettermounthud: Better Mount HUD 1.1.4
		camerautils: Camera Utils 1.19.2-1.0.2
		clientcommands: Client Commands 2.7.3
			clientarguments: clientarguments 1.4.1
			multiconnect-api: MultiConnect API 1.5.10
		continuity: Continuity 2.0.1+1.19
		effective: Effective 1.2.2
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		fabric-api: Fabric API 0.60.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.11+e62f51a390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.9+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.17+aeb40ebe90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.20+aeb40ebe90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.1+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.11+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.7+0c17ea9690
			fabric-commands-v0: Fabric Commands (v0) 0.2.28+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.34+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.3+aeb40ebe90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.1+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.5+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.8+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.30+aeb40ebe90
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.18+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.28+aeb40ebe90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.28+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.21+aeb40ebe90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.7+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.28+aeb40ebe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.20+aeb40ebe90
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.18+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.2+aeb40ebe90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.3+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.6+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.3+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.14+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.17+aeb40ebe90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.4+5eb68ef290
			fabric-networking-v0: Fabric Networking (v0) 0.3.21+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.11+aeb40ebe90
			fabric-particles-v1: Fabric Particles (v1) 1.0.10+aeb40ebe90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.24+aeb40ebe90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.10+aeb40ebe90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.12+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.20+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.14+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.7+aeb40ebe90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.22+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.16+aeb40ebe90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.11+e62f51a390
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.1+aeb40ebe90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.26+f05effaf90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.13+9ff28f4090
			fabric-textures-v0: Fabric Textures (v0) 1.0.20+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.11+83a8659290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.0+42d99c3290
		fabricloader: Fabric Loader 0.14.9
		ferritecore: FerriteCore 4.2.1
		forgetmechunk: Forget Me Chunk 1.0.4-1.18.X-1.19.X
		freecam: Freecam 1.1.4
			cloth-config: Cloth Config v6 7.0.73
				cloth-basic-math: cloth-basic-math 0.6.1
		illuminations: Illuminations 1.10.8
		indium: Indium 1.0.7+mc1.19
		inventorytabs: Inventory Tabs 0.8.1-1.19.x
		iris: Iris 1.2.7
			org_anarres_jcpp: jcpp 1.4.14
		itemscroller: Item Scroller 0.17.1
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lazydfu: LazyDFU 0.1.3
		litematica: Litematica 0.12.4
		litematica_printer: Litematica Printer 2.5
		lithium: Lithium 0.8.3
		malilib: MaLiLib 0.13.0
		minecraft: Minecraft 1.19.2
		minihud: MiniHUD 0.23.3
		modmenu: Mod Menu 4.0.6
		replaymod: Replay Mod 1.19.1-2.6.8
		sodium: Sodium 0.4.2+replaymod.rev.bfbc6de
			org_joml_joml: joml 1.10.4
		starlight: Starlight 1.1.1+fabric.ae22326
		technomodel: technomodel 1.0.2
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.9-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.94, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/HardcorePack, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor
```

### Additional context

This only happens on the current version of Iris (1.2.7) while downgrading to 1.2.6 solves the problem

**Comment by NotJansel** [comment] 2022-08-28 11:32
duplicate of #1609

**Comment by Bane8832** [comment] 2022-08-28 22:15
The exact same thing happened to me. I would like to update to the new version  but it keeps causing the game to crash, please resolve.

**Comment by SuperStarFFC** [comment] 2022-08-28 22:48
just wanted to say I encountered this same issue. Temporarily reverted to previous version.  added my own crash report for additional information.  Quick system specs : Ryzen 5 3600, 16gb ram, rx 580 8gb, windows 11
[crash-2022-08-28_18.32.47-client.txt](https://github.com/IrisShaders/Iris/files/9440595/crash-2022-08-28_18.32.47-client.txt)

**Comment by IMS212** [comment] 2022-08-29 00:19
I've hotfixed Iris 1.2.7 to fix the warning screen.

**Closed by IMS212** 2022-08-29 00:19 UTC
Labels: crash
