### ISSUE TITLE
[BUG] Invisable Menu/Inventory

### ISSUE THREAD

**Issue by WildFyr16** [IrisShaders/Iris#1478] opened 2022-06-10 05:44 UTC
### What happened?

The Player hand/tool, inventory, and menus are invisible. Upon removal of Iris, the game works correct again. Also, when the game is in this invisible mode, you cannot break blocks or do anything that requires over 1 click(like breaking grass). Using F3 allows you to see your inventory and escape menu. however, upon closing F3 the GUI closes again. I have tried removing all other mods other than Sodium and Iris and the issue persists.

### Screenshots

With Iris - https://media.wildfyr.net/WildFyr/yOB8L4.gif
Without Iris - https://media.wildfyr.net/WildFyr/2oS2Hb.gif

### Relevant log output

```shell
https://pastebin.com/dC6iY7Pu
```

### Minecraft Version

Minecraft Version 1.19.0

### Iris Version

iris-mc1.19-1.2.5

### Sodium Version

sodium-fabric-mc1.19-0.4.2build.16

### Operating System

Windows 11

### What is your GPU?

NVIDIA GeForce RTX 2070

### Java Version

Java 17.0.3 64bit

**Comment by star-whisper9** [comment] 2022-06-13 16:24
I reproduced the same problem: invisible handheld items, GUI, **and containers like chests/shulker boxes not being rendered**. In my case it looks like the problem comes from the VoxelMap mod. I'm not sure about the root cause of the problem.

I tested the mods I installed one by one, and the problem arises if and only if the following mods are installed:
```
fabric-api-0.55.3
iris-1.2.5
modmenu-4.0.0
sodium-fabric-0.4.2+build.16
voxelmap-1.11.6
```
When I removed VoxelMap from the above list, all GUI and container rendering went back to normal.

**When I just install Iris and Sodium, the problem doesn't appear.**

**Comment by WildFyr16** [comment] 2022-06-14 00:00
I will try with just  Voxel map tonight. It would work fine after I removed all mods and added them back 1 by 1 but after the next restart it would go back to not working until I removed Iris and started again from scratch with no mods

**Comment by fantahund** [comment] 2022-06-14 02:42
I have also noticed the bug, I have it too. But I do not know why. If you delete the iris config and put your shader back in, everything works again. Since I'm currently the only one who updates the voxelmap for 1.19, we could only fix the problem by working together. I have unfortunately too little knowledge of it ch just try to keep the map alive. But I am not a professional.

**Comment by IMS212** [comment] 2022-06-14 02:43
You're likely messing with vertex consumers in world and trying to reuse them out of world, confusing Iris.

**Comment by xoaoj** [comment] 2022-06-14 16:20
Theres a new version of voxel map, should fix.

**Comment by coderbot16** [comment] 2022-07-14 04:03
Closing since this was said to be fixed, if it isn't this can be reopened.

**Closed** 2022-07-14 04:02 UTC
Labels: bug
