### ISSUE TITLE
打开体素地图的大地图时崩溃/Crash when using VoxelMap

### ISSUE THREAD

**Issue by DSRoie** [IrisShaders/Iris#418] opened 2021-06-21 16:48 UTC
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 21-6-22 上午12:34
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:379)
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.renderShadows(DeferredWorldRenderingPipeline.java:651)
	at net.minecraft.class_761.handler$ckn000$iris$renderTerrainShadows(class_761.java:9152)
	at net.minecraft.class_761.method_22710(class_761.java:1149)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:379)
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.renderShadows(DeferredWorldRenderingPipeline.java:651)
	at net.minecraft.class_761.handler$ckn000$iris$renderTerrainShadows(class_761.java:9152)
	at net.minecraft.class_761.method_22710(class_761.java:1149)
	at net.minecraft.class_757.method_3188(class_757.java:727)

-- Affected level --
Details:
	All players: 1 total; [class_746['DS_Roie'/37697, l='ClientLevel', x=656.11, y=85.00, z=-740.04]]
	Chunk stats: Client Chunk Cache: 1024, 209
	Level dimension: minecraft:overworld
	Level spawn location: World: (-39,63,79), Chunk: (at 9,3,15 in -3,4; contains blocks -48,0,64 to -33,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 55681824 game time, 4225475 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 8963008440 bytes (8547 MB) / 10737418240 bytes (10240 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 8
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx10240m
	Fabric Mods: 
		adventurez: AdventureZ 1.2.2
		amecsapi: Amecs API 1.1.4+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		artifacts: Artifacts 3.2.1+fabric
		artifice: Artifice 0.14.6+1.16.5
		attributefix: Attribute Fix {FABRIC} 1.0.1
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autofish: Autofish 0.9.2
		backslot: BackSlot 1.1.11
		battletowers: Battle Towers 3.3.4-1.16.4
		bendy-lib: Bendy api 1.1.0
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
		betterend: Better End 0.9.6-pre
		betterf3: BetterF3 1.1.3
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.1
		betternether: Better Nether 5.0.7
		bettersleeping: Better Sleeping 0.4.0
		betterstrongholds: YUNG's Better Strongholds 1.16.5-1.0
		betterthirdperson: Better Third Person 1.4.0
		black-powder: Black Powder 1.0.2
		blue_endless_jankson: jankson 1.2.0
		byg: BYG 1.1.8
		cardinal-components: Cardinal Components API 2.8.3
		cardinal-components-base: Cardinal Components API (base) 2.8.3
		cardinal-components-block: Cardinal Components API (blocks) 2.8.3
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.3
		cardinal-components-entity: Cardinal Components API (entities) 2.8.3
		cardinal-components-item: Cardinal Components API (items) 2.8.3
		cardinal-components-level: Cardinal Components API (world saves) 2.8.3
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.3
		cardinal-components-util: Cardinal Components API (utilities) 2.8.3
		cardinal-components-world: Cardinal Components API (worlds) 2.8.3
		cavebiomes: Cave Biomes 0.6.2
		chainmail: Chainmail 0.5.0
		chorus_links: Chorus Links 1.2.2
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.26
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.2.1
		colwater: ColWater 1.4.1
		cosmetic-armor: Cosmetic Armor 1.0.0
		couplings: Couplings 1.3.3
		cpas: conveniently placed armor slots 1.3.0+1.16.5
		crowdin-translate: CrowdinTranslate 1.2
		curios: Curios API 0.0.13-1.16.5
		dashloader: DashLoader 1.4.5
		deadlydaggers: DeadlyDaggers 1.0-1.16.5
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		dragonloot: DragonLoot 1.0.6
		dualwielding: Dual Wielding 1.0.2
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		eldritch_mobs: Eldritch Mobs 1.6.9
		emotecraft: Emotecraft 2.0.4
		enchant_giver: Enchant Giver 1.0.3
		enhancement: Enhancement (Fabric) 0.7.0
		expanded_weapon_enchanting: Expanded Weapon Enchanting 1.0.0
		expandedstorage: ExpandedStorage 5.6.33
		expcontainer: Experience Container [XP] 1.15
		extraalchemy: Extra Alchemy 1.4.5
		extrasounds: Extra Sounds 1.4.0
		fabric: Fabric API 0.34.2+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.1+kotlin.1.5.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		fabricshieldlib: Fabric Shield Lib 1.3.5-1.16.5
		fallingtree: FallingTree 2.11.0
		flytre_lib: FlytreLib 0.2.10
		geckolib3: Geckolib 3.0.36
		givemehats: Give Me Hats! 1.5.1
		gravestones: Gravestones v1.9
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		guardiansgalore: Guardians Galore 1.0-SNAPSHOT
		hole_filler_mod: Hole Filler Mod 1.2.4
		hookshot: Hookshot 13.0
		horseinfo: Horse Info 0.2.2-1.16.1
		illuminations: Illuminations 1.5.1
		inmis: Inmis 2.1.3-1.16.5
		inventory_control_tweaks: Inventory Control Tweaks 1.3.4+MC1.16.2-1.16.5
		inventoryprofiles: Inventory Profiles 0.4.2
		inventorysorter: Inventory Sorter 1.7.9-1.16
		io_activej_activej-codegen: activej-codegen 4.2
		io_activej_activej-serializer: activej-serializer 4.2
		iris: Iris 1.0.0-rc1
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kirin: Kirin UI 1.7-1.16.2
		kyrptconfig: Kytpt Config 1.1.6-1.16
		libgui: LibGui 3.3.2+1.16.4
		libstructure: LibStructure 1.5
		luckyblocks: Fabricated Lucky Blocks 1.0.0-1.16.5
		magic_mirror: Magic Mirror 1.2.1
		maybe-data: Maybe data 1.0.0-1.16.2
		mcda: MC Dungeons Armors 1.5.0
		mcdar: MC Dungeons Artifacts 1.2.0
		mcdw: MC Dungeons Weapons 3.2.0
		mcsa: MC Story Mode Armor 2.3.2
		medievalweapons: Medieval Weapons 1.1.3
		mimics: Mimics 0.1.4
		minecraft: Minecraft 1.16.5
		mobz: MobZ 2.4.6
		modmenu: Mod Menu 1.16.9
		multi_item_lib: Multi Item Lib 1.3.0
		nbtcrafting: NBT Crafting 2.0.14+mc1.16.4
		net_gudenau_lib_unsafe: unsafe 1.4.1
		obsdncontainer: Obsidian Container [Experience Container Addon] 1.0.1
		omega-config: OmegaConfig 1.0.2
		org_aeonbits_owner_owner: owner 1.0.12
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		org_slf4j_slf4j-api: slf4j-api 1.7.29
		phosphor: Phosphor 0.7.2+build.12
		polymorph: Polymorph 0.0.10-1.16.5
		presencefootsteps: Presence Footsteps r29+1.16.4
		rangers_haven: Ranger's Haven 2.2.1
		rare-ice: Rare Ice 0.2.2
		reach-entity-attributes: Reach Entity Attributes 1.1.0
		repurposed_structures: Repurposed Structures 1.16.5-1.10.5-fabric
		respawnablepets: Respawnable Pets 1.16.5-2
		roughlyenoughitems: Roughly Enough Items 5.11.218
		roughlyenoughitems-api: REI (API) 5.11.218
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.218
		roughlyenoughitems-runtime: REI (Runtime) 5.11.218
		rpgz: RPGZ 0.4.7
		seasons: Fabric Seasons 1.2-BETA
		servertick: Server Tick 1.4
		sit: Sit 1.16.5-11
		sodium: Sodium 0.2.0+IRIS_rev.400af47
		spellbound: Spellbound 1.3.0
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stitchedsnow: Stiched Snow 1.0.1
		stoneholm: Stoneholm 1.2.1
		structure-helpers: Structure Helpers 3.0.0
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.6
		torchbowmod: TorchBowMod 1.0-Beta
		torohealth: ToroHealth Damage Indicators 1.16.4-fabric-4
		transparent_cosmetics: Transparent Cosmetics 1.2.0
		transportables: Transportables 1.0.1
		trinkets: Trinkets 2.6.7
		voidz: VoidZ 1.0.0
		voxelmap: VoxelMap 1.10.15
		voyager: Voyager 1.0.0
		waila: Hwyla 1.9.22
		walljump: Wall-Jump! 1.3.3+1.16.1
		waystones: Waystones 1.1.1.1
		windchimes: Windchimes 1.1.1
		wolveswitharmor: Wolves With Armor 1.5.4-1.16.5
		xp_storage: XP Storage 1.4+1.16.5
		yalbm: Yet Another Lucky BLock Mod 1.2.2
		yungsapi: YUNG's API 1.16.5-Fabric-5
	Launched Version: 1.16.5-Fabric 0.11.3
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.47, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: minecraft:transparent_cosmetics, vanilla, file/真实天空材质 V2.0.zip (incompatible), file/UltimaCraft_(pre.8_fix2).zip, file/FreshAnimations_v1.2.zip, Fabric Mods, file/Light-Cycle-Resources-1.2.4
	Current Language: 简体中文 (中国)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

**Comment by AlsoNiko** [comment] 2021-06-25 16:05
This isn't an issue with iris and Voxel, I use both actively, not sure what it is though

**Comment by AlsoNiko** [comment] 2021-07-01 12:24
Remove dash loader

**Comment by coderbot16** [comment] 2021-09-09 19:57
Closing as a duplicate of #811. Even though this issue was created first, the other report contains more accurate & useful information.

**Closed by coderbot16** 2021-09-09 19:57 UTC
Labels: bug, invalid, more information needed
