### ISSUE TITLE
anvils seem to be detected as water on complementary 4.0.2 (1.17)

### ISSUE THREAD

**Issue by arceuss** [IrisShaders/Iris#352] opened 2021-06-10 02:29 UTC
![image](https://user-images.githubusercontent.com/28229451/121455203-4d404380-c961-11eb-98dc-1f6c5e55ab9f.png)
and a message from the shader dev
![image](https://user-images.githubusercontent.com/28229451/121455228-54675180-c961-11eb-8db0-0e0fd49568b8.png)

**Comment by IMS212** [comment] 2021-06-10 05:04
Duplicate of #340, this is due to separateAo not being implemented.

**Closed by IMS212** 2021-06-10 05:04 UTC
