### ISSUE TITLE
Shaders Fail to Load when Using a Custom Server Resource Pack

### ISSUE THREAD

**Issue by Th3LastSh3riff** [IrisShaders/Iris#1357] opened 2022-04-10 02:17 UTC
### What happened?

When loading into a server with a custom resource pack the shaders fail to load in; and when I get teleported or moved along to another part of the server the shaders also, fail to load in. Also, custom armor that uses the server resource pack fail to load, too.  The only solution I currently have is turning my shaders completely off then back on.

### Screenshots

![2022-04-09_22 14 39](https://user-images.githubusercontent.com/103339965/162598315-061fed96-0c09-45ec-9fca-cc7fae723efb.png)

### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.2.2-build.32.jar

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15.jar

### Operating System

Windows 11

### What is your GPU?

Nvidia Geforce RTX 3050Ti

### Java Version

Java 17

**Comment by Th3LastSh3riff** [comment] 2022-04-10 02:33
There is only this mod active all the custom resource packs are from the server and are vanilla.

**Comment by coderbot16** [comment] 2022-04-10 04:31
This is a duplicate of https://github.com/IrisShaders/Iris/issues/1042 and https://github.com/IrisShaders/Iris/issues/1330.

**Closed by coderbot16** 2022-04-10 04:31 UTC
Labels: bug
