### ISSUE TITLE
Problem with all my shaders

### ISSUE THREAD

**Issue by Potatooooos** [IrisShaders/Iris#1158] opened 2022-01-02 17:31 UTC
### What happened?

Hello, my problem is this white rectangle.

Regardless of the shader, I always have this rectangle in front of me.

### Screenshots

![2022-01-02_18 25 32](https://user-images.githubusercontent.com/96992521/147884050-cc30f3ac-138b-4fa2-b527-3b7b516d48a1.png)

### Minecraft Version

Minecraft 1.18.1

### Iris Version

iris-mc1.18.1-1.1.3

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5

### Operating System

Windows 10

### What is your GPU?

Nvidia RTX 3070 Ti

### Java Version

jre1.8.0_311

**Comment by edwloef** [comment] 2022-01-02 17:33
This is a known issue that occurs when your client render distance is higher than the server's

**Comment by edwloef** [comment] 2022-01-02 17:34
See here: https://github.com/IrisShaders/Iris/issues/1053

**Comment by AlsoSylv** [comment] 2022-01-02 17:37
Duplicate of #1053, fixed in development branches.

**Closed by AlsoSylv** 2022-01-02 17:37 UTC
Labels: bug
