### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by TheButterbrotMan** [IrisShaders/Iris#1267] opened 2022-02-05 14:14 UTC
### Minecraft Version

1.18.1

### Iris Version

mc1.18.1-1.2.0-pre

### Sodium Version

mc1.18.1-0.4.0-alpha6+build.14

### Operating System

Windows 10

### What is your GPU?

GeForce RTX 3060

### Java Version

Java 17

### Reproduction Steps

Not available

### Crash Report file and latest.log

```shell
https://bytebin.lucko.me/JWGyxER40Q
```

**Comment by NoComment1105** [comment] 2022-02-05 14:32
This crash appears to be caused by "Survival Plus". Could you try without it and see if it still happens. If not, please report the issue to the developer of said mod.

**Comment by NoComment1105** [comment] 2022-02-05 14:35
The cause of this crash appears to be a mod called `SurvivalPlus`. Could you test just Iris + Sodium + `SurvivalPlus` and see if the problem still occurs?

**Comment by coderbot16** [comment] 2022-02-05 18:45
These sorts of crashes are generally not the fault of Iris, but some mods have issues because of assumptions they make about when entities are rendered compared to other things, or assuming that entities will only be rendered once per frame. I doubt there's much for us to do about this.

**Comment by TheButterbrotMan** [comment] 2022-02-06 14:41
I will forward this to SurvivalPlus Devs

**Comment by coderbot16** [comment] 2022-02-09 17:05
I am going to close this issue for now. If it's confirmed to be an Iris issue and not a bug in the other mod, let me know and I will reopen it.

**Closed by coderbot16** 2022-02-09 17:05 UTC
Labels: crash
