### ISSUE TITLE
Spiders and endermen have black texture when running Iris v1.2.5 and Sodium v0.4.1 on Minecraft 1.18.2

### ISSUE THREAD

**Issue by U5B** [IrisShaders/Iris#1517] opened 2022-07-01 05:44 UTC
### What happened?

Spiders and endermen have black texture instead their normal texture.
However, downgrading Iris to v1.2.4 fixes the issue so it has to be caused by a relatively recent change.

### Screenshots

![image](https://user-images.githubusercontent.com/56985400/176831447-f17702a4-46b9-409f-8996-d60f4d0680ce.png)
![image](https://user-images.githubusercontent.com/56985400/176831107-f499cfc2-2dfc-431b-9827-b585d8dc94f7.png)

### Relevant log output

```shell
N/A
```

### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.2.5.jar

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 1060

### Java Version

Java 16

**Comment by coderbot16** [comment] 2022-07-01 19:47
Do you have any other mods and resource packs? You should try running with only Iris and Sodium and if it still happens you should post a log.

**Comment by U5B** [comment] 2022-07-02 00:23
> Do you have any other mods and resource packs? You should try running with only Iris and Sodium and if it still happens you should post a log.

I should've specified that I used only Sodium and Iris. I was testing with a resource pack. (https://github.com/U5B/MonumentaRP-NoOptiFine/releases/tag/v1.1.0)

Should check if it happens in vanilla.

**Comment by Lolothepro** [comment] 2022-08-10 11:47
https://faithfulpack.net/classicfaithful/32x-programmer-art

**Comment by Lolothepro** [comment] 2022-08-12 08:43
seems to be caused by https://github.com/IrisShaders/Iris/commit/0767f859d87e10b7db64e5c0c46dc6e9010b654d

**Comment by Lolothepro** [comment] 2022-08-22 11:53
https://github.com/IrisShaders/Iris/blob/trunk/src/main/java/net/coderbot/iris/mixin/rendertype/MixinRenderType_FixEyesTranslucency.java This should only be active if a shader is enabled. (https://github.com/sp614x/optifine/issues/4578)

**Comment by coderbot16** [comment] 2022-08-22 16:35
That doesn't really solve the problem, since it just makes it look like it's caused by the shader instead of the resource pack.

**Comment by IMS212** [comment] 2022-11-03 20:27
This should be fixed with 1.4.1, can someone check?

**Comment by Lolothepro** [comment] 2022-11-03 20:36
> This should be fixed with 1.4.1, can someone check?

fixed

Iris 1.4.0:
![2022-11-03_21 33 33](https://user-images.githubusercontent.com/68275908/199828715-0c16b544-3e83-411f-be76-2c68e4550c36.png)

Iris 1.4.1pre:
![2022-11-03_21 34 30](https://user-images.githubusercontent.com/68275908/199828746-5808b562-ec28-4e3d-bdbc-94a925155f06.png)

**Closed** 2022-11-27 19:55 UTC
Labels: bug, status: fixed in next release
