### ISSUE TITLE
Mobs do not flash red when hurt using Sildurs Vibrant High in 1.17

### ISSUE THREAD

**Issue by Mr-Waterscout** [IrisShaders/Iris#372] opened 2021-06-12 01:38 UTC
In 1.17 with Sildurs Vibrant High, the mobs do not flash red when I hurt them. I suspect this is a known bug, but I'm mentioning it in case it isn't.

**Comment by AlsoNiko** [comment] 2021-06-12 01:39
It's a known bug, not just on 1.17, this is a duplicate of #72 so the issue is going to be marked as closed

**Closed by AlsoNiko** 2021-06-12 01:39 UTC
