### ISSUE TITLE
Bumpmap/Connected Textures support

### ISSUE THREAD

**Issue by kingarthur0975** [IrisShaders/Iris#577] opened 2021-07-18 17:46 UTC
Support for Parallax Mapping/normal maps would be putting the icing on the cake for this mod to be the perfect shaders/performance mod. As for connected textures, it would just look nice.

**Comment by IMS212** [comment] 2021-07-18 17:48
Connected textures is done by other mods already, however PBR is planned in the future for Iris.

**Comment by IMS212** [comment] 2021-07-18 17:50
Duplicate of #130 for now, closing.

**Closed by IMS212** 2021-07-18 17:50 UTC
Labels: enhancement

**Comment by SirPytan** [comment] 2021-08-13 22:28
@IMS212 But connected textures support is not working properly or is not completely integrated in the mods. I tried using the fabric mod that tries to replicate the optifine integration, but the Patrix Resourcepack looks broken and not correctly working with it, so that is why it would be nice, if there would exist native support from Iris.

**Comment by just-chubbyfoxx** [comment] 2021-08-13 22:29
Connected textures are probably not gonna be added into iris
No plans
Plus, iris is not a complete utility mod
Its shaders with performance

**Comment by SirPytan** [comment] 2021-08-13 22:32
But, aren't connected textured solved with shaders?

**Comment by IMS212** [comment] 2021-08-13 22:33
No, they are entirely different features that are independent.

**Comment by SirPytan** [comment] 2021-08-13 22:37
Ok, but do you know a working alternative?
Because Connected Block Textures, is only in Beta and not even updated over a year, so no version for 1.17.1 and the ones in the comments does not work correctly. So any idea. Because the other Connected Textures mod does not use the Optifine format.

**Comment by IMS212** [comment] 2021-08-13 22:39
There are other mods in progress for this, but none currently.

**Comment by SirPytan** [comment] 2021-08-13 22:40
Do you know which ones are in progress, to deliver feature parity with optifine connected textures?

**Comment by SirPytan** [comment] 2021-08-13 22:48
@IMS212 Can you tell which ones are in progress?

**Comment by IMS212** [comment] 2021-08-13 22:48
Sadly none are public at all right now.

**Comment by SirPytan** [comment] 2021-08-13 22:49
@IMS212 But can you tell me the names anyways, so I know which ones to look for when the come out?

**Comment by IMS212** [comment] 2021-08-13 22:51
as i meant to say, they have no names either. there will likely be a few announcements in fabric-related servers when they are released.

**Comment by SirPytan** [comment] 2021-08-13 22:53
Ok, thanks anyways. But it would be a opportunity for Iris to become the Optifine of Fabric or least to work together with the developers of the not released version, to integrate it with Iris. I think it would be worth to think about that.

**Comment by just-chubbyfoxx** [comment] 2021-08-14 04:06
Eyo, you can use ConnectedTexturesMod instead.

**Comment by SirPytan** [comment] 2021-08-14 10:43
@just-chubbyfoxx No I can't if you read the mod description, it says, it does not use the Optifine format, so it's not what I need.

**Comment by yitzy299** [comment] 2021-08-14 10:44
> @just-chubbyfoxx No I can't if you read the mod description, it says, it does not use the Optifine format, so it's not what I need.

You can use the format supported by it, or you can use connected block textures. Please ask on the discord if you're looking for a mod

**Comment by SirPytan** [comment] 2021-08-14 10:47
@yitzy299 If the Resourcepack I want to use, only supports optifine format, it is not helpful to use a mod, that does support a different format. Anyways, which Discord do you mean, can you sent me an invite?

**Comment by yitzy299** [comment] 2021-08-14 10:48
It supports the optifine format, as I said. Join the iris discord for further discussion

**Comment by SirPytan** [comment] 2021-08-14 10:55
> > @just-chubbyfoxx No I can't if you read the mod description, it says, it does not use the Optifine format, so it's not what I need.
> 
> You can use the format supported by it, or you can use connected block textures. Please ask on the discord if you're looking for a mod

Yes, the mod does support it, but:
1. Not in the full extend, its still in Beta
2. It did not got updated for 1.17.1 the version someone created in the comments does not work.
