### ISSUE TITLE
Iris Support for VulkanAPI

### ISSUE THREAD

**Issue by LiberteIV** [IrisShaders/Iris#1722] opened 2022-10-30 14:50 UTC
Hello,

I'm here to mention this mod https://github.com/xCollateral/VulkanMod which allows to start minecraft with the Vulkan API instead of OpenGL, chances are if the mod get's enough attention.. it might support FidelityFX Super Resolution which will drastically improve performance.
As an example this mod https://www.nexusmods.com/aplaguetalerequiem/mods/9 replaces DLSS with FSR in A Plague Tale Requiem, without the mod i had an average of 40 FPS on a GTX 1080 Ti 1440p ultra settings. With the FSR mod on Quality mode i had an average 80 FPS with the same settings while the image still looked even better then native.
Those results are crazy.
I beleve this (DLSS and FSR) are the future and will be supported by all major upcomming games.
The potential is to much to be ignored, my opinion.

Taking a look at VulkanMod's github page it clearly says this: "This is a fabric mod that rewrites Minecraft OpenGL renderer to use Vulkan API."
With 12,163 downloads the mod is still pretty smal compared to fabric / optifine / sodium, then again imagine what Fabric, VulkanAPI, Optifine, and FidelityFX Super Resolution could do together, i have no doubt minecraft's performance would skyrocket.

Seus Shader and Patrix Resourcepack are very performance hungry, getting an average 60 FPS with both enabled, i consider them both mandatory for playing minecraft as they look really good.
With Vulkan and FSR those 60 FPS could easily turn into 120.
At this moment using optifine with fabric requires optifabric, combining those mods with vulkanmod results in a game-crash.
By creating this "issue" i hope to bring more attention to the vulkanmod and it's potential for FSR.
If fabric, optifine, and optifabric would officialy support vulkanmod

Just like Optifine, Sodium and Iris also crash combined with Vulkanmod.
With fabric loader OpenGL and sodium i get 1300 FPS max when looking at the sky.
With fabric loader and vulkanmod i get 1150 FPS max when looking at the sky.
Combine those and...

![Seus PTGI + Patrix](https://user-images.githubusercontent.com/116210112/198885316-b9ad5b1d-8915-4930-8608-4686f6a21209.png)

![Survival House](https://user-images.githubusercontent.com/116210112/198885318-d6fbdd3e-148c-4dc4-9573-2aa7f457943e.png)

![Dragons](https://user-images.githubusercontent.com/116210112/198885323-e63fc6e8-80fd-4b43-be9b-04aabcb48cb1.png)

![Argonath LOTR](https://user-images.githubusercontent.com/116210112/198885325-3ff371ad-2f63-46b4-a40b-725b8af9cb22.png)

**Comment by Lolothepro** [comment] 2022-10-30 14:55
duplicate of #1515

**Comment by AlsoSylv** [comment] 2022-10-30 14:55
We do not have any plans to support Vulkan replacement mods as of now, as it would require a major rewrite of the Iris pipeline.

Duplicate of #1515

**Closed by AlsoSylv** 2022-10-30 14:55 UTC
Labels: enhancement

**Comment by NotJansel** [comment] 2022-10-30 17:24
Goddamnit stop opening an issue in every render performance mod thank you

**Comment by r4ph1-2015** [comment] 2026-06-21 07:05
> Hello,
> 
> 
> 
> I'm here to mention this mod https://github.com/xCollateral/VulkanMod which allows to start minecraft with the Vulkan API instead of OpenGL, chances are if the mod get's enough attention.. it might support FidelityFX Super Resolution which will drastically improve performance.
> 
> As an example this mod https://www.nexusmods.com/aplaguetalerequiem/mods/9 replaces DLSS with FSR in A Plague Tale Requiem, without the mod i had an average of 40 FPS on a GTX 1080 Ti 1440p ultra settings. With the FSR mod on Quality mode i had an average 80 FPS with the same settings while the image still looked even better then native.
> 
> Those results are crazy.
> 
> I beleve this (DLSS and FSR) are the future and will be supported by all major upcomming games.
> 
> The potential is to much to be ignored, my opinion.
> 
> 
> 
> Taking a look at VulkanMod's github page it clearly says this: "This is a fabric mod that rewrites Minecraft OpenGL renderer to use Vulkan API."
> 
> With 12,163 downloads the mod is still pretty smal compared to fabric / optifine / sodium, then again imagine what Fabric, VulkanAPI, Optifine, and FidelityFX Super Resolution could do together, i have no doubt minecraft's performance would skyrocket.
> 
> 
> 
> Seus Shader and Patrix Resourcepack are very performance hungry, getting an average 60 FPS with both enabled, i consider them both mandatory for playing minecraft as they look really good.
> 
> With Vulkan and FSR those 60 FPS could easily turn into 120.
> 
> At this moment using optifine with fabric requires optifabric, combining those mods with vulkanmod results in a game-crash.
> 
> By creating this "issue" i hope to bring more attention to the vulkanmod and it's potential for FSR.
> 
> If fabric, optifine, and optifabric would officialy support vulkanmod
> 
> 
> 
> Just like Optifine, Sodium and Iris also crash combined with Vulkanmod.
> 
> With fabric loader OpenGL and sodium i get 1300 FPS max when looking at the sky.
> 
> With fabric loader and vulkanmod i get 1150 FPS max when looking at the sky.
> 
> Combine those and...
> 
> 
> 
> ![Seus PTGI + Patrix](https://user-images.githubusercontent.com/116210112/198885316-b9ad5b1d-8915-4930-8608-4686f6a21209.png)
> 
> 
> 
> 
> 
> 
Vulkan support for Minecraft Java 26.2 has already been added. OpenGL is being deprecated from Minecraft Java to allow Vibrant Visuals. Iris shaders will not be adding support for Vulkan instead You will need to use other ones.

**Comment by Lolothepro** [comment] 2026-06-21 09:09
> > Hello,
> > I'm here to mention this mod https://github.com/xCollateral/VulkanMod which allows to start minecraft with the Vulkan API instead of OpenGL, chances are if the mod get's enough attention.. it might support FidelityFX Super Resolution which will drastically improve performance.
> > As an example this mod https://www.nexusmods.com/aplaguetalerequiem/mods/9 replaces DLSS with FSR in A Plague Tale Requiem, without the mod i had an average of 40 FPS on a GTX 1080 Ti 1440p ultra settings. With the FSR mod on Quality mode i had an average 80 FPS with the same settings while the image still looked even better then native.
> > Those results are crazy.
> > I beleve this (DLSS and FSR) are the future and will be supported by all major upcomming games.
> > The potential is to much to be ignored, my opinion.
> > Taking a look at VulkanMod's github page it clearly says this: "This is a fabric mod that rewrites Minecraft OpenGL renderer to use Vulkan API."
> > With 12,163 downloads the mod is still pretty smal compared to fabric / optifine / sodium, then again imagine what Fabric, VulkanAPI, Optifine, and FidelityFX Super Resolution could do together, i have no doubt minecraft's performance would skyrocket.
> > Seus Shader and Patrix Resourcepack are very performance hungry, getting an average 60 FPS with both enabled, i consider them both mandatory for playing minecraft as they look really good.
> > With Vulkan and FSR those 60 FPS could easily turn into 120.
> > At this moment using optifine with fabric requires optifabric, combining those mods with vulkanmod results in a game-crash.
> > By creating this "issue" i hope to bring more attention to the vulkanmod and it's potential for FSR.
> > If fabric, optifine, and optifabric would officialy support vulkanmod
> > Just like Optifine, Sodium and Iris also crash combined with Vulkanmod.
> > With fabric loader OpenGL and sodium i get 1300 FPS max when looking at the sky.
> > With fabric loader and vulkanmod i get 1150 FPS max when looking at the sky.
> > Combine those and...
> > ![Seus PTGI + Patrix](https://user-images.githubusercontent.com/116210112/198885316-b9ad5b1d-8915-4930-8608-4686f6a21209.png)
> 
> Vulkan support for Minecraft Java 26.2 has already been added. OpenGL is being deprecated from Minecraft Java to allow Vibrant Visuals. Iris shaders will not be adding support for Vulkan instead You will need to use other ones.

OpenGL is not deprecated, it will be when Vulkan becomes the default API
