### ISSUE TITLE
Render scale and shadow quality

### ISSUE THREAD

**Issue by 4194304** [IrisShaders/Iris#2052] opened 2023-07-11 23:54 UTC
**Is your feature request related to a problem? Please describe.**
I have a 1050 Ti, a fairly low end graphics card that isn't exactly the best for running shaders like Complementary at a stable 60 fps on default settings. However, the render scale option lets me sacrifice rendering quality for performance which I really like. The shadow quality option could let me downscale/upscale shadows further than what the shader supports, for example, SEUS PTGI is a shader where you can't change the shadow resolution. This would allow shaders to run on incapable/lower-end machines at a much higher framerate.

**Describe the solution you'd like**
Have two buttons like with OptiFine to control these settings on the shader menu.

**Describe alternatives you've considered**
Fast graphics

**Additional context**
![2023-07-11_16 48 57](https://github.com/IrisShaders/Iris/assets/130800536/44275540-d804-445d-bfbe-f61e7fc6f996)
OptiFine menu

Possibly it could look like this:
![2023-07-11_16 50 31 - Copy](https://github.com/IrisShaders/Iris/assets/130800536/a9ffb558-db3f-442b-aaae-54238cd568e0)
Being able to type a custom value in instead of tapping the button over and over to get the setting you want would also be great

**Comment by douira** [comment] 2023-07-12 00:10
Iris is purely a shader mod and doesn't generally cover additional features that Optifine, which is a kitchen sink of client features, may include. [ResolutionControl+](https://modrinth.com/mod/resolution-control-plus) is a separate mod that gives you this particular feature. Further Optifine features are implemented by the mods listed on this page: https://lambdaurora.dev/optifine_alternatives/

**Comment by Lolothepro** [comment] 2023-07-12 13:40
duplicate of #757

**Comment by 4194304** [comment] 2023-07-13 02:45
Tested ResolutionControl+, it is pretty nice but the linear downscaling method seems to be a bit worse than OptiFine's

**Comment by 4194304** [comment] 2023-07-16 02:40
Can't close this so it will remain open until someone closes it

**Closed** 2023-08-18 16:49 UTC
Labels: enhancement
