### ISSUE TITLE
Not Enough Crashes allows the game to continue initializing after a fatal entrypoint error, breaking Iris

### ISSUE THREAD

**Issue by TT6Programming** [IrisShaders/Iris#930] opened 2021-10-12 15:35 UTC
Error:
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Cannot invoke "net.coderbot.iris.pipeline.PipelineManager.getPipeline()" because the return value of "net.coderbot.iris.Iris.getPipelineManager()" is null

**Comment by Anti27** [comment] 2021-11-06 05:33
same here:
---- Minecraft Crash Report ----
// My bad.

Time: 11/6/21, 6:18 AM
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "net.coderbot.iris.pipeline.PipelineManager.getPipeline()" because the return value of "net.coderbot.iris.Iris.getPipelineManager()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.63)
	at net.minecraft.client.render.GameRenderer.isPhase(GameRenderer:7315)
	at net.minecraft.client.render.GameRenderer.handler$dma000$iris$overridePositionShader(GameRenderer:7045)
	at net.minecraft.client.render.GameRenderer.getPositionShader(GameRenderer)
	at com.mojang.blaze3d.systems.RenderSystem.setShader(RenderSystem:1137)
	at net.minecraft.client.render.WorldRenderer.renderStars(WorldRenderer:645)
	at net.minecraft.client.render.WorldRenderer.<init>(WorldRenderer:278)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:573)
	at net.minecraft.client.main.Main.main(Main:179)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_757.isPhase(class_757.java:7315)
	at net.minecraft.class_757.handler$dma000$iris$overridePositionShader(class_757.java:7045)
	at net.minecraft.class_757.method_34539(class_757.java)
	at com.mojang.blaze3d.systems.RenderSystem.setShader(RenderSystem.java:1137)
	at net.minecraft.class_761.method_3293(class_761.java:645)
	at net.minecraft.class_761.<init>(class_761.java:278)
	at net.minecraft.class_310.<init>(class_310.java:573)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by AmibeSkyfy16** [comment] 2021-11-10 07:03
I have this crash too
this is my log:
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11/10/21, 8:01 AM
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "net.coderbot.iris.pipeline.PipelineManager.getPipeline()" because the return value of "net.coderbot.iris.Iris.getPipelineManager()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.63)
	at net.minecraft.client.render.GameRenderer.isPhase(GameRenderer:5815)
	at net.minecraft.client.render.GameRenderer.handler$ceg000$iris$overridePositionShader(GameRenderer:5545)
	at net.minecraft.client.render.GameRenderer.getPositionShader(GameRenderer)
	at com.mojang.blaze3d.systems.RenderSystem.setShader(RenderSystem:1137)
	at net.minecraft.client.render.WorldRenderer.renderStars(WorldRenderer:645)
	at net.minecraft.client.render.WorldRenderer.<init>(WorldRenderer:278)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:573)
	at net.minecraft.client.main.Main.main(Main:179)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_757.isPhase(class_757.java:5815)
	at net.minecraft.class_757.handler$ceg000$iris$overridePositionShader(class_757.java:5545)
	at net.minecraft.class_757.method_34539(class_757.java)
	at com.mojang.blaze3d.systems.RenderSystem.setShader(RenderSystem.java:1137)
	at net.minecraft.class_761.method_3293(class_761.java:645)
	at net.minecraft.class_761.<init>(class_761.java:278)
	at net.minecraft.class_310.<init>(class_310.java:573)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 84040792 bytes (80 MiB) / 553648128 bytes (528 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 32
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5950X 16-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2486
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9649
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 75188.23
	Virtual memory used (MB): 25103.82
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 0.00
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		achievement_plates: Achievement Plates 1.4
		additionalbars: Additional Bars 2.1.1
		adorn: Adorn 2.3.1+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		advancementinfo: AdvancementInfo 1.17.1-fabric0.36.1-1.2.1
		advancementplaques: Advancement Plaques 1.4.2
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		aqupdcaracal: Caracal mob 1.17-1.3.2
		aqupdgrizzly: Grizzly Bear mob 1.17-1.2.0
		architectury: Architectury 2.6.35
		artifacts: Artifacts 5.0.2+fabric
		bendy-lib: Bendy api 2.0.2
		betterbeds: Better Beds 1.2.0
		betterf3: BetterF3 1.1.5
		betterpingdisplay: Better Ping Display 1.1
		blockmeter: Block Meter ${version}
		blue_endless_jankson: jankson 1.2.1
		boatcontainer: BoatContainer 1.0.3
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.2-1.17.1
		bountiful: Bountiful 1.0.0
		caelus: Caelus API 0.0.18-1.17.1
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		carrier: Carrier 1.8.1
		charmonium: Charmonium 3.3.0
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 0.0.7-1.17.1
		cool_elytra: Cool Elytra 1.3.0
		croptopia: Croptopia 1.6.3
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customizableelytra: Customizable Elytra 1.5.1-1.17
		deathlog: DeathLog 0.2.2
		decapitation: Decapitation 1.0.0
		drinkbeer: Drink Beer 2.3
		dual_riders: DualRiders 1.0.5
		easiercrafting: EasierCrafting 1.17.1-fabric0.36.1-1.7
		easiervillagertrading: EasierVillagerTrading 1.17.1-fabric0.36.1-1.5.4
		eatinganimationid: Eating Animation 1.2
		elytratrinket: Elytra Trinket 2.0.1-1.17
		emotecraft: Emotecraft 2.0.9
		enderscape: Enderscape 0.1.1
		endless_cake: Endless Cake 1.0.0
		enhancedcelestials: Enhanced Celestials 2.0.5
		entityculling: EntityCulling-Fabric 1.3.3
		expandability: ExpandAbility 4.0.2
		explorerscompass: Explorer's Compass 1.17.1-2.0.2-fabric
		extrarecords-core: Extrarecords Core 2.0.1
		fabric: Fabric API 0.42.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+5847535018
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+5847535018
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
		fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+5847535018
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.3+5847535018
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.2+6d0fac4218
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.5+6d0fac4218
		fabric-models-v0: Fabric Models (v0) 0.3.1+5847535018
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.11+6d0fac4218
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.5+6d0fac4218
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+5847535018
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+5847535018
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+6d0fac4218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+6d0fac4218
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+6d0fac4218
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+6d0fac4218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+5847535018
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+5847535018
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.1+eb76084f18
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.1+6d0fac4218
		fabricloader: Fabric Loader 0.11.7
		ferritecore: FerriteCore 3.0.3
		gammautils: Gamma Utils 1.4.3
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.21
		gravestones: Simple Gravestones 0.5
		graveyard: The Graveyard 2.0
		guild: Guild 0.3.3
		horsestatsvanilla: Horse Stats Vanilla 4.1.8
		iceberg: Iceberg 1.0.23
		inventorysorter: Inventory Sorter 1.8.0-1.17
		invmove: InvMove 1.17-0.1.0
		iris: Iris 1.1.2+build.9
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kambrik: Kambrik 1.1.0
		krypton: Krypton 0.1.4
		kyrptconfig: Kyrpt Config 1.2.1-1.17
		lazydfu: LazyDFU 0.1.2
		lchunkloader: Literally Chunk Loader 2.0.3
		legendarytooltips: Legendary Tooltips 1.1.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.6+1.17.1
		libninepatch: LibNinePatch 1.1.0
		lightestlamp: Lightest Lamps 0.9.6
		litematica: Litematica 0.0.0-dev.20210906.183617
		logical_zoom: Logical Zoom 0.0.11
		lovely_snails: Lovely Snails 1.0.3+1.17
		maelstrom_library: Maelstrom Library 1.2.2-1.17.1
		malilib: MaLiLib 0.10.0-dev.26
		maptooltip: Map Tooltip 1.3.0
		midnightlib: MidnightLib 0.2.6
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 2.0.14
		morebannerfeatures: More Banner Features 1.0.7
		moretotems: More Totems 2.8.0
		multipart_entities: MultipartEntities 1.1.3-1.17.1
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		nears: Nears 1.1.2
		notenoughcrashes: Not Enough Crashes 3.7.1+1.17.1
		omega-config: OmegaConfig 1.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		oxidizelib: OxidizeLib 1.1.0
		paintings: Paintings ++ 1.17.1-1.0.0.3
		pandamc_concreteplus: Concrete plus 1.9
		perorate: Perorate 1.2.0
		perspectivemod: Perspective Mod Redux 0.0.5_01
		phonos: Phonos 0.1.2+1.17
		plushies: Plushie Mod 1.0
		quickshulker: Quick Shulker 1.3.1-1.17
		reinfbarrel: Reinforced Barrels 1.0.3
		reinfchest: Reinforced Chests 1.0.3
		reinfcore: Reinforced Core 1.1.0
		reinfshulker: Reinforced Shulker Boxes 1.1.2
		rocks: This Rocks! 1.5.1
		roughlyenoughitems: Roughly Enough Items 6.1.327
		rupee: Rupees 1.2.0
		shulkerboxtooltip: Shulker Box Tooltip 3.0.3+1.17.1
		shulkerutils: shulkerutils 1.0.4-1.17
		skinnedlanterns: Skinned Lanterns 1.1.5
		skyfymodclient: SkyfyModClient 1.0.0
		smoothboot: Smooth Boot 1.16.5-1.6.0
		sodium: Sodium 0.3.2+build.7
		sodium-extra: Sodium Extra 0.3.5
		somnus: Somnus API 0.0.13-1.17.1
		sound_track: Sound-Track 1.0.4
		spawnermod: Enhanced Mob Spawners 1.1.2
		squirrels: Squirrels 1.2.0-1.17
		starlight: Starlight 1.0.0+fabric.73f6d37
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		strawdummy: Straw Dummy 1.5.0
		team_reborn_energy: Energy 2.0.0-beta1
		teenycoal: Teeny Coal 1.0.3-1.16.x-1.17.x-1.18.x
		things: Things 0.2.6
		third_person_maps: Third Person Maps 1.2.0
		transportables: Transportables 1.0.6
		trinkets: Trinkets 3.0.4
		untitledduckmod: Untitled Duck Mod 0.3.0
		upgradedechests: Upgraded Ender Chests 1.0.3-1.17
		vanilla_degus: Vanilla Degus 1.2.3
		veinmining: Vein Mining 0.0.11-1.17.1
		weaponthrow: Weapon Throw 1.17.1-1.4
		wie: Water Imbued Enchantment & Thunder Imbued Enchantment 1.0.1
		xps: Xp Obelisk 0.2.0_for_1.17.x_Fabric
	Launched Version: fabric-loader-0.11.7-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 496.49, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 32x AMD Ryzen 9 5950X 16-Core Processor 
	Suspected Mods: Fabric Loader (fabricloader)

**Comment by AmibeSkyfy16** [comment] 2021-11-10 14:44
The crash that i have is on the latest version of iris (iris-and-sodium-mc1.17-1.1.2+build.9.jar)

i downloaded the iris-mc1.17-1.1.1.jar and i dont have crash

also, when i download sodium extra, sodium mod has been automatically download because sodium extra include it on dependence and i had to delete sodium manually

**Comment by IMS212** [comment] 2021-11-10 15:02
Your sodium versions seem to be getting replaced with the official ones, which in many cases causes a crash like that. You’ll need to manually delete the sodium jar file from your mods folder.

**Comment by AmibeSkyfy16** [comment] 2021-11-10 15:34
i have now the same error but with adorn mod :(
i disabled adorn = work
i enabled adorn = pipeline error

**Comment by AmibeSkyfy16** [comment] 2021-11-11 05:57
I did an export of my curseforge profile, maybe if you want you can import him and see the error https://drive.google.com/file/d/1nIR1fmpcundc-Di4twBSOPakRDPoyRk4/view?usp=sharing

**Comment by TelepathicGrunt** [comment] 2021-11-17 16:39
Seems to be happening with notify on and iris
https://github.com/JamCoreModding/Notify/issues/5

the fact that random mods can be disabled to stop Iris from crash means this might be some sort of race condition. WHich is a massive pain to debug. oof

**Comment by Jamalam360** [comment] 2021-11-17 19:25
👋 Notify dev here. Is this caused by something I'm doing, or is it 'random'? Just so I can temporarily stop doing whatever I might be doing to stop the crashes?

**Comment by coderbot16** [comment] 2021-11-22 05:19
This seems to have nothing to do with Notify or similar mods, but rather this seems to be yet another incompatibility issue with Not Enough Crashes. NEC lets the game continue initialization after a fatal entrypoint crash, and if Iris wasn't initialized before the entrypoint crash, Iris crashes trying to access state that in a SANE environment should **ALWAYS BE INITIALIZED** by the time LevelRenderer is getting constructed, but NEC breaks that.

I guess it sorta makes sense since it needs to show a custom error screen. Still incredibly annoying.

**Comment by coderbot16** [comment] 2021-11-22 17:51
Just to be clear: If you are debugging an error like this, changing the mods you have loaded will randomly change the mod loading order, meaning that adding / removing unrelated mods can cause or disable the crash.

**Comment by Jamalam360** [comment] 2021-11-29 16:46
Interesting, maybe it would be easier to just add a `breaks` to the fabric.mod.json and not worry about it :yeef:? Most people are going to choose iris over not enough crashes if they have to get rid of one of them anyways....

**Comment by coderbot16** [comment] 2021-12-06 08:20
Should be addressed by https://github.com/IrisShaders/Iris/commit/e7ecc6af2777637c4e34b702085158646346e901

**Closed** 2022-01-06 18:50 UTC
Labels: mod compatibility, crash, status: fixed in next release
