### ISSUE TITLE
F3 + G ( Chunk Borders ) aren't visible when using shaders.

### ISSUE THREAD

**Issue by Xemorr** [IrisShaders/Iris#708] opened 2021-08-04 17:57 UTC
### What happened?

A bug happened! When I use F3 + G, I expect to be able to see chunk borders.

### Screenshots

![image](https://user-images.githubusercontent.com/31805746/128230667-435d2a70-3a4c-4291-a074-1426016f8a9d.png)
I can't see chunk borders ^

![image](https://user-images.githubusercontent.com/31805746/128230709-e6fc1b4e-cdd1-41c5-8be2-6389a01f3cff.png)
I can see chunk borders

### Relevant log output

```shell
N/A
```

### Iris and Minecraft Version

iris-mc1.17-1.1.1.jar

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

GTX 980 Ti

### Java Version

Java 16

**Comment by TehcJS** [comment] 2021-08-04 17:57
This is a known bug with iris.

**Comment by TehcJS** [comment] 2021-08-04 17:58
Duplicate of #513.

**Comment by AlsoNiko** [comment] 2021-08-04 17:59
Thanks Tehc Java script

**Closed by AlsoNiko** 2021-08-04 17:59 UTC
Labels: bug
