### ISSUE TITLE
Add parallax occlusion mapping 

### ISSUE THREAD

**Issue by HeroRyker** [IrisShaders/Iris#724] opened 2021-08-08 00:25 UTC
Please add an option for POM it makes the texture packs so much better.

**Comment by ColdIce1605** [comment] 2021-08-08 03:20
Sorry, but POM is a shader pack feature what your looking for is normal textures and maybe in some weird format a specular texture, also used for PBR in many cases tho isn't strictly needed, (Chronos is a good example or anything the hardcoded IDs)

**Comment by IMS212** [comment] 2021-08-08 03:22
Duplicate of #130.

**Closed by IMS212** 2021-08-08 03:22 UTC
Labels: enhancement
