### ISSUE TITLE
iris breaking text

### ISSUE THREAD

**Issue by potaterboi** [IrisShaders/Iris#1978] opened 2023-05-02 22:13 UTC
everywhere in the game, all text is replaced with this
![image](https://user-images.githubusercontent.com/96933103/235797082-0c06b9c5-14aa-4853-9766-e8d3dc4fca01.png)
![image](https://user-images.githubusercontent.com/96933103/235797259-1f6adea4-6477-49a2-b0d2-900a12141c37.png)

**Comment by jyyyyylim** [comment] 2023-05-03 01:38
^likewise.
version affected is 1.6.1 on my end. issue seems to persist regardless of display language, as of mc1.19.4

**Comment by IMS212** [comment] 2023-05-03 02:40
This is caused by a conflicting mod, the log must be checked to find out what the mod is.

**Comment by MineCreeper86** [comment] 2023-05-03 04:48
> ^likewise. version affected is 1.6.1 on my end. issue seems to persist regardless of display language and mods used, as of mc1.19.4
> 
> 1.6.2 that fixes this had been released

Issue gets solved after upgrading to 1.6.2 thx

**Comment by heymiztli** [comment] 2023-05-14 20:01
I have this problem after updating to 1.6.3, even when I take out others mods and recourses the problem persist

**Comment by IMS212** [comment] 2023-05-20 12:44
Upgrade Iris to 1.6.3 and downgrade Sodium to 0.4.10, this will be fixed in the next release.

**Closed** 2023-05-20 12:44 UTC
