### ISSUE TITLE
Underwater reflection is too strong

### ISSUE THREAD

**Issue by tobiaisu** [IrisShaders/Iris#974] opened 2021-11-14 13:58 UTC
### What happened?

While using BSL shaders, you can see that if you look at the water surface from inside, the reflection is way too strong.
First picture is from Optifine, second from Iris.

### Screenshots

![image](https://user-images.githubusercontent.com/89903758/141684262-addf9d08-81f0-454f-98f4-3c798017a695.png)
![image](https://user-images.githubusercontent.com/89903758/141684275-3bcc27c3-18fb-4d93-9123-2db5a3568e48.png)

### Iris and Minecraft Version

iris-mc1.17.1-1.1.2.jar for Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 11 Home

### What is your GPU?

Nvidia GeForce GTX 1650 Ti

### Java Version

Minecraft running on Java 16 + Iris installed with Java 8

**Comment by IMS212** [comment] 2021-11-14 14:57
Duplicate of #961

**Closed by IMS212** 2021-11-14 14:57 UTC
Labels: bug
