### ISSUE TITLE
Sildurs Vibrant extreme Volumetric Light

### ISSUE THREAD

**Issue by KpauMupa** [IrisShaders/Iris#73] opened 2021-01-04 19:18 UTC
That's how this shaderpack looks with OptiFine:
![2021-01-04_22 15 52](https://user-images.githubusercontent.com/76217453/103570715-aa2f5d80-4eda-11eb-8b74-46b69fde6011.png)
And that's how it looks with Iris mod rn (Iris-trunk runclient):
![2021-01-04_22 13 05](https://user-images.githubusercontent.com/76217453/103570781-c3380e80-4eda-11eb-9494-0b465c7d77bf.png)

**Comment by supsm** [comment] 2021-01-04 19:27
Iris isn't fully developed yet, some features won't work. Volumetric light hasn't been implemented yet nor have shadows been. They well probably work in the future.

**Comment by KpauMupa** [comment] 2021-01-04 19:33
> 
> 
> Iris isn't fully developed yet, some features won't work. Volumetric light hasn't been implemented yet nor have shadows been. They well probably work in the future.

Ok. Should i close this issue or leave it as a reminder for the creator?

**Comment by coderbot16** [comment] 2021-01-04 19:35
No need to close it, it's still an issue

**Comment by KpauMupa** [comment] 2021-01-04 19:37
> 
> 
> No need to close it, it's still an issue

Ok. As a developer of this mod, сan You tell the approximate release date of it?

**Comment by coderbot16** [comment] 2021-01-04 19:38
I can't provide any ETAs because it's not clear how long things will take or how much time I will have to develop the mod.

**Comment by KpauMupa** [comment] 2021-01-04 19:42
> 
> 
> I can't provide any ETAs because it's not clear how long things will take or how much time I will have to develop the mod.

Thanks for the answer. You already did a great job and every user of Sodium appreciates it!

**Comment by coderbot16** [comment] 2021-01-06 00:45
Thanks! 🙂

A lot of development happened over the holiday break, but unfortunately I'll likely be pretty busy with other things in the near future. As a result, I can't provide any guarantees on development.

**Comment by UltraBlackLinux** [comment] 2021-01-07 11:21
This actually looks cool. Like super secret settings retro ;)

**Comment by coderbot16** [comment] 2021-03-06 08:04
Hey! It's been a while, could you re-test on the latest Iris version and make sure that this issue still happens? Thanks!

**Comment by coderbot16** [comment] 2021-03-23 20:39
Closing this since the dithery effect is likely fixed, and because the remaining discrepancies are caused by the lack of shadow mapping, which is being tracked in #84.

**Closed by coderbot16** 2021-03-23 20:39 UTC
Labels: more information needed
