### ISSUE TITLE
Hard crash on 1.16.5

### ISSUE THREAD

**Issue by Kashouryo** [IrisShaders/Iris#101] opened 2021-02-07 04:36 UTC
I am currently using Sildur's Vibrant Shaders v1.283 High-MB shader pack.
The game hard crashes upon entering the main menu.
One error message that I found interesting was:
` - Conflicting versions found for fabric-api-base: used 0.2.0+ab87788d3a, also found 0.2.0+daa38b3d7d`
After I removing the `fabric-api-0.30.0+1.16.jar` the shader does works and looks great!
However, without `fabric-api-0.30.0+1.16.jar` most of the mods simply won't load.
I did not found anything else interesting in the log file. However, if you need the log please tell me.

**Comment by IMS212** [comment] 2021-02-07 04:37
That message isn’t important, it’s just a warning. Can you get the crash log?

**Comment by Kashouryo** [comment] 2021-02-07 04:39
https://0bin.net/paste/RumXk2RI#u7ZiyP8GDoc6gN3nTGx8IB0h3+KTzsixAGBAKFEg3w-

**Comment by IMS212** [comment] 2021-02-07 04:42
Interesting, do you have a separate crash log in the crash-reports folder?

**Comment by Kashouryo** [comment] 2021-02-07 04:44
Yes, I do have one [hs_err_pid3828.log](https://github.com/IrisShaders/Iris/files/5938282/hs_err_pid3828.log)
Also, my version is 305ddec if that helps

**Comment by Tiebe** [comment] 2021-02-18 13:04
Same issue here. Game crashes as soon as it's done loading.

**Comment by coderbot16** [comment] 2021-03-01 20:27
This appears to be a duplicate of #77, the root problem will be resolved soon.

**Closed by coderbot16** 2021-03-01 20:27 UTC
