### ISSUE TITLE
All the entities are white/invisible

### ISSUE THREAD

**Issue by Baphomeem** [IrisShaders/Iris#1716] opened 2022-10-28 04:55 UTC
### What happened?

Whenever i use a shader, all the entities become white/invisible, including me. It happens with all the shaders.

### Screenshots

![2022-10-27_23 47 31](https://user-images.githubusercontent.com/116759900/198505569-6ab70479-5193-4747-a6a9-972f38865c8b.png)

![2022-10-27_23 47 58](https://user-images.githubusercontent.com/116759900/198505627-ac8289b0-4109-4cc4-9f22-28c2c5fe37fd.png)

### Minecraft Version

1.19.2

### Iris Version

1.4.0 

### Operating System

Windows 10 

### What is your GPU?

Intel HD graphics 4000

**Comment by toomuchcodehelp** [comment] 2022-10-29 01:10
intel's drivers have always been annoying with shaders, try with optifine too to make sure though.

**Comment by coderbot16** [comment] 2022-10-30 22:39
Assuming this is a duplicate of https://github.com/IrisShaders/Iris/issues/1412 because no log files were attached

**Closed by coderbot16** 2022-10-30 22:39 UTC
Labels: bug, more information needed

**Comment by Baphomeem** [comment] 2022-10-31 04:50
I tried with Optifine and i had no issue
