### ISSUE TITLE
Entities Randomly Becomes Invisible

### ISSUE THREAD

**Issue by StartsMercury** [IrisShaders/Iris#1240] opened 2022-01-23 08:40 UTC
### What happened?

 - Applying config changes to shader
 - Or just randomly

### Minecraft Version

Minecraft 1.18.1

### Iris Version

iris-mc1.18.1-1.2.0-pre

### Sodium Version

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14 and/or sodium-fabric-mc1.18.1-0.4.0-alpha6+replaymod.rev.b90e7f3

### Operating System

Windows 10

### What is your GPU?

AMD Radeon HD 8500M

### Java Version

GraalVM EE 17-21.3.0

### Additional context

[2022-01-23-1.log.gz](https://github.com/IrisShaders/Iris/files/7920073/2022-01-23-1.log.gz)

 - Issue randomly and shortly fixes itself
 - Game relaunch temporarily fixes the issue
 - Particles from entities work normally
 - Some shaders can still create shadows
 - Even the player in f5 is invisible

**Comment by coderbot16** [comment] 2022-01-23 09:03
Can you upload a normal log file? Viewing .log.gz files is difficult.

**Comment by StartsMercury** [comment] 2022-01-23 09:05
[2022-01-23-1.log](https://github.com/IrisShaders/Iris/files/7920123/2022-01-23-1.log)

**Comment by coderbot16** [comment] 2022-01-25 20:16
You have a ton of other mods installed - try with only Iris and Sodium, and if it does not happen then, remove mods until you get to the smallest number of mods needed to reproduce the issue.

**Comment by StartsMercury** [comment] 2022-01-25 22:58
I actually only tried without iris (and yes, no issue), but I would later try with just iris (then potentially with others).

**Comment by StartsMercury** [comment] 2022-01-26 09:50
[latest.log](https://github.com/IrisShaders/Iris/files/7940608/latest.log)

**Comment by coderbot16** [comment] 2022-02-03 06:17
Nothing in the logs is obviously wrong. Without reliable reproduction steps, there's not much we can feasibly do.

**Comment by StartsMercury** [comment] 2022-02-05 00:23
I'll just hope It's fixed on the next release.

**Comment by coderbot16** [comment] 2022-03-06 21:21
Please test with the latest release, using a standard build of AdoptOpenJDK (not GraalVM). Also, does this happen with shaders disabled?

**Comment by StartsMercury** [comment] 2022-03-12 13:40
Occurs when shaders were enabled at least once, the bug doesn't occur instantly.

The bug did occur with just iris and essential dependencies, but just recently the bug occurred and only happened once yet in a single-player world. I obviously have different mods installed from before.

**Comment by coderbot16** [comment] 2022-04-30 18:04
Closing, since without consistent reproduction steps or anyone else being able to replicate this issue, it's unlikely that I can do anything about it.

**Closed by coderbot16** 2022-04-30 18:04 UTC
Labels: bug, more information needed
