### ISSUE TITLE
Performance regression on 1.17

### ISSUE THREAD

**Issue by SecretlyJealous** [IrisShaders/Iris#460] opened 2021-06-30 12:41 UTC
### What happened?

When using iris + sodium on 1.16.5 I get decent fps and no stuttering however when I updated to iris + sodium 1.17 I noticed a big performance hit for some reason (fps has been halved). I've taken a video of iris + sodium 1.16.5 and iris + sodium 1.17 so that it is easy to compare the performance drop.

I'm not using any mods besides iris and sodium, I used the Iris-Installer-1.0.2 for both 1.16.5 and 1.17.
**Note:** If the videos are too small just click on the quality icon and change it from sd to hd:
![Untitled](https://user-images.githubusercontent.com/10485646/123960612-690a9880-d9a7-11eb-8cde-c1d51369bd79.png)

iris + sodium on 1.16.5 video:
**Video:** https://gfycat.com/unknownmassiveaquaticleech
1.16.5 logs: https://pastebin.com/cZXajPsb

iris + sodium on 1.17 video:
**Video:** https://gfycat.com/celebratedelementarydairycow
1.17 logs: https://pastebin.com/qnmUFApg

### Iris and Minecraft Version

iris-mc1.17-1.1.0+rev.f06a69d

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

RTX 2070

### Java Version

Java 16

**Comment by pajicadvance** [comment] 2021-06-30 13:15
Duplicate of #453 , the regression was introduced by Sodium, we are aware of the issue.

**Closed** 2021-06-30 13:28 UTC
Labels: bug, duplicate
