### ISSUE TITLE
Sues Ptgi shaders won't show (Only vanilla textures)(The Twitter post stated "SEUS PTGI HRR is now mostly working with development branches of Iris!")

### ISSUE THREAD

**Issue by whenthedoodoo** [IrisShaders/Iris#1320] opened 2022-03-13 20:22 UTC

**Comment by IMS212** [comment] 2022-03-13 20:23
Please send a log file.

**Comment by IMS212** [comment] 2022-03-13 20:23
And please use our issue reporting next time.

**Comment by coderbot16** [comment] 2022-03-13 21:56
Assuming this to be a duplicate of https://github.com/IrisShaders/Iris/issues/1071 since the issue report has none of the required information.

**Closed by coderbot16** 2022-03-13 21:56 UTC
Labels: bug
