### ISSUE TITLE
Dirty Lens not working

### ISSUE THREAD

**Issue by tobiaisu** [IrisShaders/Iris#972] opened 2021-11-14 13:15 UTC
### What happened?
When changing options on BSL shaders, the Dirty Lens option is not working at all. I tried opening the shader with Optifine and it worked. The file used for settings is located in lib with name settings.glsl so problem is not there.

### Screenshots Optifine
![image](https://user-images.githubusercontent.com/89903758/141682703-568b86ee-253f-4bb8-a8bb-54848a1ed6f9.png)

### Screenshots Iris
![image](https://user-images.githubusercontent.com/89903758/141682695-45c10add-bc81-4b58-8ebd-e92138a24ffe.png)

### Relevant log output
No response

### Iris and Minecraft Version
iris-mc1.17.1-1.1.2.jar for Minecraft 1.17.1

### Are you running Sodium along with Iris?
Yes

### Operating System
Windows 11 Home

### What is your GPU?
Nvidia GeForce GTX 1650 Ti

### Java Version
Minecraft running on Java 16 + Iris installed with Java 8

**Comment by IMS212** [comment] 2021-11-14 14:59
Duplicate of #853

**Closed by IMS212** 2021-11-14 14:59 UTC
