### ISSUE TITLE
Crashes when loading into world

### ISSUE THREAD

**Issue by sm8925** [IrisShaders/Iris#2530] opened 2024-11-17 00:13 UTC
### Minecraft Version

1.21

### Iris Version

iris 1.8 Beta 7 for Fabric 1.21.1

### Sodium Version

sodium-fabric-0.6.0-beta.4+mc1.21.1

### Operating System

Garuda Linux

### What is your GPU?

4070 ti

### Java Version

Java 21.0.5

### Reproduction Steps

1. Load into a world
2. Black screen (except for hotbar and chat) for a few seconds
3. crash
[crash-2024-11-16_19.06.07-client.txt](https://github.com/user-attachments/files/17788301/crash-2024-11-16_19.06.07-client.txt)
[latest.log](https://github.com/user-attachments/files/17788303/latest.log)
https://mclo.gs/tSqBX2e (crash report in case I didn't attach the files correct)
https://mclo.gs/ovKZwjX (latest log in case the file isn't attached correctly)

### Crash Report file and latest.log

```shell

```

### Additional context

I think this might be the fault of another mod conflicting with iris because I've been using iris for weeks without this issue until today.

**Comment by kands-code** [comment] 2024-11-17 03:21
I encountered a similar situation, but my Sodium version is 0.6.0-release. Initially, I thought it was a problem with Sodium, but the Sodium team [said](https://github.com/CaffeineMC/sodium/issues/2880#issuecomment-2480905777) it was an issue with Iris in 1.21.1 that caused the crash. Here is my log file:

[crash-2024-11-17_11.02.23-client.txt](https://github.com/user-attachments/files/17788747/crash-2024-11-17_11.02.23-client.txt)

[2024-11-17-4.log](https://github.com/user-attachments/files/17788750/2024-11-17-4.log)

**Comment by IMS212** [comment] 2024-11-17 05:22
Caused by MoreMCMeta. (The Sodium 0.6 release crash is unrelated and will be fixed in the next update.)

**Closed as not planned by IMS212** 2024-11-17 05:22 UTC
