### ISSUE TITLE
Sodium Extra makes the program stack go out of sync

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#132] opened 2021-02-26 17:25 UTC
https://github.com/FlashyReese/sodium-extra-fabric/blob/66e05eaa5a2c8f9fea20f34a677ba6223769b9ef/src/main/java/me/flashyreese/mods/sodiumextra/mixin/features/particle/MixinWorldRenderer.java#L29

This seems to be a concerning problem, where mods cancel various bits of world rendering without letting Iris know. I'll need to figure out a way to avoid getting into a state where the program push happens before a mod cancels the callback.

**Comment by thedocruby** [comment] 2021-03-03 18:07
Comparing the MixinWorldRenderer for Iris vs SodiumExtras, it seems that SE injects the callback cancel at the _invoke_ of the renderWeather function, while iris injects the program push at the _head_ of the renderWeather function. That way, the callback cancel will cause an immediate return, before iris gets a chance to push the program. Right? Forgive me if I am missing something obvious, I am still getting used to working with Mixin, and I may unconsciously ignore important parts of the code if I don't understand what might make them important.

However, I will say that all of my testing with the Sodium-compatibility branch has been done with SodiumExtras installed, and i haven't noticed any trouble with weather rendering besides what has already been mentioned and patched by @IMS212 . Of course, there is still the possibility that I am getting my issues confused, and the persistent precipitation artifacts are rooted in another cause, such as SE. Also, I haven't tried turning off weather or particles in Sodium config, and looking at the code, it seems that these callback cancels would only become an issue when I do so. Because of this, I will spend a few minutes when I get home to mess around in the SE config menu with iris installed, to see if I can coax the issue to surface.

**Comment by coderbot16** [comment] 2021-03-03 19:09
Essentially what those injection points mean is that whenever renderWeather calls a function, sodium extra checks if weather is disabled and if so cancels the function.

Notably, all of these are *after* the HEAD of the function, so Iris pushes a program before the function is cancelled.

Essentially, this is an oversight in Iris, meaning that I'll need to inject around the calls to renderWeather within render() instead of at the head and return of renderWeather.

**Comment by thedocruby** [comment] 2021-03-03 20:20
So correct me if i'm wrong, but you're saying that sodium extra's check, which is injected at the renderWeather `INVOKE`, is somehow executing before Iris's program push, which is injected at renderWeather `HEAD`?

**Comment by coderbot16** [comment] 2021-03-03 20:26
No, that's the exact opposite of what I'm saying. The problem is that the INVOKE (where Sodium Extra injects) happens *after* HEAD (where Iris injects). As a result, Iris never pops the program, causing the stack to get messed up.

The fix would involve injecting in such a way that the push and pop happen whether or not weather rendering is cancelled.

**Comment by thedocruby** [comment] 2021-03-03 20:48
I'm confused. I thought INVOKE was always _before_ HEAD, since INVOKE is in the code wherever the function is _called_, and interrupts execution there, whereas HEAD is actually _inside_ the function, requiring a successful call to ever be executed. Am I missing something?

**Comment by coderbot16** [comment] 2021-03-03 20:53
INVOKE is actually referring to every function call within `renderWeather`, which is completely different from what you're describing. It's quite a peculiar injection point for Sodium Extra to use for what it's doing (generally, you use it to target a *specific* function call), but we'll roll with it for now.

Here's an example of what's going on (simplified for illustration):

```
void renderWeather() {
    // Iris injects a pushProgram call here
    int i = 32 + 3;
    // Sodium Extra injects its check and cancellation logic here
    RenderSystem.setupStuff();
    // and here...
    RenderSystem.setupOtherStuff();
    
    // (rest of the weather rendering logic...)
    
    // and here...
    RenderSystem.teardownStuff();
    // and here...
    RenderSystem.teardownOtherStuff();

    // Iris injects a popProgram call here
}
```

**Comment by thedocruby** [comment] 2021-03-04 00:09
Ohhhh. That makes more sense. So, what if you were to set up an inject at HEAD with a dupe of the renderWeather function not including anything from other mods but including the code from pushProgram and popProgram in the appropriate places, and then just cancel the injection to force the real renderWeather function to return prematurely. Would that solve the issue? I know that it would have the effect of completely bypassing SodiumExtras' disabling function, but maybe we could work with them a little bit because I agree when you say that their solution is "peculiar".

Also, If you think that the patch I've described would be worth implementing, I know you've been busy recently, so I'd be happy to type it up myself if you can point me in the direction of the renderWeather source.

**Comment by coderbot16** [comment] 2021-03-04 00:14
That would probably cause a lot of problems honestly: it would avoid the crashes, but not solve the root issue. I commented that the injection point was peculiar, but even if they used HEAD it's possible that their HEAD inject could happen after Iris's HEAD inject. My plan is to stop injecting at head / return of functions like renderWeather and instead inject "around" the functions in WorldRenderer#render, like so:

```
void render() {
    // ... stuff

    // inject a pushProgram
    renderWeather();
    // inject a popProgram

    // stuff ...
}
```

The only real way for that to explode is if someone cancels WorldRenderer#render in the middle, which will cause a lot more problems, and is unlikely to be something that *any* reasonable mod does.

**Comment by thedocruby** [comment] 2021-03-04 00:27
Oh that makes more sense. Much more elegant solution. So you'd do an `INVOKE` inject with `method="render"` and `target="renderWeather"` to inject the pushProgram... Right? Then maybe `INVOKE_ASSIGN` for popProgram? I apologize in advance if I am way off, I'm still very new to mixin, and I am trying to learn as much as I can about it so I can efficiently help out with Iris development down the road.

**Closed** 2021-03-05 23:01 UTC
