### ISSUE TITLE
Replay Mod Warning Screen Glich

### ISSUE THREAD

**Issue by OrangeGlowest** [IrisShaders/Iris#1819] opened 2023-01-01 22:47 UTC
I could open replay viewer and hit cancel and bypass the warning screen, loaded into game and it crashed instant

**Comment by coderbot16** [comment] 2023-01-05 01:52
Caused by https://github.com/ReplayMod/ReplayMod/issues/621, this will need to be fixed by Replay Mod.

**Closed by coderbot16** 2023-01-05 01:52 UTC
