### ISSUE TITLE
When you go to a world other than "world" all shaders are disabled and only the default shader works.

### ISSUE THREAD

**Issue by mifjpn** [IrisShaders/Iris#2091] opened 2023-08-12 07:10 UTC
### What happened?

Using the Multivirse portal to navigate to a world other than the default world 'World' will disable all shaders, including the latest Kappa Shader V5.2, and only the default shader will work.
CPU:i9-10900f
RAM:32GB
GPU:RX6600Xt
Normal World

### Screenshots

proper-world
![259746172-a3438b5f-1899-4fbe-ac44-ccc64c3e1c2e](https://github.com/IrisShaders/Iris/assets/7693274/2962fe82-ad13-4d5e-a361-72e007bfcb1a)

bad-world
![259746326-2d2c0912-a038-4e8e-8d0e-f234314269e5](https://github.com/IrisShaders/Iris/assets/7693274/39efbbb8-6aac-4fa9-850c-d1d6fbc6fe84)

### Log output

[log.txt](https://github.com/IrisShaders/Iris/files/12326802/log.txt)

### Minecraft Version

Minecraft 1.20.1

### Iris Version

iris-mc1.20.1-1.6.5.jar

### Operating System

Windows11

### What is your GPU?

AMD RX 6600 xt

**Comment by Lolothepro** [comment] 2023-08-13 20:00
duplicate of #2083

**Closed** 2023-08-13 20:05 UTC
Labels: bug
