### ISSUE TITLE
Optifine Shader Options in Shader Menu

### ISSUE THREAD

**Issue by samozoid** [IrisShaders/Iris#1129] opened 2021-12-24 21:04 UTC
Hi,

I've been using this mod for awhile now and I've noticed the lack of the normal Optifine shader which really irritates me due to this mod being compatible with normal Optifine shaders and the lack of Shader Options either makes it difficult or impossible to modify the settings of shaders.

I would find some way of implementing it as either a work around or something similar to how normal Optifine reads and writes to the shader options.

**Comment by maximumpower55** [comment] 2021-12-24 21:05
Duplicate of #663

**Closed** 2021-12-24 21:05 UTC
