### ISSUE TITLE
Faulty chest rendering - Sildurs Vibrant

### ISSUE THREAD

**Issue by thedocruby** [IrisShaders/Iris#87] opened 2021-01-21 17:13 UTC
Using Iris with Sildurs Vibrant, (High, no Sodium) Chests seem to render incorrectly. this may be able to be expanded to other blocks, but I will leave that to you. As you can see below, the blue 'fog' that is present underwater does not affect the chests:
![2021-01-21_10 59 53](https://user-images.githubusercontent.com/76263371/105385687-9de91700-5be1-11eb-900e-6b502dfbc6db.png)
Even on land, the chest lighting seems to be out of tune with it's surroundings:
![2021-01-21_12 04 41](https://user-images.githubusercontent.com/76263371/105385713-a6415200-5be1-11eb-9baa-fe6890373f80.png)

**Comment by thedocruby** [comment] 2021-03-03 20:03
Upon later review, I realized that this is quite possibly related to some combination of #146 , #133 , #84 , and #19 .

**Comment by coderbot16** [comment] 2021-03-03 20:48
I *would* like to keep this open until I can verify that it is fixed for sure, because it is always possible that it's a separate issue - though it's likely that the issues in the first screenshot are related to #133. However, it's worth re-checking the second screenshot with the current Iris version, since I remember resolving a related issue there.

**Comment by coderbot16** [comment] 2021-05-23 18:09
Confirmed that any remaining issues are due to #84.

**Closed by coderbot16** 2021-05-23 18:09 UTC
Labels: bug
