### ISSUE TITLE
End Portal Animation Glitching Out, possibly a weird mod conflict?

### ISSUE THREAD

**Issue by githubbingitup** [IrisShaders/Iris#431] opened 2021-06-26 17:30 UTC
Minecraft 1.16.5
iris-mc1.16.5-1.0.2f + sodium-fabric-mc1.16.5-0.2.0+IRIS2-rev.31828aa
fabric-api-0.36.0+1.16

The visual animation bugs out as well as the skybox inside of The End. Looks like this on the right:
https://i.imgur.com/Z84Map1.png

This issue is weird because it doesn't seem to be from one specific mod, but a combination of several.
I spent a lot of time testing this and trying to find a cause, but I couldn't find a source.
It seems to just happen after adding enough mods and after getting an unlucky game reboot. It might not even be mod-related.

Sometimes I boot up and it happens. Sometimes it doesn't.
Easiest way to replicate this is just by dumping a ton of mods into your folder and keep launching the game until it happens.

I've attached a log of two different sessions running the exact same mod setups with no changes to any options.
In the first session, the bug didn't happen.
In the second session, the bug happens.

[two logs.zip](https://github.com/IrisShaders/Iris/files/6720445/two.logs.zip)

**Comment by IMS212** [comment] 2021-06-26 17:31
Duplicate of #361, likely due to #347 not being implemented yet.

**Comment by githubbingitup** [comment] 2021-06-26 17:31
Gotcha, thanks!

**Closed by IMS212** 2021-06-26 17:31 UTC
Labels: bug
