### ISSUE TITLE
Entities become invisible randomly when using GraalVM

### ISSUE THREAD

**Issue by SusStew** [IrisShaders/Iris#1556] opened 2022-07-23 23:55 UTC
### What happened?

When using GraalVM on Minecraft 1.19, entities become invisible after a seemingly random amount of time. Using Adoptium's Java 17 works fine, and using GraalVM on 1.18 also works.

### Log output

https://mclo.gs/FBmaQrT

### Minecraft Version

Minecraft 1.19

### Iris Version

iris-mc1.19-1.2.5.jar

### Operating System

Linux Mint 20.3 Cinnamon (using Kernel 5.15.0-41-generic)

### What is your GPU?

Nvidia GeForce GTX 980

**Comment by coderbot16** [comment] 2022-07-24 00:09
This is an issue we've seen before but could not guarantee to be caused by GraalVM, so thanks for testing and confirming that it is. Unfortunately, I doubt that there's much that can be done in Iris since it's likely that GraalVM is miscompiling our code.

I'll add an entry in the Iris documentation to not use GraalVM but it's likely that this should be reported to GraalVM instead (though, I'm not sure if they can easily debug it themselves with the massive layers of complexity involved in Minecraft's rendering). Once I've added the documentation I'll close this issue with a link to the documentation.

I wonder if it's worth adding a warning message in the log as well, though I don't think GraalVM is used commonly enough to justify that?

**Closed** 2022-07-24 16:25 UTC
Labels: documentation
