### ISSUE TITLE
Water doesn't render on Sildurs Vibrant Shaders v1.281 with AMD drivers

### ISSUE THREAD

**Issue by KpauMupa** [IrisShaders/Iris#71] opened 2021-01-04 16:02 UTC
I can't see the water!!! It's transparent!
![2021-01-04_19 00 08](https://user-images.githubusercontent.com/76217453/103554015-5400f100-4ebf-11eb-964b-2b0a65fcb4e9.png)
![2021-01-04_19 00 19](https://user-images.githubusercontent.com/76217453/103554022-55cab480-4ebf-11eb-8d0f-4852137d37f5.png)

**Comment by KpauMupa** [comment] 2021-01-04 16:03
This is an iris-trunk run version, no other mods are loaded.

**Comment by supsm** [comment] 2021-01-04 16:37
Water seems to be broken with fabulous settings. If you turn it off does it resolve the issue?

**Comment by KpauMupa** [comment] 2021-01-04 17:11
> 
> 
> Water seems to be broken with fabulous settings. If you turn it off does it resolve the issue?

No, that's "fancy" graphics. Same issue with "fast".

**Comment by coderbot16** [comment] 2021-01-04 17:12
Please send a screenshot with F3 open and the water not rendering like that with the latest trunk version

**Comment by KpauMupa** [comment] 2021-01-04 17:19
> 
> 
> Please send a screenshot with F3 open and the water not rendering like that with the latest trunk version

![2021-01-04_20 18 40](https://user-images.githubusercontent.com/76217453/103561185-21a8c100-4eca-11eb-9991-2e13f9cf46ca.png)

**Comment by KpauMupa** [comment] 2021-01-04 17:21
> 
> 
> Please send a screenshot with F3 open and the water not rendering like that with the latest trunk version

Tried all versions of Sildurs Vibrant (lite, medium, high, extreme, extreme-VL) and water is the same.

**Comment by KpauMupa** [comment] 2021-01-04 17:26
> 
> 
> Please send a screenshot with F3 open and the water not rendering like that with the latest trunk version



> 
> 
> Water seems to be broken with fabulous settings. If you turn it off does it resolve the issue?

On your pc the water is working fine with those shaders? o_0

**Comment by IMS212** [comment] 2021-01-04 18:52
does not happen for me unless I turn on fabulous, this may be amd only?

**Comment by KpauMupa** [comment] 2021-01-05 12:44
> 
> 
> does not happen for me unless I turn on fabulous, this may be amd only?

Oh... Maybe actually.

**Comment by WittyWhiscash** [comment] 2021-01-06 03:36
Can confirm this issue occurs on an AMD integrated GPU, but NOT on an Nvidia dedicated one. Latest trunk according to the fetch from IntelliJ. SHA1 of the final jar I tested is 4D4EF356217DAB81E74685D52ABD33EB4DF38B26

Screenshots below:

![2021-01-05_20 31 32](https://user-images.githubusercontent.com/21300678/103726140-69484f00-4f95-11eb-87a5-ff82cf8d0a52.png)
![2021-01-05_20 33 13](https://user-images.githubusercontent.com/21300678/103726144-6baaa900-4f95-11eb-9496-27a61d64621e.png)

**Comment by coderbot16** [comment] 2021-01-07 05:25
Could you test whether this happens on https://github.com/IrisShaders/Iris/commit/14bde1d64c82d440d9448ce0d3f841b6e59f67a8? This could possibly be a regression due to the tests with water reflections in more recent commits.

**Comment by WittyWhiscash** [comment] 2021-01-07 16:49
I can confirm that water does render on commit `14bde1d`. Regression is very likely.

![2021-01-07_09 47 01](https://user-images.githubusercontent.com/21300678/103919522-59cc2180-50cd-11eb-88da-2ab8d5983363.png)

**Comment by coderbot16** [comment] 2021-01-07 17:12
In that case, I know exactly what this is. Will have a fix out in a few days.

**Comment by Viruzaum** [comment] 2021-01-19 12:43
I have this same problem but I have an Intel iGPU
![2021-01-19_09 39 30](https://user-images.githubusercontent.com/23330390/105035939-8885b880-5a3a-11eb-9cd3-8285a2ac743e.png)
My logs were also being spammed with this, not sure if it's related
![image](https://user-images.githubusercontent.com/23330390/105036066-b965ed80-5a3a-11eb-80bd-b4804e5d0004.png)

**Comment by coderbot16** [comment] 2021-01-19 16:18
That seems related but I would need the log file to investigate more closely, preferably one that isn't too large

**Comment by Viruzaum** [comment] 2021-01-19 19:40
Log: https://paste.ee/p/mmGqr

**Comment by Motschen** [comment] 2021-01-24 09:55
Also happens with my Vega 64, should this be fixed I would switch from canvas to iris for all my instances.
I tested it with the render-layer-experiments branch, and it still doesn't work 
(in fact, there are even more issues, but I guess it's very WIP, so that can be expected)
Should you need help with trying to fix this issue, feel free to contact me when I'm online on discord :)

**Comment by coderbot16** [comment] 2021-01-24 17:04
Could you send a log as well? I'm wondering if the spam of GL_INVALUD_OPERATION is consistent.

Also, if there's not a ton of spam of that, maybe try commenting out waterRefl / metallicRefl / polishedRefl in shaders.settings.

Finally, if you're encountering issues with the render-layer-experiments branch that don't exist on trunk, please report them, because otherwise I won't be able to fix them.

**Comment by coderbot16** [comment] 2021-01-24 17:24
Also, please note that the experimental branch only works properly with Sildur's Vibrant 1.283, not 1.281, so make sure to upgrade when testing with it.

**Comment by Motschen** [comment] 2021-01-24 22:32
So, apparently the issues I was having were because of the old shader version.
But still, the water doesn't render, my log doesn't show any errors related to iris when in-game.
I tried to comment out these variables, but it didn't help.

**Comment by coderbot16** [comment] 2021-01-25 01:19
Mithos23 on Discord discovered that removing this line causes water to begin to render again:

https://github.com/IrisShaders/Iris/commit/18ca0e633a688858b4b6a1dfa639e1d38c0cbdf8#diff-5ad2095349647fb38cabec1360381b76af725f575e30540aedeccc8a3786c329R43

Seems like something could be wrong with the way that the noise texture is being setup?

This doesn't happen with Sodium however.

**Comment by coderbot16** [comment] 2021-03-05 03:51
This should be fixed in the latest commits, please tell me if the issues still occur with them.

**Comment by Mithos23** [comment] 2021-03-05 12:35
this still happens on latest commit
![2021-03-05_13 23 03](https://user-images.githubusercontent.com/54249738/110116194-70ce7d80-7db7-11eb-8ef4-1a8699176a01.png)

**Comment by coderbot16** [comment] 2021-03-07 18:48
This should be fixed on the latest trunk in https://github.com/IrisShaders/Iris/commit/a0a85424fd9747a75c8c286e50096ac2ef24a7cd.

**Closed by coderbot16** 2021-03-07 18:48 UTC
Labels: bug
