### ISSUE TITLE
Crash while loading with a large number of mods

### ISSUE THREAD

**Issue by ruvaldak** [IrisShaders/Iris#619] opened 2021-07-23 21:51 UTC
### Iris and Minecraft Version

All recent versions of Iris+Iris Sodium including:
Iris & Sodium @ latest 1.17 commit, 
Starline 1.17 Sodium+Iris, 
IMS212 merg9999 & Damage flashing branches

Minecraft @ 1.17

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10, Arch Linux

### What is your GPU?

RTX 2080ti

### Java Version

GraalVM 16, GraalVM-ee 16, OpenJDK16

### Reproduction Steps

 * Use Iris+Sodium on 1.17.1
 * install a large number of mods (in my case, something above ~115 jar files)
 * Attempt to boot minecraft
 * Crash

### Crash Report file and latest.log

[latest.log](https://github.com/IrisShaders/Iris/files/6871370/latest.log)

### Additional context

This does not happen on CaffeineMC/Sodium 0.3.0.
The number of mods and what can cause crashing when reaching the limit isn't very consistent in my testing, so I have next to no information regarding what is going on here.

Crashes only when running Iris alongside Iris-Shaders/sodium-fabric. When using Iris standalone, MC boots fine. Once again, this is exclusive to Iris-Shaders/sodium-fabric, and isn't present on CaffeineMC/Sodium 0.3.0 release.

**Comment by AlsoNiko** [comment] 2021-07-23 21:52
Known reported bug, a fix is actively being worked on

**Comment by DestinyTheGreat** [comment] 2021-07-23 22:27
It seems that removing the Sodium fork (and using Iris standalone) does not crash.

**Comment by ruvaldak** [comment] 2021-07-23 22:40
Still crashes when not using Not Enough Crashes

Does not crash on the latest CaffeineMC/Sodium-fabric compiled from source as of 7/23/2021, 6:40PM EST

**Comment by ruvaldak** [comment] 2021-07-23 22:43
[latest.log](https://github.com/IrisShaders/Iris/files/6871486/latest.log)

Crash with mixintrace.

**Comment by IMS212** [comment] 2021-07-23 23:03
This is caused by the Shader mixin from Sodium somehow applying after Iris's, when Mixin should be skipping due to a redirect conflict. The exact cause is unknown, but removing the Shader mixin or otherwise disabling it from the Sodium fork will fix this.

**Comment by ruvaldak** [comment] 2021-07-24 22:44
> This is caused by the Shader mixin from Sodium somehow applying after Iris's, when Mixin should be skipping due to a redirect conflict. The exact cause is unknown, but removing the Shader mixin or otherwise disabling it from the Sodium fork will fix this.

A fix for an issue that we don't know why needs fixing in the first place isn't much of a fix. For all we know, the fix may be more of a bandaid than a permanent fix for the issue. Time will tell though, and something is better than nothing. We suspect it might be a bigger issue on fabric 1.17.1, maybe a mixin overflow, infinite loops cause by some kind of overflow somewhere, not sure. As it stands, any logs covering this issue are extremely inconsistent and don't make much sense. Might be worth bringing this issue to the attention of fabric devs.

**Comment by coderbot16** [comment] 2021-09-26 00:25
This was fixed by https://github.com/IrisShaders/sodium-fabric/pull/25, which shipped in Iris 1.1.2.

**Closed by coderbot16** 2021-09-26 00:25 UTC
