### ISSUE TITLE
FSR 1 / 2 Toggle

### ISSUE THREAD

**Issue by SapryWenInera** [IrisShaders/Iris#1733] opened 2022-11-13 22:50 UTC
**Is your feature request related to a problem? Please describe.**
Shaders are pretty heavy on gpu.

**Describe the solution you'd like**
Creating a toggle for fsr 2 or at least 1 would free some gpu resources for shaders

**Describe alternatives you've considered**
Resoluution Scalers could do the same buut with higher quality hits.
**Additional context**
This would allow more people to use shaders and give parity with the resolution scaler of optifine.

**Comment by toomuchcodehelp** [comment] 2022-11-15 02:00
duplicate of #1637

**Closed** 2022-12-23 22:37 UTC
Labels: enhancement
