### ISSUE TITLE
Chat Text turns Black when shaders are enabled

### ISSUE THREAD

**Issue by FilipSly** [IrisShaders/Iris#2030] opened 2023-06-19 15:10 UTC
### What happened?

Whenever I enable shaders (I use BSL and SEUS Renewed), all the text in the chat turns black and its impossible to read!

### Screenshots

With
![image](https://github.com/IrisShaders/Iris/assets/82275709/c529f5c8-2c6e-4d03-951e-df907f9e1da7)

Without
![image](https://github.com/IrisShaders/Iris/assets/82275709/9fb23380-dace-4103-b634-3ed11eedb0e6)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/11789523/latest.log)

### Minecraft Version

Minecraft 1.20

### Iris Version

iris-mc1.20-1.6.4.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GTX1060 6GB

**Comment by Lolothepro** [comment] 2023-06-19 15:29
duplicate of https://github.com/IrisShaders/Iris/issues/2024

**Comment by Lolothepro** [comment] 2023-06-19 15:33
ok

**Comment by Lolothepro** [comment] 2023-06-19 15:33
Do you use Feather Client?

**Comment by FilipSly** [comment] 2023-06-19 15:34
> Do you use Feather Client?

I do in fact use Feather

**Comment by JustMordecai** [comment] 2023-06-20 13:30
I'm also on Feather and am experiencing this exact issue. I'm somewhat of an inexperienced Minecraft modder, so with Iris having this bug, I am guessing there are no ways for me to use shaders until it is fixed because OptiFine doesn't work with Feather as far as I'm aware.

**Comment by IMS212** [comment] 2023-06-20 13:50
Iris does not support Feather Client.

**Closed by IMS212** 2023-06-20 13:50 UTC
Labels: bug
