### ISSUE TITLE
Swinging bells behave strangely when using Enhanced Block Entities

### ISSUE THREAD

**Issue by Janfel** [IrisShaders/Iris#357] opened 2021-06-10 08:31 UTC
When hitting a bell, you can see entities through it as long as it is swinging. I am using Iris 1.0.0 and this does not happen when using a recent build of regular Sodium instead of Iris.

Edit: The behavior changed for unknown reasons, now the swinging bell has messed up textures instead. See the third screenshot. ~~Also this only happens with this specific resource pack: [VanillaTweaks_r601019.zip](https://github.com/IrisShaders/Iris/files/6629765/VanillaTweaks_r601019.zip)~~ This information is incorrect.

![2021-06-10_10 25 22](https://user-images.githubusercontent.com/33464477/121491983-bdd57780-c9d6-11eb-8001-1f1e2ca0dd7c.png)

![2021-06-10_10 31 57](https://user-images.githubusercontent.com/33464477/121492535-3f2d0a00-c9d7-11eb-9078-6114b2a3afa6.png)

![2021-06-10_10 41 12](https://user-images.githubusercontent.com/33464477/121494493-1443b580-c9d9-11eb-95a4-9832299b16a1.png)

**Comment by Janfel** [comment] 2021-06-14 19:59
When using [Enhanced Block Entities](https://github.com/FoundationGames/EnhancedBlockEntities), this also happens with chests.
![2021-06-14_21 55 13](https://user-images.githubusercontent.com/33464477/121951858-c1ad2500-cd5b-11eb-9b42-45adae24022b.png)
![2021-06-14_21 55 16](https://user-images.githubusercontent.com/33464477/121951862-c2de5200-cd5b-11eb-80f8-cefa248f6c67.png)

**Comment by CodingRays** [comment] 2021-06-27 21:12
I was unable to reproduce the bell issue with iris 1.0 and trunk both with and without sodium. 
Were you using any other mods and what shaderpack are you using?

**Comment by Janfel** [comment] 2021-07-09 19:17
I am using Sildurs Vibrant Shaders. After some further testing, I have found that this is an incompatibility with the “Enhanced Bells” feature of Enhanced Block Entities. This is however hardly noticeable when using only Iris and EBE, because of https://github.com/FoundationGames/EnhancedBlockEntities/issues/38, as only the swinging one of the two bell models exhibits this behavior. Using Indium in addition to Iris and EBE fixes https://github.com/FoundationGames/EnhancedBlockEntities/issues/38 so you can see the issue as I originally described it.

In short: The issue is caused by Enhanced Block Entities with “Enhanced Bells” turned on, but you need Indium to properly see it, because it is obstructed by https://github.com/FoundationGames/EnhancedBlockEntities/issues/38.

**Versions:**

- [Enhanced Block Entities](https://github.com/FoundationGames/EnhancedBlockEntities): 0.3.1
- [Fabric API](https://github.com/FabricMC/fabric): 0.35.0
- [Indium](https://github.com/comp500/Indium): Compiled from https://github.com/comp500/Indium/commit/a997c5583c1d995eb0da393d1784805bae92454a using GitHub Actions
- Iris: 1.0.0
- [Sildurs Vibrant Shaders](https://sildurs-shaders.github.io/): 1.29 Medium

**Comment by coderbot16** [comment] 2022-01-02 08:07
Does this issue still happen with Iris 1.1.3?

**Comment by coderbot16** [comment] 2022-02-10 06:53
Closing until this issue is confirmed to still be present in modern Iris - given that there's been no further reports of the issue, I'm guessing it was fixed somewhere along the way between 1.0.0 and 1.2.0.

**Closed by coderbot16** 2022-02-10 06:53 UTC
Labels: bug, contributions requested, more information needed, mod compatibility
