### ISSUE TITLE
Normal, Bump and Parallax Mapping support

### ISSUE THREAD

**Issue by SirPytan** [IrisShaders/Iris#753] opened 2021-08-13 12:57 UTC
I am using the Patrix Texture pack, which uses PBR Material Textures, but it does not use them.
I tried SEUS PTGI E12 or E11 and Continuum Shaders, as well as Complementary 4.1 Shaders, but it does not use them.

Will you add a Shader options menu, like Optifine has, to configure each shader? Would be great.
If you could support for these kind of Texturepacks would be great. As well as support for Connected Textures in the Optifine format.

**Comment by IMS212** [comment] 2021-08-13 14:37
Duplicate of #130. Shader options are also planned to be supported soon.

**Closed by IMS212** 2021-08-13 14:37 UTC
Labels: enhancement
