### ISSUE TITLE
Change to SteamOS possibly broke shaders

### ISSUE THREAD

**Issue by ssscott75044** [IrisShaders/Iris#2417] opened 2024-07-17 16:23 UTC
### What happened?

I've been running Iris via Prism on Steam Deck, loading SEUS shaders from file.  It worked until around mid-June, when entering the world the screen split into two big triangles and flickered and was unplayable.  Was able to continue playing by disabling shaders.  I had not changed anything.  The only changes were SteamOS updates, as well as Prism itself.

I've got a MC 1.19.3 Prism instance that was working the last time I used it, many months ago, but now it displays the same problem as my active game.  I've made a copy of my active game and updated to Minecraft 1.20.1 and all mods, and everything works except for shaders.  I've made a copy and updated to Minecraft 1.21 and all mods, and everything works except for shaders.

Because my much older untouched Prism instance demonstrates the same problem that began about a month ago, this appears to be a SteamOS problem.  I received a tip that the Steam Deck Beta Client Update of June 14 changed something regarding shaders (I assume with other games), that maybe broke Iris shaders specifically on Steam Deck.

Is Iris specifically tested on Steam Deck?  If not, could you begin to do so?  I think it's a good platform for Minecraft with shaders.  And portable, no less.

### Minecraft Version

tried on 1.19.3, 1.20.1, 1.21

### Iris Version

1.5.1 with MC 1.19.3, 1.7.1+mc1.20.1, 1.7.1+mc1.21

### Operating System

SteamOS

### What is your GPU?

AMD 0405

**Comment by ssscott75044** [comment] 2024-07-17 19:05
I submitted a request to Valve to see what they could do, and they said it's beyond their scope.  So I guess the only solution is for Iris to adjust.  Assuming of course that a Steam Deck client update caused this problem.

**Comment by IMS212** [comment] 2024-07-18 00:02
This is unrelated to the Steam Deck, and a duplicate of #2411. It affects all AMD devices on Linux.

**Closed as not planned by IMS212** 2024-07-18 00:02 UTC
Labels: bug

**Comment by ssscott75044** [comment] 2024-07-18 01:07
This looks correct.  I tried complementary shaders and they seem to work.  Will avoid water for a while I guess.  Thanks!
