### ISSUE TITLE
Incorrect rendering of running water on ice

### ISSUE THREAD

**Issue by ZechariahB** [IrisShaders/Iris#1476] opened 2022-06-08 06:15 UTC
### What happened?

Ice is rendered see though when running water is placed on top. Additional various water sources nearby will create a visible 16 x 16 grid where the sides of water render ice. Water source blocks seem to not have this issue. 

### Screenshots

![Screenshot_20220608_015937](https://user-images.githubusercontent.com/84613764/172543949-d5f5ca44-e328-42a3-8596-8fdfa6d38b62.png)

### Minecraft Version

1.19

### Iris Version

iris-mc1.19-1.2.5

### Sodium Version

sodium-fabric-mc1.19-0.4.2+build.16

### Operating System

KDE Plasma

### What is your GPU?

Nvidia GeForce RTX 3050 Ti

### Java Version

Java 16

**Comment by LordVertice** [comment] 2022-06-09 12:57
Pretty sure this is related: with any shaders active, water cannot be seen through glass, and glass cannot be seen through water.

![2022-06-09_14 50 40](https://user-images.githubusercontent.com/56739341/172851663-464871a5-5fb1-4084-8e33-391fb3b4d48a.png)
Didn't take a screenshot of it, but when I enter that glass cage, the entire ocean floor becomes visible due to the water not rendering at all. Likewise, diving below the ocean surface makes all glass blocks seemingly disappear. I can provide more screenshots or logs if needed.

**Comment by LordVertice** [comment] 2022-06-15 22:55
Alright, so the issue is 100% reproducible on 1.17.1. However, I believe there may be 2 different issues happening here. OP's ice related issue happens on Sodium with and without Iris and is tracked here: CaffeineMC/sodium-fabric#1286 but seems to be caused by CaffeineMC/sodium-fabric#38

This may or may not be what's causing some shaders to go nuts over water and stained glass (see my previous comment), since issue 38 is tracking a variety of different translucency related issues caused by the same underlying problem, however this in particular only shows up when using Iris shaders. Perhaps there's still something that can be done on Iris' end? If not, this is up to Sodium's devs.

Here are some more screenshots: https://imgur.com/a/qTyizdN

**Comment by coderbot16** [comment] 2022-06-15 23:35
This seems to just be a case of Sodium's infamous translucency sorting issues, so I will be closing this issue since there's nothing to be done on the Iris side to fix it.

The issue with stained glass and water in the comment is a limitation specific to deferred-rendered shader packs and there is nothing that Iris can do about it. Shader packs like Complementary Shaders use forward rendering and are not affected by that issue, just by Sodium's issue.

You can tell the difference between Sodium's translucency sorting issues happen within a chunk, but deferred rendering translucency issues happen with all translucent surfaces, even between chunks.

**Closed** 2022-06-15 23:36 UTC
Labels: bug
