### ISSUE TITLE
I have no shadows in shader packs with shadows

### ISSUE THREAD

**Issue by miltos22** [IrisShaders/Iris#302] opened 2021-05-28 19:14 UTC
![2021-05-28_22 12 57](https://user-images.githubusercontent.com/46090693/120031770-e9815680-c001-11eb-9c1f-82ba42d68362.png)

I have no shadows in shader packs that have shadows
ive tried:
Sildurs vibrand extreme
BSL

i am using an rx 570

**Comment by IMS212** [comment] 2021-05-28 19:15
Shadows are not added to the public versions of iris yet, please read the readme file.

**Comment by coderbot16** [comment] 2021-05-28 19:15
Duplicate of #84.

**Closed by coderbot16** 2021-05-28 19:15 UTC
