### ISSUE TITLE
POM & PBR not Supported. Maybe config Issue?

### ISSUE THREAD

**Issue by Ex4byte** [IrisShaders/Iris#277] opened 2021-05-18 20:08 UTC

**Comment by IMS212** [comment] 2021-05-18 22:02
Duplicate of #130, not a bug. PBR is not supported yet

**Comment by coderbot16** [comment] 2021-05-18 22:20
Closing as a duplicate - this feature will take quite some effort to fully support and isn't a super high priority right now, but it will be supported eventually.

**Closed by coderbot16** 2021-05-18 22:20 UTC
