### ISSUE TITLE
When Kappa Shaders Are Active The Entire Screen Is White

### ISSUE THREAD

**Issue by GabeHanby** [IrisShaders/Iris#1409] opened 2022-05-05 16:05 UTC
### What happened?

Upon selection of the Kappa Shader the entire screen becomes white. I am still able to move and perform in game activites just the screen is whited out. This is the only shader it has happened on out of the 5 different shaders i tried.

### Screenshots

![image](https://user-images.githubusercontent.com/46830575/166964907-8bf8265a-8c40-41c7-9b15-5777c139535f.png)

### Minecraft Version

1.18.2

### Iris Version

on both the curse forge default and Pbr beta 4 1.18.2

### Sodium Version

default curse forge 

### Operating System

windows 11

### What is your GPU?

Nvidia Geforce GTX 1060 6GB

### Java Version

Java kit 18

### Additional context

The SS taken is not what it looked like, i was unable to grab a SS for whatever reason, just note the whole screen is white

**Comment by Lolothepro** [comment] 2022-05-05 16:05
https://github.com/IrisShaders/Iris/issues/1030

**Comment by coderbot16** [comment] 2022-05-07 23:04
Duplicate of https://github.com/IrisShaders/Iris/issues/1030. This is likely caused by the lack of support for the "custom uniforms" feature of the OptiFine shader pipeline.

**Closed by coderbot16** 2022-05-07 23:04 UTC
Labels: bug
