### ISSUE TITLE
Really low fps even without shaders

### ISSUE THREAD

**Issue by Boomy639** [IrisShaders/Iris#472] opened 2021-07-01 17:14 UTC
### What happened?

This mod gives me lower fps than Vanilla minecraft even without the shaders and everything set to low

Vanilla Minecraft settings, Chunks: 8, Graphics: Fancy, Smooth Lighting: On/Maximum, Other things (e.g Biome blend): on
Fps= 80 to 100

IrisShaders Settings, Chunks: 2, Graphics: Fast, Smooth Lighting: Off, Other things (^): off
Fps= 20 to 40

### Iris and Minecraft Version

Both 1.17

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Geforce GT710

### Java Version

Java 16

**Comment by DestinyTheGreat** [comment] 2021-07-01 17:15
send screenshots of your f3 debug screen, and latest.log file

**Comment by Boomy639** [comment] 2021-07-01 17:20
> send screenshots of your f3 debug screen, and latest.log file

okay

**Comment by Boomy639** [comment] 2021-07-01 17:28
![2021-07-01_18 24 52](https://user-images.githubusercontent.com/74262738/124165655-f3cbc000-da99-11eb-8aa7-266cd08275bf.png)
[latest.log](https://github.com/IrisShaders/Iris/files/6749861/latest.log)

**Comment by hewnly** [comment] 2021-07-01 17:46
had the same results i think its because of the "active renderer: none (vanilla)"

**Comment by AlsoNiko** [comment] 2021-07-01 17:47
That just means it's using the vanilla rendering api and not the fabric rendering api, it wouldn't cause the issue

**Comment by ttltrashmammal** [comment] 2021-07-02 06:37
Having a very similar experience, originally thought it may have been my resource packs but even with them disabled and everything else set to the minimum settings I've been experiencing serious FPS drops (lowest I've seen was 7, but it quickly hopped back up to 9). It averages 13 and gets the worst when I try to turn or look up- down isn't as low as the other directions.

**Comment by Xenthio** [comment] 2021-07-02 08:14
I have this issue aswell

**Comment by Aiko-Suzuki** [comment] 2021-07-02 09:23
got the same issue as well.

**Comment by ColdIce1605** [comment] 2021-07-02 13:59
It seems Sodium has a leak and Iris itself has a few might want to check both vram and ram.

**Comment by yitzy299** [comment] 2021-07-02 14:04
Log files and other information would be useful

**Comment by ColdIce1605** [comment] 2021-07-02 14:04
@coderbot16 maybe add something like sodium issue or ... Forgot what it was called I'll come back with a edit.

**Comment by Boomy639** [comment] 2021-07-02 16:19
> Log files and other information would be useful
latest.log under the screenshot

**Comment by ttltrashmammal** [comment] 2021-07-05 01:35
> Having a very similar experience, originally thought it may have been my resource packs but even with them disabled and everything else set to the minimum settings I've been experiencing serious FPS drops (lowest I've seen was 7, but it quickly hopped back up to 9). It averages 13 and gets the worst when I try to turn or look up- down isn't as low as the other directions.
> 
> EDIT: Wanted to mention that it will start out great at about 60-70 fps with shaders and the works, 80-90 with just Iris, Fabric and Origins. However, after roughly 30 minutes into gameplay (no matter whether on a server or a single player world) it starts to tank into the previous mentioned drops.

So I played last night and decided to take some screenshots from when it tanks. I can grab the logs as well; I tested it without the other mods with just Iris and Sodium and it still has the same issues so I didn't bother screenshotting them. The screenshots include the mods:

- Iris/Sodium, 
- LambsDynamicLights, 
- OkZoomer, 
- Origins/Extra Origins/Fabric 
- ShulkerBoxToolTip
- ModMenu
- Music Reducer
- Pehkui

The texture/resource packs I am using are:

- Better Visibility of Ores
- Better Clear Glass
- Colorful Flora
- Kal's Armor
- Pride Axolotls
- Visible Ores
- A Vanilla Tweaks pack

I was playing for four hours at this point (from roughly 9 pm to 1 am, give or take) with Complementary Shaders on and it was running at an average of 45 fps, 75 fps without shaders. I stayed within a 70 chunk radius (working on two builds side by side, they span roughly 300 blocks in a square?) This was right before I turned the shaders off as it became unplayable:

![2021-07-04_01 24 49](https://user-images.githubusercontent.com/86491611/124406306-a0aa7500-dd06-11eb-887b-490d16ae2420.png)
![2021-07-04_01 25 22](https://user-images.githubusercontent.com/86491611/124406322-b029be00-dd06-11eb-914b-7413da35d4ad.png)

It worked for the twenty or so minutes and then this happened:

![2021-07-04_01 32 19](https://user-images.githubusercontent.com/86491611/124406414-ea935b00-dd06-11eb-910c-5b1443129376.png)
![2021-07-04_01 41 16](https://user-images.githubusercontent.com/86491611/124406365-c899d880-dd06-11eb-9907-f67625c0c07b.png)
![2021-07-04_01 41 12](https://user-images.githubusercontent.com/86491611/124406373-ce8fb980-dd06-11eb-91f3-b3c9bfcfc818.png)

When looking back at the logs (attached at bottom), I mainly saw these issues:

- *[STDRR] No uniform exists with name <name> (ex. u_ModelViewMatrix).
- *[<sodium shaders>] Unsupported uniform: float/mat4/vec3 <name> (one of those 3 and then a similar or matching name to above) (this one and the one above begin anytime I start the CS pack and happens a *lot*. Not sure why but that's why I'm not a programmer)
- *Shader <shader name> could not find sampler named <name> in the specified shader program. (this one varies quite a bit.)
- Ignoring draw buffer 9 from draw buffers array [0, 5, 9] since Iris doesn't support extended color buffers yet.
- Received passengers for unknown entity (.....Yeah no clue. Starts about 30 minutes in.)
- *Failed to parse the block ID map entry <name> There is no block with the name <name>! (It's calling on a bunch of plants. Going to completely honest here, this is partially why I included the list of mods and textures because _I have no idea where these are coming from_)

*Happens the most

There will also be a few errors about simple voice chat, its on the server but I don't have it; it's never been an issue and when I don't have Iris/Sodium running it's fine. It isn't the mods nor is it the server (we use Shockbyte, but it does this offline as well). My computer has ran these mods and more with no issue, so it's not a hardware issue either. I plan on trying different shaderpacks to see if certain parts of certain packs are causing conflicts or if its just a pack-wide thing.

Java 16
Windows 10
Hardware and Iris/Sodium versions in the screenshots

[latest.log (pt.1).txt](https://github.com/IrisShaders/Iris/files/6760998/latest.log.pt.1.txt)
[latest.log (pt.2).txt](https://github.com/IrisShaders/Iris/files/6760999/latest.log.pt.2.txt)
[latest.log (pt.3).txt](https://github.com/IrisShaders/Iris/files/6761000/latest.log.pt.3.txt)

**Comment by DSRoie** [comment] 2021-07-05 15:15
> > 有一个非常相似的经验，最初以为这可能是我的资源包，但即使他们禁用和其他一切设置到最低设置，我一直在经历严重的FPS下降（我见过的最低是7，但它迅速跳回9）。它平均 13， 并得到最坏的， 当我试图打开或向上看 - 没有其他方向低。
> > 编辑： 想提一下， 它会开始伟大的约 60 - 70 fps 与着色器和作品， 80 - 90 只有虹膜， 织物和起源。然而，大约30分钟后进入游戏（无论在服务器上还是单个玩家世界），它开始坦克到前面提到的下降。
> 
> 所以我昨晚玩了， 并决定采取一些截图时， 它坦克。我也附加了日志。我测试它没有其他模组-只是虹膜和钠，它仍然有同样的问题，所以我没有费心截图。截图包括模组：
> 
> * 虹膜/钠，
> * 羔羊动力灯，
> * 奥克祖默，
> * 起源/额外起源/织物
> * 舒尔克盒工具
> * 莫德梅努
> * 音乐减压器
> * 佩赫奎
> 
> 我使用的纹理/资源包包括：
> 
> * 更好的奥雷斯能见度
> * 更好的透明玻璃
> * 五颜六色的植物
> * 卡尔的盔甲
> * 骄傲阿克索洛特斯
> * 可见的奥雷斯
> * 香草调整包
> 
> 我玩了四个小时，在这一点上（从大约晚上9点到凌晨1点，给或采取）与补充着色器，它运行在平均45 fps，75 fps没有着色器。我住在一个70块半径内（并排在两个建构上工作，它们跨越大约300个方块？这是在我关闭着色器之前， 因为它变得无法播放：
> 
> ![2021-07-04_01 24 49](https://user-images.githubusercontent.com/86491611/124406306-a0aa7500-dd06-11eb-887b-490d16ae2420.png)
> ![2021-07-04_01 25 22](https://user-images.githubusercontent.com/86491611/124406322-b029be00-dd06-11eb-914b-7413da35d4ad.png)
> 
> 它工作了二十分钟左右，然后发生了这种情况：
> 
> ![2021-07-04_01 32 19](https://user-images.githubusercontent.com/86491611/124406414-ea935b00-dd06-11eb-910c-5b1443129376.png)
> ![2021-07-04_01 41 16](https://user-images.githubusercontent.com/86491611/124406365-c899d880-dd06-11eb-9907-f67625c0c07b.png)
> ![2021-07-04_01 41 12](https://user-images.githubusercontent.com/86491611/124406373-ce8fb980-dd06-11eb-91f3-b3c9bfcfc818.png)
> 
> 回顾日志（附在底部）时，我主要看到以下问题：
> 
> * *[STDRR]不存在带有名称的制服（前u_ModelViewMatrix）。
> * *[]不受支持制服：浮动/mat4/vec3（其中3个，然后一个类似或匹配的名称到上面）（这一个和上面的开始，每当我开始CS包，并发生_很多_。不知道为什么，但这就是为什么我不是一个程序员）
> * *着色器找不到指定着色器程序中命名的取样器。（这一个变化很大。
> * 忽略抽奖缓冲区 9 从抽奖缓冲区阵列 [0， 5， 9]， 因为 Iris 还不支持扩展的颜色缓冲区。
> * 收到未知实体的乘客（。。。。是的，没有线索。大约30分钟后开始。
> * *未能解析块ID地图条目没有与名称块！（它呼吁一堆植物。要完全诚实在这里，这就是为什么我包括模组和纹理列表的部分原因，因为_我不知道这些来自哪里_)
> 
> *最多发生
> 
> 也会有一些关于简单语音聊天的错误，它在服务器上，但我没有它：这从来都不是问题，当我没有虹膜/钠运行它的罚款。它不是模组，也不是服务器（我们使用休克字节，但它也离线）。我的计算机已运行这些模组和更多没有问题，所以它不是一个硬件问题。我计划尝试不同的着色器包，看看某些包的某些部分是否正在引起冲突，或者它只是一个包范围内的事情。
> 
> Java 16
> Windows
> 10 硬件和虹膜/钠版本在截图中
> 
> [最新.log （第 1 点）.txt](https://github.com/IrisShaders/Iris/files/6760998/latest.log.pt.1.txt)
> [最新.log （第 2 点）.txt](https://github.com/IrisShaders/Iris/files/6760999/latest.log.pt.2.txt)
> [最新.log （第 3 点）.txt](https://github.com/IrisShaders/Iris/files/6761000/latest.log.pt.3.txt)

Thank you for your meticulous reply

**Comment by SweepSwap** [comment] 2021-07-07 02:16
i think it gets worse when looking at lights like torches and lanterns

**Comment by ttltrashmammal** [comment] 2021-07-07 02:34
It definitely doesn't help, that's for sure. I've also noticed that loading animals or mobs doesn't trigger it? It seems to just progressively get worse over the course of two minutes.

**Comment by AlsoNiko** [comment] 2021-07-07 02:37
This is known, all of it. It's being fixed behind the scene.

**Comment by Boomy639** [comment] 2021-07-10 19:00
one thing i do know is an i7 and gtx 980 should NOT be getting 0fps, jesus

**Comment by AlsoNiko** [comment] 2021-07-10 19:01
Once again, the issue is being fixed, it was an issue with a mem leak that is being patched by both the sodium and iris team actively, and the next release should solve all these issues

**Comment by Boomy639** [comment] 2021-07-11 13:01
> Once again, the issue is being fixed, it was an issue with a mem leak that is being patched by both the sodium and iris team actively, and the next release should solve all these issues

Thank you Niko

**Comment by DestinyTheGreat** [comment] 2021-07-20 22:14
Should be fixed in latest commits

**Closed** 2021-07-20 22:15 UTC
Labels: bug
