### ISSUE TITLE
Windows 11 Build 22000.65: Computer starts lagging with File Explorer open, after exiting Iris.

### ISSUE THREAD

**Issue by Koomongous** [IrisShaders/Iris#550] opened 2021-07-15 17:07 UTC
### What happened?

When I launch and then quit Iris & Sodium (Installed with the Universal Installer), my computer will become super laggy if File Explorer is open. Inputs have massive delays and items drag like ~10 seconds behind. I believe this also happens when Alt+Tabbing out of Iris. Restarting normally fixes this.

While typing this I have noticed that it fixed itself after a while, but it still should not happen.

### Screenshots

I have linked a video as I can't exactly screenshot lag.

https://mega.nz/file/SfJSzZ4K#zvjgNkC0g_qqnsnhOqquHfMbD9XCrUcbLRiuZb5Aerc

### Iris and Minecraft Version

iris-fabric-loader-0.11.5-1.17.1.jar

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 11: Build 22000.65 co_release

### What is your GPU?

RX 5700XT

### Java Version

Java 16.0.1

**Comment by IMS212** [comment] 2021-07-15 17:10
Cannot replicate, are you sure this isn't just general lag caused by Windows/Minecraft closing

**Comment by Koomongous** [comment] 2021-07-15 19:07
I don't believe so, that kind of lag normally doesn't happen on Vanilla Minecraft or Optifine and my PC specs are decent, Ryzen 7 2700X. I don't know if Iris is the sole cause, but my game has also crashed and made Chrome give an out of memory error.

**Comment by AlsoNiko** [comment] 2021-07-15 19:25
Ah this is caused by a memory leak which has been fixed in dev

**Comment by Koomongous** [comment] 2021-07-15 19:46
I noticed this when Task Manager reported 9.5GB RAM usage while using Iris, but I think it is a different issue altogether as Task Manager is currently reporting 5.5GB RAM usage while having this lagging issue after closing Iris.

**Comment by GialliDev** [comment] 2021-07-16 11:37
Windows 11 is still a Developement release, so the issue could easily be linked to some glitch in Windows, it's never recommended to use Dev builds for day-to-day use.

**Comment by forkiesassds** [comment] 2021-07-17 13:36
Can not reproduce. Using Iris 1.1.0 for Minecraft 1.17 from the curseforge page. On build 22000.71.

**Comment by Koomongous** [comment] 2021-07-17 16:14
Yea idk, I'll try the curseforge version. It's weird because there aren't any corrupt files on my install so I don't get why it happens. I've also updated to build 22000.71.

**Comment by Koomongous** [comment] 2021-07-17 16:45
Ok I can't be certain yet but I just did a clean install of minecraft, deleting the .minecraft folder, and it seems like it might be working now? I'll play for a while and see if the issue persists.

**Comment by Koomongous** [comment] 2021-07-18 17:06
I've just noticed that this happens with Minecraft in general, not just Iris, so I'm going to close the issue.

**Closed** 2021-07-18 17:06 UTC
Labels: bug
