### ISSUE TITLE
Vanilla issue: World border interacts oddly with water with Fancy Graphics

### ISSUE THREAD

**Issue by CalXee** [IrisShaders/Iris#267] opened 2021-05-10 23:37 UTC
World border doesn't render underwater if you are out of water, and doesn't render out of water when you are underwater.

![2021-05-10_19 36 54](https://user-images.githubusercontent.com/68349758/117737145-37efc200-b1c7-11eb-9b09-5281c28789bd.png)
![2021-05-10_19 36 58](https://user-images.githubusercontent.com/68349758/117737147-38885880-b1c7-11eb-9636-1318a0067ffb.png)

**Comment by coderbot16** [comment] 2021-05-10 23:46
It's likely that this is a bug with Sildur's Vibrant Shaders inherent in its usage of deferred rendering that I won't be able to fix. If you want shaders with a similar visual style that handle translucency better, Complementary Shaders is a good choice.

The only reason why I was able to fix particles was because they were opaque but being rendered as if they were translucent. However, things like the worldborder or campfire smoke particles are not really things that can be fixed on my side.

**Comment by CalXee** [comment] 2021-05-10 23:47
I see, I wonder if BSL is fixable

**Comment by CodingRays** [comment] 2021-06-27 15:41
Im assuming with the bug with rain youre referencing #289? If so then i dont think so. I was unable to reproduce #289 on trunk but i was able to reproduce this bug.

**Comment by CodingRays** [comment] 2021-06-27 20:53
I think this might be a shaderpack issue. The worldborder also isnt visible with optifine.

**Comment by CalXee** [comment] 2021-07-23 20:52
Changed to only state the effects on vanilla rendering, as the problems with shaderpacks seems to not be an Iris issue.

**Comment by coderbot16** [comment] 2022-01-19 07:32
This isn't feasibly fixable by us. See ShaderpackBugs.

**Closed by coderbot16** 2022-01-19 07:32 UTC
Labels: wontfix
