### ISSUE TITLE
The chunk limit is not visible with Cyanide Shaders

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1098] opened 2021-12-15 17:08 UTC
### What happened?

The chunk limit is not visible with Cyanide Shaders

### Screenshots

![2021-12-15_18 06 44](https://user-images.githubusercontent.com/68275908/146232067-55ffd5a7-5512-4147-a702-d7bd7a287d55.png)
![2021-12-15_18 06 45](https://user-images.githubusercontent.com/68275908/146232106-c34f654a-c06b-45b5-bd76-e80d15ad1a0c.png)

### Minecraft Version

Minecraft 1.18

### Iris Version

iris-mc-1.18.1

### Sodium Version

sodium 0.4 alpha 5

### Operating System

Ubuntu 20.04

### What is your GPU?

GTX 1070

### Java Version

Java 17

**Comment by coderbot16** [comment] 2021-12-18 00:52
Underlying cause: https://github.com/IrisShaders/Iris/issues/773

**Comment by LizIsTired** [comment] 2022-02-23 20:19
Why did you just close and repoen this issue?

**Comment by Lolothepro** [comment] 2022-02-23 20:24
I can't reproduce this

**Comment by LizIsTired** [comment] 2022-02-23 20:25
If you can't reproduce it, that likely means it's been fixed so you can just close the issue

**Comment by coderbot16** [comment] 2022-03-17 06:27
I saw this in 1.16 trunk at one point

**Closed** 2022-06-07 19:45 UTC
Labels: bug, status: fixed in next release
