### ISSUE TITLE
what's up with entities

### ISSUE THREAD

**Issue by qpalx** [IrisShaders/Iris#2057] opened 2023-07-18 10:40 UTC
### What happened?

they all be buggin in seus ptgi 3.0
theres no such thing in optifine

### Screenshots

![image](https://github.com/IrisShaders/Iris/assets/139867960/ddb35a76-f125-45b2-b06f-1e5272a20b7a)

### Minecraft Version

1.20.1

### Iris Version

1.6.4

### Operating System

windows 10 pro x64

### What is your GPU?

rtx 3070 

### Additional context

it is two chickens in the photo
yes i tried turning off motion blur

**Comment by Lolothepro** [comment] 2023-07-18 11:54
duplicate of #1446

**Closed** 2023-07-18 14:26 UTC
Labels: bug
