### ISSUE TITLE
Horse markings render over horse armor 

### ISSUE THREAD

**Issue by O-d-i-n-n** [IrisShaders/Iris#1853] opened 2023-01-28 08:02 UTC
### What happened?

With Iris-mc1.19.3-1.5.1 all horses render their markings over the top of their armor.

I have reproduced this consistently with only Iris and Sodium installed and no resourcepacks used.
Simply load a world, tame a horse and place any horse armor on it.

### Screenshots

![2023-01-28_09 05 35](https://user-images.githubusercontent.com/67060551/215254733-a5f137bd-5a76-41f5-b689-7342a4c01cda.png)

### Minecraft Version

Minecraft 1.19.3

### Iris Version

1.5.1

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce GTX 1060

### Additional context

This has been reported before for an older version.

**Comment by IMS212** [comment] 2023-01-28 15:35
Duplicate of #1365.

**Closed by IMS212** 2023-01-28 15:35 UTC
Labels: bug
