### ISSUE TITLE
Horse markings visible above horse armor

### ISSUE THREAD

**Issue by Footl0se** [IrisShaders/Iris#2450] opened 2024-08-22 19:43 UTC
### What happened?

when a horse has any horse armor equipped, their markings show up above it, this probably isn't caused by any of my mods, as the bug disapears once Iris is removed.

### Screenshots

![2024-08-22_14 32 24](https://github.com/user-attachments/assets/b33c1768-2737-4f2d-bd78-babf5c86d5e2)
![2024-08-22_14 48 41](https://github.com/user-attachments/assets/1a65bce1-bcb4-47b2-9752-47d79797f350)
![2024-08-22_15 31 51](https://github.com/user-attachments/assets/4b0d648a-50cc-4c48-ada9-e50765752722)

### Log output

[latest.log](https://github.com/user-attachments/files/16716799/latest.log)

### Minecraft Version

Minecraft 1.21

### Iris Version

iris-1.7.3+mc1.21.jar

### Operating System

Windows 11

### What is your GPU?

RX 5500 xt

### Additional context

As mentioned before, it is visible with any armor, the bug is also very easy to get, as most people equip armors on their horses.

**Comment by IMS212** [comment] 2024-08-22 19:44
duplicate of #1365

**Closed as completed by IMS212** 2024-08-22 19:44 UTC
Labels: bug
