### ISSUE TITLE
The ability to customize shaders

### ISSUE THREAD

**Issue by Fat123453** [IrisShaders/Iris#553] opened 2021-07-15 23:09 UTC
Certain shaders do not run well such as SEUS renewed due to the fact I am unable to disable/lower certain settings in the shader. Motion blur is also a big problem when enabling shaders and it being a preset option.

**Comment by IMS212** [comment] 2021-07-15 23:12
Duplicate of many other issues, shader configuration is being worked on.

**Closed by IMS212** 2021-07-15 23:12 UTC
Labels: enhancement
