### ISSUE TITLE
Adding the Vulcan API if feasible

### ISSUE THREAD

**Issue by daniellata** [IrisShaders/Iris#1842] opened 2023-01-13 15:09 UTC
I got the idea to fire up sheders on vulcan api but the problem is you can't use sodium to make iris work and vulcan api gives you more fps

**Comment by IMS212** [comment] 2023-01-13 16:17
Duplicate of #1515. Vulkan will not give more FPS.

**Closed by IMS212** 2023-01-13 16:17 UTC
Labels: enhancement

**Comment by daniellata** [comment] 2023-01-19 14:08
and why can not give after all vanilla gives

**Comment by IMS212** [comment] 2023-01-19 14:12
Because Vanilla does not have Vulkan. 

(We are very aware of the Vulkan mod and it’s improvement on FPS, but that’s actually unrelated to just being on Vulkan and just due to more modern code.)

**Comment by daniellata** [comment] 2023-01-19 15:57
too bad there's no sodium in vulkan

**Comment by starlite-developer** [comment] 2023-02-17 00:29
Sodium optimizes the Minecraft OpenGL Engine. VulkanMod completely changes the type of render Minecraft uses from OpenGl to Vulkan, therefore making Sodium completely useless at best on it, and would almost definitely crash it. So, in conclusion, Sodium on Vulkan would not improve fps even if someone managed to get it to run because Sodium is made to optimize a completely different renderer. Maybe in the future someone will work on a completely different mod to optimize Vulkan, but since it is in it's experiment phases I doubt that will be anytime soon.
