### ISSUE TITLE
Sodium compatibility is broken in the Sodium Branche

### ISSUE THREAD

**Issue by SirPytan** [IrisShaders/Iris#138] opened 2021-02-27 02:56 UTC
Currently with Sodium the version that should be compatible with it is broke, it directly crashed on startup.

**Comment by CraftalotReloaded** [comment] 2021-02-27 03:14
I'm afraid you might be doing something wrong unless it's like one of those AMD issues as i just tested and they're working.

**Comment by SirPytan** [comment] 2021-02-27 03:30
No, I just tested only with Sodium and the latest Iris mod from the compatibility branch and I get this:

`---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 27/02/2021, 04:27
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'iris'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.IllegalStateException: You do not have a compatible version of Sodium installed! You have 0.1.0 but IRIS-SNAPSHOT is expected
	at net.coderbot.iris.Iris.lambda$onInitializeClient$0(Iris.java:73)
	at java.base/java.util.Optional.ifPresent(Optional.java:176)
	at net.coderbot.iris.Iris.onInitializeClient(Iris.java:66)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 15.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1358737392 bytes (1295 MB) / 2600468480 bytes (2480 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 12
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx10240m
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>`

**Comment by CraftalotReloaded** [comment] 2021-02-27 03:32
Are you testing with normal sodium by any chance:
Caused by: java.lang.IllegalStateException: You do not have a compatible version of Sodium installed! You have 0.1.0 but IRIS-SNAPSHOT is expected

**Comment by SirPytan** [comment] 2021-02-27 03:34
Ah ok, where do I get this.

**Comment by CraftalotReloaded** [comment] 2021-02-27 03:36
Read the README properly

**Comment by SirPytan** [comment] 2021-02-27 03:41
Ok, yes, sorry I overlooked it. But can you also tell me the right path for the config file, because like I said in the other thread, it does not work without quotes.

**Comment by CraftalotReloaded** [comment] 2021-02-27 03:42
It doesn't need any path

**Comment by SirPytan** [comment] 2021-02-27 03:46
Ok, and how do I configure/set the right shaderpack?

**Comment by CraftalotReloaded** [comment] 2021-02-27 03:48
I'll continue this in the other issue, please close this one if resolved

**Comment by SirPytan** [comment] 2021-02-27 03:52
I will but I currently struggle to compile the sodium Iris version.

**Comment by CraftalotReloaded** [comment] 2021-02-27 03:54
You have to put the sodium compatible branch of iris into the loom cache folder of the sodium fork in order for that to work

**Comment by SirPytan** [comment] 2021-02-27 03:54
Ah ok, will try thanks.

**Comment by SirPytan** [comment] 2021-02-27 03:56
Ok, now it works, I will test it and then close this one.

**Closed** 2021-02-27 03:59 UTC
