### ISSUE TITLE
Water shows through on the underside of waterlogged stairs 

### ISSUE THREAD

**Issue by Justsnoopy30** [IrisShaders/Iris#242] opened 2021-04-14 23:32 UTC
https://user-images.githubusercontent.com/33374736/114793312-b33c9000-9d4f-11eb-93b5-876b18142142.mp4

**Comment by coderbot16** [comment] 2021-04-15 00:08
This seems like it could a shaderpack bug, could you please confirm whether it exists on OptiFine? If it's a shadepack bug I'm not sure what can be done about it on our side. Perhaps we'd exclude the bottom face of water if there's a solid face there or something?

**Comment by Justsnoopy30** [comment] 2021-04-15 00:16
> This seems like it could a shaderpack bug, could you please confirm whether it exists on OptiFine? If it's a shadepack bug I'm not sure what can be done about it on our side. Perhaps we'd exclude the bottom face of water if there's a solid face there or something?

Yeah I already checked, it does not happen on OptiFine.

**Comment by Kroppeb** [comment] 2021-04-15 04:26
I seem to remember this being a vanilla bug.

**Comment by Kroppeb** [comment] 2021-04-15 04:31
Ah this used to be a vanilla bug, but it has been fixed in 1.15-rc1
https://bugs.mojang.com/browse/MC-127005

**Comment by CodingRays** [comment] 2021-06-27 12:15
This issue only seems to appear when Sodium is installed. I tested on latest trunk and was able to reproduce it with sodium but not without.

**Comment by CodingRays** [comment] 2021-06-27 12:36
I think i found the issue. Sodium does not check for self occlusion in waterlogged blocks, standard minecraft does.

**Comment by CodingRays** [comment] 2021-06-27 12:38
Nevermind it does seem to attempt to check but for some reason the check fails to detect the occlusion.

**Comment by coderbot16** [comment] 2021-06-27 12:41
I think vanilla uses a tiny offset on the water to avoid the z fighting, but it seems like Sodium's compact vertex format might be rounding this offset down to zero.

**Comment by CodingRays** [comment] 2021-06-27 12:44
No i i looked at the vanilla code and it looks like they detect the culling. Sodium does have an offset and i can increase it to fix the issue . The standard offset is 0.001 which shouldnt cause rounding errors i dont think.

**Comment by CodingRays** [comment] 2021-06-27 12:58
I think what is happening is that sildurs shaders apply a tiny amount of wave animations to the bottom side of water blocks causing them to through the stairs faces. If i switch to different shaders that dont have waves the issue vanishes.

**Comment by CodingRays** [comment] 2021-06-27 13:44
I found the issue. When testing if a fluid is exposed mincraft tests both if the next block has a same type fluid and if the current block has a covered side. Sodium only runs the first test.

**Comment by CodingRays** [comment] 2021-07-15 22:45
A fix for this should now be in upstream sodium

**Comment by coderbot16** [comment] 2021-12-07 01:03
Thanks for getting that fixed. Though it still is an issue in 1.16.5. Not sure what we want to do about that.

**Comment by coderbot16** [comment] 2022-07-24 05:37
Closing this as wontfix for 1.16.5, since it's fixed in 1.17.1+ for Sodium and would be too difficult to backport on our side.

**Closed by coderbot16** 2022-07-24 05:37 UTC
Labels: version: 1.16, bug in sodium
