### ISSUE TITLE
Black outline not showing with shaders.

### ISSUE THREAD

**Issue by respectablenoob-source** [IrisShaders/Iris#769] opened 2021-08-19 04:00 UTC
### What happened?

The block outline is not visible with shaders enabled.

### Iris and Minecraft Version

iris 1.1.1 and 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

1660Ti

### Java Version

Java 16

**Comment by IMS212** [comment] 2021-08-19 04:36
Duplicate of #403.

**Closed by IMS212** 2021-08-19 04:36 UTC
Labels: bug

**Comment by respectablenoob-source** [comment] 2021-08-19 04:40
> Duplicate of #403.

Will this be fixed in the future?

**Comment by IMS212** [comment] 2021-08-19 04:49
Yes, it is planned.
