### ISSUE TITLE
Lighting from sky on sildur's vibrant is not being properly rendered

### ISSUE THREAD

**Issue by SweepSwap** [IrisShaders/Iris#153] opened 2021-03-04 19:38 UTC

**Comment by coderbot16** [comment] 2021-03-04 20:31
I'm going to assume that this is caused by the lack of shadows: https://github.com/IrisShaders/Iris/issues/84

However without a screenshot it's hard to know for sure.

**Comment by coderbot16** [comment] 2021-03-07 20:19
Closing this since no screenshot or additional information has been provided.

**Closed by coderbot16** 2021-03-07 20:19 UTC
Labels: more information needed
