### ISSUE TITLE
Light Overlay provided by mods such as MiniHUD do not render with shaders enabled

### ISSUE THREAD

**Issue by InQuognito** [IrisShaders/Iris#721] opened 2021-08-07 06:24 UTC
### What happened?

Title. Light overlays that show where mobs can spawn do not render whatsoever with shaders on. Disabling shaders makes it work as intended immediately.

### Screenshots

![shaders_off](https://user-images.githubusercontent.com/44120299/128590546-81f42d72-77c1-4a21-a737-138ec6701730.PNG)
![shaders_on](https://user-images.githubusercontent.com/44120299/128590554-1016068d-bb26-4cfd-8d6b-65a83f6a3430.PNG)

### Iris and Minecraft Version

Iris 1.1.1, MC 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 2070S

### Java Version

Java 16

**Comment by NoComment1105** [comment] 2021-08-07 06:24
duplicate of #218

**Comment by InQuognito** [comment] 2021-08-07 06:25
damn that was fast xD

**Closed by NoComment1105** 2021-08-07 06:24 UTC
Labels: bug

**Comment by NoComment1105** [comment] 2021-08-07 06:25
am speed xD

**Comment by InQuognito** [comment] 2021-08-07 06:26
sorry for the dupe issue!
