### ISSUE TITLE
Oceano flickering/pixelated water

### ISSUE THREAD

**Issue by Diztend** [IrisShaders/Iris#406] opened 2021-06-19 13:14 UTC
![2021-06-17_18 38 47](https://user-images.githubusercontent.com/39473569/122643612-48d71000-d143-11eb-9dc3-5544980a388b.png)

**Comment by coderbot16** [comment] 2021-12-13 22:13
Seems like a duplicate of https://github.com/IrisShaders/Iris/issues/958

**Closed** 2022-01-06 18:50 UTC
Labels: bug, status: fixed in next release
