### ISSUE TITLE
Lines shader not working in 1.17

### ISSUE THREAD

**Issue by LunaSeashell00** [IrisShaders/Iris#403] opened 2021-06-18 01:30 UTC
Repro steps:

Launch Iris 1.17 stand alone installation
Enter any world
Enable shaders: BSL or Complementary (latest dev versions, all default settings)
Expected: Default black selection outline should appear where crosshair is pointing
Observed: No selection outline at all
Note: This could be an issue with other shaders too, only tested using BSL and Comp at this point]

**Comment by Skyyofficial** [comment] 2021-06-30 11:25
Outlines are gone with Sildurs as well, outlines will show again when shaders are disabled

**Comment by CodingRays** [comment] 2021-06-30 14:49
I did some frame debugging and it looks like the issue is that in 1.17 the lines layer draws to a different framebuffer which should later be fused back into the main render but that step never happens.

**Comment by IMS212** [comment] 2021-08-03 01:03
This is the cause of many issues including hitboxes not rendering in debug.

**Comment by IMS212** [comment] 2021-08-21 21:05
This has been fixed in recent commits, feel free to reopen if you can find any issues with the fix.

**Closed by IMS212** 2021-08-21 21:05 UTC
Labels: bug

**Comment by davecaruso** [comment] 2021-12-21 21:11
It seems this doesnt work on the skylec shader pack, but the rest of the shaders including the ones mentioned above work.

**Comment by coderbot16** [comment] 2021-12-21 21:12
That is a separate issue being tracked here that will be fixed in the next release: https://github.com/IrisShaders/Iris/issues/929
