### ISSUE TITLE
Hitboxes don't render with shaders

### ISSUE THREAD

**Issue by matthew2837** [IrisShaders/Iris#688] opened 2021-08-03 01:00 UTC
### What happened?

Hitboxes do not render when shaders are enabled.

Steps:
1. Turn on shaders
2. Do F3 + B to turn on hitboxes

### Screenshots

With Shaders
![2021-08-02_20 54 12](https://user-images.githubusercontent.com/13020950/127941095-5c35113d-cdd7-4227-8b3e-e420d20ccf2d.png)
![2021-08-02_20 55 34](https://user-images.githubusercontent.com/13020950/127941168-2f5d7a6d-ad72-4387-a620-716aacbbcc8b.png)
![2021-08-02_20 55 48](https://user-images.githubusercontent.com/13020950/127941170-7ef2d1bb-f4f0-4e46-8df1-8263384c0a93.png)
Without Shaders
![2021-08-02_20 54 19](https://user-images.githubusercontent.com/13020950/127941100-44f034d7-c22c-4872-b87d-483cc1d5be97.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.1.jar

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 3060

### Java Version

16

**Comment by IMS212** [comment] 2021-08-03 01:03
Duplicate of #403.

**Closed by IMS212** 2021-08-03 01:03 UTC
Labels: bug
