### ISSUE TITLE
Can't use BSL shaders

### ISSUE THREAD

**Issue by iPlayNone** [IrisShaders/Iris#1351] opened 2022-04-07 13:54 UTC
### What happened?

When I try loading any shaders chocapic and BSL I pressed apply then nothing happens it doesn't crash or load the shader.

### Screenshots

![image](https://user-images.githubusercontent.com/72128959/162215145-12e3dcf4-13f7-4b8a-8277-0e99e0b0afbd.png)

### Minecraft Version

Fabric 1.18.1

### Iris Version

irirs-mc1.18.1-1.2.0-pre.jar

### Sodium Version

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar

### Operating System

Windows 10

### What is your GPU?

Intel Graphics

### Java Version

Java 17 or 18

**Comment by coderbot16** [comment] 2022-04-07 14:00
Probably a duplicate of https://github.com/IrisShaders/Iris/issues/441, please specify what Intel GPU you have so we can confirm.

**Comment by iPlayNone** [comment] 2022-04-07 14:15
> Probably a duplicate of #441, please specify what Intel GPU you have so we can confirm.

slr uh it's a "Intel HD Graphics 2500"

**Comment by coderbot16** [comment] 2022-04-07 14:19
In that case, it's a duplicate. There's no solution or workaround for now aside from using Linux or switching to 1.16.5.

**Closed by coderbot16** 2022-04-07 14:19 UTC
Labels: bug
