### ISSUE TITLE
Possible Incompatability causing texture bugs.

### ISSUE THREAD

**Issue by Razatop** [IrisShaders/Iris#1735] opened 2022-11-14 03:58 UTC
### What happened?

When enabling Iris in my modpack certain textures will break and turn into lines, but not the missing texture. The textures affected can change based upon what resource packs from mods are loaded and which aren't (Nothing important, just things like alternative textures offered by mods)

### Screenshots

![Screenshot_33](https://user-images.githubusercontent.com/43615000/201572035-5e3a1c8c-9bbb-42a9-a26f-f1d89b330323.png)
![Screenshot_34](https://user-images.githubusercontent.com/43615000/201572043-0c7832c2-e460-466d-b87f-643853c84271.png)
![Screenshot_35](https://user-images.githubusercontent.com/43615000/201572047-d7b659fc-1b86-4e58-8e1c-e819f421fa93.png)
![Screenshot_36](https://user-images.githubusercontent.com/43615000/201572051-5e98dc9d-bcf4-4537-972e-c46676d1d226.png)

### Log output

[raw.txt](https://github.com/IrisShaders/Iris/files/9999340/raw.txt)

### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.4.0.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce RTX 2080

### Additional context

Not sure what could be the issue here. I'm guessing it's conflicting with another performance mod. Going to go through and try to figure out what's going on.

**Comment by Timolino456** [comment] 2022-11-14 13:44
This bug is known already and will be fixed in iris 1.4.1

**Comment by Razatop** [comment] 2022-11-14 18:10
What's causing it if I might ask?

**Comment by Timolino456** [comment] 2022-11-14 18:12
Quoting Coderbot's message from the devlog channel of the Discord server: "This issue was caused by an oversight in Sodium that was over a year and a half old. It caused textures placed on the edge of the texture atlas (in this case, the still water texture) to have some of their texture coordinates wrap all the way around to zero. That's why the bottom of this water looks like a bunch of stripes - it's about 32 different Minecraft textures smooshed together!

This only occurred in very rare circumstances with specific combinations of resource packs and mods. Iris 1.2.5 added an optimization by Pepper to make the Minecraft texture atlas more compact, which made this issue way more likely. Thanks to a straightforward way of reproducing the issue with just Iris and Sodium provided by Deebz96, it's finally been fixed!"

**Comment by Razatop** [comment] 2022-11-14 23:42
Oh that's awesome, sorry for the spam then. Is there a release window. Also feel free to close this if you can. If not I'll close it tonight.

**Closed** 2022-11-19 19:46 UTC
Labels: bug
