### ISSUE TITLE
Continuum 2.0 crashes world on reload

### ISSUE THREAD

**Issue by AlsoNiko** [IrisShaders/Iris#296] opened 2021-05-27 03:15 UTC
Along with issue #295 Continuum 2.0 can also cause the world to crash when reloading (Including selecting it well in a world) 
[crash-2021-05-26_23.13.21-client.txt](https://github.com/IrisShaders/Iris/files/6550842/crash-2021-05-26_23.13.21-client.txt)
[latest.log](https://github.com/IrisShaders/Iris/files/6550843/latest.log)

**Comment by IMS212** [comment] 2021-05-27 03:20
Duplicate of #283.

**Closed** 2021-05-27 03:21 UTC
