### ISSUE TITLE
Mod incompatibility with Xaero's worldmap

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#46] opened 2020-12-29 07:48 UTC

**Comment by CompaqDisc** [comment] 2021-01-02 18:11
Cannot reproduce with Xaero's minimap alone. Must have Xaero's worldmap present (whether solo or not) to have this effect.

It looks like it wants some classes from OptiFine to be present.
```
[11:08:03] [main/WARN]: Error loading class: net/optifine/render/ChunkVisibility (java.lang.ClassNotFoundException: net/optifine/render/ChunkVisibility)
[11:08:03] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[11:08:03] [main/WARN]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersRender)
```

Screenshot:
![image](https://user-images.githubusercontent.com/12076803/103463245-50ffd800-4ce8-11eb-9dba-986f99da9951.png)

**Comment by coderbot16** [comment] 2021-03-04 20:30
Another similar issue with Xaero's Worldmap
![image](https://user-images.githubusercontent.com/22420959/110026311-575d0100-7ce5-11eb-90c6-70678d906d86.png)

**Comment by coderbot16** [comment] 2021-04-27 02:43
Based on my investigation, it appears that the changes that Iris makes to the vanilla management of texture units (moving the lightmap to texture unit 1 and the overlay texture to a different texture unit) conflict with Xaero's Worldmap, because Xaero's Worldmap assumes that texture unit 1 is the overlay texture.

At the end of rendering the map GUI, Xaero's Worldmap disables texture unit 1. Under vanilla, this disables the hurt flash overlay, which is what is expected. Under Iris, however, this disables the lightmap texture. This seemingly results in everything that uses a lightmap after that point in rendering (ie, all GUI elements) turning white.

These changes have also caused problems with Sodium. They were done so that the lightmap texture matrix would reside in `gl_TextureMatrix[1]` as shaderpacks expect, however this comes at the expense of compatibility with other mods. It appears that the best way forward is to patch shaderpacks to access the lightmap texture matrix in some other way, instead of through `gl_TextureMatrix[1]`, and then to revert the changes to the texture units.

**Comment by Mithos23** [comment] 2021-05-03 13:55
This issue is fixed in Xaero's World Map 1.13.1

**Comment by coderbot16** [comment] 2021-05-12 19:36
Though Xaero's World Map has worked around the issue on their side, I'd still like to rework how Iris manages the textures here to avoid having compatibility issues with other mods as well. I'll leave this issue open for now.

**Comment by thedocruby** [comment] 2021-06-11 06:13
Coderbot, i'm assuming this was one of the things you were talking about doing to clean up the code a bit before we move forward? I am putting this comment here to rrmind you, since the above comment is hidden in this unassuming issue and is kind of hard to find.

**Closed** 2021-07-07 00:21 UTC
Labels: mod compatibility
