### ISSUE TITLE
SEUS PTGI HRR Shaders not working

### ISSUE THREAD

**Issue by Pixel-Clay** [IrisShaders/Iris#1503] opened 2022-06-19 05:23 UTC
### What happened?

I tried loading SEUS PTGI HRR shaders, but nothing happened.
In Shader Options there was a message that shaders failed to load.

I tried various versions of the shader, including
- HRR 3 (AMD fix)
- HRR 2 (AMD fix)
- HRR 2 (vanilla)

### Screenshots

![image](https://user-images.githubusercontent.com/80592654/174466874-09db98f9-c602-4ec0-a461-78319063accf.png)
![image](https://user-images.githubusercontent.com/80592654/174466877-6bfe95a7-6999-476d-8c46-b64c06654e7e.png)
![image](https://user-images.githubusercontent.com/80592654/174466884-8e4b66bc-74c7-4528-a724-6c990da5b61d.png)

### Relevant log output

```shell
[10:07:20] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.6
[10:07:20] [ForkJoinPool-1-worker-8/WARN]: Mod cpm uses the version 0.4.3a which isn't compatible with Loader's extended semantic version format (Could not parse version number component '3a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[10:07:20] [main/WARN]: Warnings were found!
 - Mod 'Custom Entity Models' (cem) 0.7.1 recommends any version of completeconfig, which is missing!
	 - You should install any version of completeconfig for the optimal experience.
[10:07:20] [main/INFO]: Loading 88 mods:
	- additionalentityattributes 1.0.0+1.19 via apoli
	- apoli 2.5.0 via origins
	- betterbiomeblend 1.19-1.3.6-fabric
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- calio 1.7.0 via apoli
	- cardinal-components-base 5.0.0-beta.1 via apoli
	- cardinal-components-entity 5.0.0-beta.1 via apoli
	- cem 0.7.1
	- citresewn 1.1.0+1.19
	- citresewn-defaults 1.1.0+1.19 via citresewn
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 7.0.72
	- completeconfig-base 2.0.0-beta.3 via cem
	- completeconfig-gui-cloth 2.0.0-beta.3 via cem
	- continuity 2.0.0+1.19
	- cpm 0.4.3a
	- cullleaves 2.3.4
	- fabric 0.56.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via fabric
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.13+b2a4a624a9 via fabric
	- fabric-blockrenderlayer-v1 1.1.18+9ff28f40a9 via fabric
	- fabric-command-api-v1 1.2.5+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.1+cda9839ba9 via fabric
	- fabric-commands-v0 0.2.22+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.27+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.1.0+4a3ec384a9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.0.1+2a5b9210a9 via fabric
	- fabric-dimensions-v1 2.1.27+72da3b3da9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.25+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.4+767db26ea9 via fabric
	- fabric-item-groups-v0 0.3.23+9ff28f40a9 via fabric
	- fabric-key-binding-api-v1 1.0.18+9ff28f40a9 via fabric
	- fabric-keybindings-v0 0.2.16+df3654b3a9 via fabric
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
	- fabric-loot-api-v2 1.0.1+9e7660c6a9 via fabric
	- fabric-loot-tables-v1 1.1.1+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.8+33fbc738a9 via fabric
	- fabric-models-v0 0.3.15+9ff28f40a9 via fabric
	- fabric-networking-api-v1 1.0.27+7fe97409a9 via fabric
	- fabric-networking-v0 0.3.14+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.5+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-registry-sync-v0 0.9.16+92cf9a3ea9 via fabric
	- fabric-renderer-api-v1 1.0.8+9ff28f40a9 via fabric
	- fabric-renderer-indigo 0.6.6+9ff28f40a9 via fabric
	- fabric-renderer-registries-v1 3.2.18+df3654b3a9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-rendering-v0 1.1.20+df3654b3a9 via fabric
	- fabric-rendering-v1 1.10.14+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.3+9e7660c6a9 via fabric
	- fabric-screen-api-v1 1.0.23+9ff28f40a9 via fabric
	- fabric-screen-handler-api-v1 1.2.6+9ff28f40a9 via fabric
	- fabric-textures-v0 1.0.18+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabricloader 0.14.6
	- iris 1.2.5
	- java 17
	- kanos_config 0.3.1+1.14.4-1.19 via pehkui
	- lambdynlights 2.1.2+1.19
	- lazydfu 0.1.3
	- lithium 0.8.0
	- logical_zoom 0.0.15
	- midnightlib 0.5.2 via cullleaves
	- minecraft 1.19
	- modmenu 4.0.0
	- org_anarres_jcpp 1.4.14 via iris
	- org_joml_joml 1.10.4 via sodium
	- origins 1.6.1
	- pehkui 3.3.2+1.14.4-1.19
	- phosphor 0.8.1
	- playerabilitylib 1.6.0 via apoli
	- pride 1.1.2+1.19 via lambdynlights
	- reach-entity-attributes 2.3.0-SNAPSHOT via origins
	- reeses-sodium-options 1.4.3+mc1.19-build.43
	- sodium 0.4.2+build.16
	- sodium-extra 0.4.5+mc1.19-build.43
	- spruceui 4.0.0+1.19 via lambdynlights
	- voicechat 1.19-2.2.45
[10:07:21] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Clay/curseforge/minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[10:07:21] [main/INFO]: Compatibility level set to JAVA_17
[10:07:22] [main/INFO]: Loaded configuration file for Lithium: 94 options available, 0 override(s) found
[10:07:22] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[10:07:22] [main/INFO]: Loaded configuration file for Sodium Extra: 26 options available, 0 override(s) found
[10:07:23] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[10:07:24] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[10:07:25] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[10:07:27] [main/WARN]: Method overwrite conflict for method_9522 in sodium.mixins.json:features.render_layer.leaves.MixinLeavesBlock from mod sodium, previously written by eu.midnightdust.cullleaves.mixin.MixinLeavesBlock. Skipping method.
[10:07:32] [main/INFO]: Building unoptimized datafixer
[10:07:36] [main/INFO]: apoli.mixins.json:ItemSlotArgumentTypeAccessor from mod apoli->@Accessor[FIELD_GETTER]::getSlotNamesToSlotCommandId()Ljava/util/Map; should be static as its target is
[10:07:36] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[10:07:37] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:07:38] [Render thread/INFO]: Setting user: Clay_T
[10:07:39] [Render thread/INFO]: Apoli 2.5.0 has initialized. Ready to power up your game!
[10:07:39] [Render thread/INFO]: Customizable Player Models Initialized
[10:07:39] [Render thread/INFO]: Loaded plugins: (0)

[10:07:39] [Render thread/INFO]: Origins 1.6.1 is initializing. Have fun!
[10:07:39] [Render thread/INFO]: Compatibility version 14
[10:07:39] [Render thread/INFO]: Loading plugins
[10:07:39] [Render thread/INFO]: Loaded 0 plugin(s)
[10:07:39] [Render thread/INFO]: Initializing plugins
[10:07:39] [Render thread/INFO]: Initialized 0 plugin(s)
[10:07:41] [Render thread/INFO]: Loading 62 entities from Custom Entity Models 0.7.1
[10:07:41] [Render thread/INFO]: [citresewn] Registering CIT Conditions
[10:07:41] [Render thread/INFO]: [citresewn] Registering CIT Types
[10:07:41] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=2 on mixins.iris.json:texture.MixinAbstractTexture from mod iris::handler$bch000$iris$afterGenerateId exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[10:07:41] [Render thread/INFO]: Customizable Player Models Client Init started
[10:07:41] [Render thread/INFO]: Customizable Player Models Client Initialized
[10:07:41] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[10:07:41] [Render thread/INFO]: [LambDynLights] Initializing LambDynamicLights...
[10:07:41] [Render thread/INFO]: [LambDynLights] Configuration loaded.
[10:07:42] [Render thread/INFO]: Using Cloth Config GUI
[10:07:42] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[10:07:42] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[10:07:43] [ForkJoinPool.commonPool-worker-1/WARN]: [Iris Update Check] Unable to download https://github.com/IrisShaders/Iris-Update-Index/releases/download/test/updateIndex.json
[10:07:44] [Render thread/INFO]: Debug functionality is disabled.
[10:07:44] [Render thread/WARN]: Unable to resolve shader pack option menu element "MOTION_BLUR_HQ" defined in shaders.properties
[10:07:44] [Render thread/WARN]: Unable to resolve shader pack option menu element "CLOUDS_IN_REFLECTIONS" defined in shaders.properties
[10:07:44] [Render thread/INFO]: Profile: Custom (+0 options changed by user)
[10:07:45] [Render thread/INFO]: Using shaderpack: SEUS PTGI HRR 3
[10:07:46] [Render thread/INFO]: Hardware information:
[10:07:46] [Render thread/INFO]: CPU: 12x AMD Ryzen 5 5600H with Radeon Graphics 
[10:07:46] [Render thread/INFO]: GPU: AMD Radeon RX 6600M (Supports OpenGL 3.2.148300 Core Profile Forward-Compatible Context 21.10.01.31 27.20.21001.31002)
[10:07:46] [Render thread/INFO]: OS: Windows 10 (10.0)
[10:07:47] [Render thread/INFO]: Narrator library for x64 successfully loaded
[10:07:47] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Additionalentityattributes, Apoli, Better Biome Blend, CaffeineConfig, Calio, Cardinal Components API (base), Cardinal Components API (entities), Custom Entity Models, CIT Resewn, CIT Resewn: Defaults, Cloth Config v6, completeconfig-base, Continuity, Customizable Player Models, Cull Leaves, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Iris, Kanos Config, LambDynamicLights, LazyDFU, Lithium, Logical Zoom, MidnightLib, Mod Menu, Origins, Pehkui, Phosphor, Pal, Pride Lib, Reach Entity Attributes, Reese's Sodium Options, Sodium, Sodium Extra, SpruceUI, Simple Voice Chat), WHAT, continuity/glass_pane_culling_fix, continuity/default
[10:07:48] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[10:07:49] [Render thread/WARN]: [Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[10:07:49] [Render thread/WARN]: Shader compilation log for composite5.fsh: Fragment shader failed to compile with the following errors:
ERROR: 0:847: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:847: error(#216) Vector field selection out of range "a"
ERROR: 0:1073: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:1073: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:1626: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:1626: error(#247) Function return does not match type
ERROR: 0:1651: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:1651: error(#247) Function return does not match type
ERROR: 0:2718: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:2718: error(#216) Vector field selection out of range "rgb"
ERROR: 0:2835: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:2835: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:2836: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:2836: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:2837: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:2837: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:2838: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:2838: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:2882: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:2882: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:2883: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:2883: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:2891: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:2983: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:2983: error(#216) Vector field selection out of range "rgb"
ERROR: 0:5310: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:5310: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:5365: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:5365: error(#216) Vector field selection out of range "a"
ERROR: 0:5377: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:5377: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: error(#273) 31 compilation errors.  No code generated


[10:07:49] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: Shader compilation failed!
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:236) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:94) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:221) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:642) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) [iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.Iris.onLoadingComplete(Iris.java:217) [iris-mc1.19-1.2.5.jar:?]
	at net.minecraft.class_442.handler$bbd000$iris$showSodiumIncompatScreen(class_442.java:541) [client-intermediary.jar:?]
	at net.minecraft.class_442.method_25426(class_442.java:155) [client-intermediary.jar:?]
	at net.minecraft.class_437.method_41843(class_437.java:391) [client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:382) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1001) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:634) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:198) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
Caused by: java.lang.RuntimeException: Failed to compile FRAGMENT shader for program composite5.fsh
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:78) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:232) ~[iris-mc1.19-1.2.5.jar:?]
	... 15 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:40) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:21) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:76) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:232) ~[iris-mc1.19-1.2.5.jar:?]
	... 15 more
[10:07:49] [Render thread/INFO]: [STDOUT]: (MidnightLib) Player hats successfully loaded!
[10:07:57] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[10:07:57] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[10:07:58] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speaker (Realtek(R) Audio)
[10:07:58] [Render thread/INFO]: Sound engine started
[10:07:58] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[10:07:59] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[10:07:59] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[10:07:59] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[10:07:59] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[10:07:59] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[10:07:59] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[10:08:00] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[10:08:00] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[10:08:00] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[10:08:00] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[10:08:35] [Render thread/INFO]: Connecting to krya.joinserver.ru, 25565
[10:08:37] [Render thread/INFO]: Started 6 worker threads
[10:08:38] [Render thread/INFO]: Sending secret request to the server
[10:08:39] [Render thread/ERROR]: Error while reading power holder data: Could not get power type from id 'foxboi_two:pounce', as it was not registered!
[10:08:39] [Render thread/INFO]: Loaded 1043 advancements
[10:08:39] [Render thread/INFO]: Received secret
[10:08:39] [Render thread/INFO]: Connecting to server: 'n16.joinserver.ru.:25661'
[10:08:39] [VoiceChatAuthenticationThread/INFO]: Trying to authenticate voice connection
[10:08:39] [Render thread/WARN]: Unable to play empty soundEvent: minecraft:entity.tropical_fish.ambient
[10:08:39] [VoiceChatConnectionThread/INFO]: Server acknowledged authentication
[10:08:40] [Thread-27/INFO]: Using Opus version 'libopus 1.3.1'
[10:12:04] [Render thread/INFO]: Clearing audio channels
[10:12:04] [Render thread/INFO]: Stopping microphone thread
[10:12:04] [Render thread/INFO]: Disconnecting voicechat
[10:12:04] [Render thread/INFO]: Stopping worker threads
[10:12:06] [Render thread/INFO]: Stopping!
```

### Minecraft Version

Minecraft 1.19

### Iris Version

iris-mc1.19-1.2.5.jar

### Sodium Version

sodium-fabric-mc1.19-0.4.2+build.16.jar

### Operating System

Windows 10

### What is your GPU?

AMD Radeon RX 6600m

### Java Version

Java 17.0.3 x64

### Additional context

I think the issue is on the IRIS mod, as these shaders work fine on optifine

**Comment by siyy123** [comment] 2022-06-19 08:46
Same problem. The shader won't compile on amd gpu with any version beyond E12.

**Comment by coderbot16** [comment] 2022-06-19 14:29
This appears to be a duplicate of https://github.com/IrisShaders/Iris/issues/1071.

**Closed by coderbot16** 2022-06-19 14:29 UTC
Labels: bug
