### ISSUE TITLE
Podzol does not render sometimes with Continuum Shaders

### ISSUE THREAD

**Issue by NotJansel** [IrisShaders/Iris#402] opened 2021-06-17 23:00 UTC
I was flying around in a world and in a spruce forest with podzol I noticed a strange ocurrence
![2021-06-18_00 58 55](https://user-images.githubusercontent.com/73423410/122482249-7780a980-cfd0-11eb-8d5c-c9827a222cc5.png)
This is only occuring with the continuum shader.

**Comment by IMS212** [comment] 2021-06-17 23:04
Can you confirm this does not happen on OptiFine?

**Comment by NotJansel** [comment] 2021-06-17 23:07
![2021-06-18_01 07 07](https://user-images.githubusercontent.com/73423410/122482782-8451cd00-cfd1-11eb-9c8c-6af11e87510d.png)
does not happen on optifine

**Comment by coderbot16** [comment] 2021-06-27 17:13
If you open F3, are all of the see-through blocks of the same type, and if so, what type of blocks are they?

Would also just be generally helpful to have an F3 screenshot.

**Comment by CodingRays** [comment] 2021-06-29 22:14
I was able to reproduce the issue in 1.16 only while sodium is installed. As far as i can tell all affected blocks are podzol.

**Comment by CodingRays** [comment] 2021-06-30 00:22
So it looks like the faces of some podzol aren't rendered. The shadow pass correctly renders those faces so i doubt the issue is that the buffers are incorrect.
I suspect were passing incorrect vertex specifications to the multidraw command. The podzol seems to be the first instruction in the multidraw as well.

**Comment by NotJansel** [comment] 2021-06-30 01:30
As CodingRays said, right now only podzol is affected, but there could be more affected, I will also look for other blocks which could be affected.

**Comment by CodingRays** [comment] 2021-06-30 09:56
I just tested it on the 1.17 release and everything looks normal there.

**Comment by CodingRays** [comment] 2021-07-01 14:38
There have been a bunch of reported issues of missing faces in 1.17 which might be related. I was able to confirm at least 1 such problem. Again same symptoms as with this issue. Missing faces in the main render pass but which are rendered in the shadow pass.
However in 1.17 the affected faces change if a resource pack is reloaded which does not seem to be the case for this issue.

**Comment by coderbot16** [comment] 2021-09-25 23:41
This was fixed in Iris 1.1.2 with this commit (and one other for base Iris): https://github.com/IrisShaders/sodium-fabric/commit/28b29bab52e73efa4d4efe0455aeefabb2cfbb36

It affected 1.17 much more severely due to 1.17 having more blocks.

**Closed by coderbot16** 2021-09-25 23:41 UTC
Labels: bug
