### ISSUE TITLE
Oak stairs are emissive when using SEUS PTGI HRR

### ISSUE THREAD

**Issue by Spectralitree** [IrisShaders/Iris#844] opened 2021-09-06 18:22 UTC
### What happened?

Oak stairs are emissive when using SEUD PTGI HRR shaders. I checked most of the other shaders I have installed (complementary, BSL, sildur's vibrant) and they do not appear to have the same issue. Neither do any of the other stairs.

### Screenshots

![2021-09-06_20 03 52](https://user-images.githubusercontent.com/72747870/132251784-c5e36c06-173b-4ad8-bbf3-de665ae7ead7.png)
![2021-09-06_20 01 04](https://user-images.githubusercontent.com/72747870/132251842-b651d7ff-b3a1-4eeb-90b6-973829d6ff37.png)

### Iris and Minecraft Version

iris-and-sodium-mc1.17-1.1.2+build.9.jar for minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 1650 Ti

### Java Version

Java 16.0.1

### Additional context

I have Indium and other mods installed, let me know if this changes things and I'll check just sodium+iris as well.

**Comment by DestinyTheGreat** [comment] 2021-09-06 18:23
SEUS PTGI is not a supported shader (yet)

**Comment by Spectralitree** [comment] 2021-09-06 18:25
Ah I must've misread the announcement then! Apologies

**Comment by IMS212** [comment] 2021-09-06 18:38
Leaving this open as we don’t know the cause.

**Comment by Fuzlop** [comment] 2021-09-15 08:31
Is there oak stairs_s.png file in your texture pack's block texture folder?

**Comment by 1a2s3d4f1** [comment] 2021-10-05 15:06
It may caused by iris miss some feature. such as read block.properties and support custom uniforms.
More information see:https://tieba.baidu.com/p/7528405720

**Comment by Ohnyx69** [comment] 2021-11-04 20:26
> 
> 
> This is caused by Iris not properly handling `#elif` directives when parsing `block.properties`.
> 
> As a result, the 1.13 block ID mappings for SEUS PTGI HRR override the 1.14+ block ID mappings. In this case, Sonic Ether forgot to update the 1.13 mappings when he added support for the new 1.16 blocks, meaning that Oak Stairs are getting mapped to `minecraft:soul_fire`, causing them to emit blue light.
> 
> It seems like if you loaded up SEUS PTGI HRR on OptiFine for 1.13, you'd observe similar issues, interestingly enough.

so deleting the entire `#elif` argument fixes the problem for now?

**Comment by coderbot16** [comment] 2021-11-04 20:54
Well, you'd need to manually delete everything between the #elif and the #else block, since the #elif isn't the issue, it's everything after it and before the #else that isn't getting properly ignored.

**Comment by coderbot16** [comment] 2021-11-30 22:46
Fixed in 1.1.3

**Closed by coderbot16** 2021-11-30 22:46 UTC
Labels: bug, status: fixed in next release
