### ISSUE TITLE
Game becomes completely unresponsive after clicking on "Shader Packs" button

### ISSUE THREAD

**Issue by Type-32** [IrisShaders/Iris#494] opened 2021-07-07 13:01 UTC
### Iris and Minecraft Version

iris-mc1.16.5-1.0.0.jar for Minecraft 1.16.5

### Are you running Sodium along with Iris?

No

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce GTX 860M

### Java Version

Java 8

### Reproduction Steps

1. Opens up game from official minecraft launcher
2. clicks on the "Option" button
3. clicks on the "Video Settings" button
4. clicks on the "Shader Packs" button
5. game freezes

### Crash Report file and latest.log

```shell
Sorry but it just freezes dead without any crashes...
```

**Comment by AlsoNiko** [comment] 2021-07-07 13:05
Please use both the latest version of iris, and provide the latest.log file from your .minecraft folder

**Comment by Type-32** [comment] 2021-07-07 13:20
I used the newest version of Iris and I removed everything except Iris from my minecraft mod folder and the game still became unresponsive. There isn't a crash report after I mandatorily ended it with Task Manager and my allocated RAM to the minecraft configuration is 3500MB.

**Comment by Type-32** [comment] 2021-07-07 13:30
Sorry for the inconvenience for checking this issue repeatedly - I have accidentally putted non-shader .zip files into the shaderpacks folder

**Comment by coderbot16** [comment] 2021-07-08 00:11
That sounds like something that should be fixed. What kind of non-shaderpack files were you putting in the shader packs folder?

**Comment by Type-32** [comment] 2021-07-08 05:42
I have accidentally putted in a 1.17 Energy Shaders Resource Pack(By Linus Dev) and a Choacapic V9.zip file which I later found out wasn't a shaderpack.
[Energy Shaders [Java] [Test] (1).zip](https://github.com/IrisShaders/Iris/files/6781808/Energy.Shaders.Java.Test.1.zip)

**Comment by PROGAMER1500** [comment] 2021-12-04 22:28
iv had this issue when modding mc and took me a while to fix it though i forgot the way to fix it.

**Comment by coderbot16** [comment] 2022-01-30 03:50
I was unable to reproduce with that ZIP file. Given that there's been no more reproducible confirmations of this issue for a long time, I'll close this for now. If it comes up again then please open another issue!

**Closed by coderbot16** 2022-01-30 03:50 UTC
