### ISSUE TITLE
[1.17] [LINUX] Shaders dont apply at all

### ISSUE THREAD

**Issue by kleinermob** [IrisShaders/Iris#379] opened 2021-06-12 11:24 UTC
F3 shows they are applied but they arent
![Screenshot_20210612_132251](https://user-images.githubusercontent.com/42699035/121774191-70e1d480-cb81-11eb-9bef-4ce24c730955.png)
![Screenshot_20210612_132312](https://user-images.githubusercontent.com/42699035/121774192-72ab9800-cb81-11eb-856e-78cedf0bb7e9.png)
[latest.log](https://github.com/IrisShaders/Iris/files/6642065/latest.log)
works fine on 1.16.5

**Comment by kleinermob** [comment] 2021-06-12 11:29
![Uploading Screenshot_20210612_132849.png…]()

**Comment by Mithos23** [comment] 2021-06-12 11:58
Duplicate of #350

**Closed** 2021-06-12 12:14 UTC
