### ISSUE TITLE
Ghosting on entities on SEUS HRR 3 

### ISSUE THREAD

**Issue by ArchandePlus** [IrisShaders/Iris#1886] opened 2023-02-14 18:14 UTC
### Ghosting on SEUS HRR 3, Nostalgia Shaders and Kappa shaders.

Whenever there is movement in the scene, there is ghosting present in entities. this is present mostly in other players, item frames, armor stands and nametags.

### Screenshots

![2023-02-14_18 03 46](https://user-images.githubusercontent.com/125395420/218821391-0bf4cce3-6ea5-4cd4-b55a-1761bf3c9d7a.png)
![2023-02-14_18 03 43](https://user-images.githubusercontent.com/125395420/218821401-f90a8feb-aa26-4936-8f68-16e868f62691.png)

https://user-images.githubusercontent.com/125395420/218827404-faf5ec69-cb5f-44a7-bc74-ade54809eba5.mp4

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/10735563/latest.log)

### Minecraft Version

1.19.2

### Iris Version

iris-mc1.19.2-1.5.2.jar

### Operating System

Windows 11

### What is your GPU?

Nvidia Geforce 3080

**Comment by ArchandePlus** [comment] 2023-02-14 18:18
Apologies for the bad compression on the video, i had no clue it was this bad on GitGub

**Comment by IMS212** [comment] 2023-02-14 19:11
Duplicate of #1446.

**Closed by IMS212** 2023-02-14 19:11 UTC
Labels: bug

**Comment by TheLastTank** [comment] 2023-03-15 11:52
Hello, any news on this one? 
i’m having the same issue but mainly with mods, i’ve tried all hrr versions (1.0, 2.0 ,2.1 and 3.0) but all have this issue, even 3.0 which says its fixed (in the patreon’s post it says so).
It seems the are issues calculating entities motion vectors, is there something i can do to at least alleviate it?
