### ISSUE TITLE
[1.16.5] SEUS crash on Intel igpu

### ISSUE THREAD

**Issue by Grayray75** [IrisShaders/Iris#356] opened 2021-06-10 07:28 UTC
When opening a world with SEUS shaders i instantly crash.

With **SEUS-Renewed-v1.0.1** i get the following error:
[crash-2021-06-10_08.44.54-client.txt](https://github.com/IrisShaders/Iris/files/6629189/crash-2021-06-10_08.44.54-client.txt)
[2021-06-10-1.log](https://github.com/IrisShaders/Iris/files/6629194/2021-06-10-1.log)

With **SEUS-v11.0** this error:
[crash-2021-06-10_09.08.56-client.txt](https://github.com/IrisShaders/Iris/files/6629203/crash-2021-06-10_09.08.56-client.txt)
[2021-06-10-2.log](https://github.com/IrisShaders/Iris/files/6629219/2021-06-10-2.log)

**Used Mods:**
* iris-mc1.16.5-1.0.0-rc1.jar
* sodium-fabric-mc1.16.5-0.2.0+IRIS_rev.400af47.jar

**System Information:**
CPU: 11th Gen Intel(R) Core(TM) i5-1135G7
GPU: Intel(R) Iris(R) Xe Graphics
Java: 1.8.0_282, AdoptOpenJDK

**Comment by thedocruby** [comment] 2021-06-11 05:15
This appears to be a duplicate of #350

**Comment by AlsoNiko** [comment] 2021-06-11 05:16
Not a duplicate issue, this is on 1.16.5 not 1.17

**Comment by coderbot16** [comment] 2021-12-21 20:04
Found something that might be related: https://community.intel.com/t5/Developing-Games-Graphics-on/Geometry-Shader-Bug/td-p/1142733

Post:

> I have an ongoing problem with the Intel shader compiler for Intel HD Graphics cards (most of the ones I have tested).
>
> The issue is related to utilizing a geometry shader, in which I will receive this message:
>
> 'The fragment shader uses varying uv, but previous shader does not write to it.  Out of resource error.'
>
> This is a bug, pure and simple, easily described as the fact that the shader compiler does not properly see that there is a geometry shader in the pipeline.
>
> I can elaborate more if the above post is does not provide enough information, but it is actually quite simple:
[snip]
> This is easy to diagnose:
>
> A vertex -> fragment pipeline does not write 'varying uv', but the geometry shader is the true 'previous shader', so this is a bug and therefore Intel HD Graphics does not meet the criterion for OpenGL support.
>
> (It is bad form and likely illegal to claim OpenGL support when the conformant requirements are not met)
>
> FYI:  Nvidia and AMD have no issues whatsoever compiling the same shaders.

Response:

> This problem can be resolved by changing the order in which the shaders are submitted for compilation.  Only the Intel driver seems to complain about this order.  Here is a viable workaround; ensure that the compilation order is 1) Vertex 2) Geometry 3) Fragment prior to the glUseProgram() command.

**Comment by coderbot16** [comment] 2021-12-21 20:05
However, I don't think SEUS v11 uses geometry shaders. So it might be a red herring.

**Comment by coderbot16** [comment] 2022-03-02 07:48
This should no longer instantly crash the game. Otherwise, I don't think there's anything we can reasonably do for this - it's an issue with SEUS and/or intel windows drivers.

**Closed by coderbot16** 2022-03-02 07:48 UTC
Labels: bug, at the mercy of drivers, pack: seus
