### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005) Crash

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [IrisShaders/Iris#77] opened 2021-01-07 13:11 UTC
I know this isn't fully about Iris, but I hope you guys could tell me I should do in this situation. I pasted the issue I posted on the MultiMC Github here:

System Information

MultiMC version:
0.6.11-1430 on win 32 - MultiMC 5

Operating System:
Windows 10

Summary of the issue or suggestion:
MC Launches, Loads, and then right before the title screen fully shows it crashes

What should happen:
Obviously MC shouldn't crash

Steps to reproduce the issue (Add more if needed):
1.  Launch Minecraft

Suspected cause:
Iris or Sodium, but IDK (I know that it's not now, this is just the copied issue)

Logs/Screenshots:
[Log](paste.ee/p/RnIkf)
[Screeenshot](img.justpaste.me/i/20210107/kxV1z/Screenshot 2021-01-07 080827.jpg)

Now I know it's about AMD and atio6axx.dll or whatever, I just want to know what to do right now. Please help me if you can.

**Comment by peterodavies27atgmailcom** [comment] 2021-01-07 13:12
oh yeah I'm using the Iris sodium compatibility too.

**Comment by Giggitybyte** [comment] 2021-01-07 13:18
I've had the same error in a different environment; running Minecraft using Java 15 solved the issue for me.

**Comment by peterodavies27atgmailcom** [comment] 2021-01-07 13:56
ok, I'll try that, thanks

**Comment by peterodavies27atgmailcom** [comment] 2021-01-11 22:50
I'm using java 15 and now I can get into the game but I cant run a world

[log](https://paste.ee/p/YdW2J)

**Comment by peterodavies27atgmailcom** [comment] 2021-01-11 22:50
btw I'm using logical zoom now too

**Comment by IMS212** [comment] 2021-01-11 23:19
Interesting, someone else had this exact same issue with optifine, seems to be AMD related

**Comment by BeansBeefBroccoli** [comment] 2021-01-12 15:41
Is this problem fixable without getting nvidia things

**Comment by BeansBeefBroccoli** [comment] 2021-01-12 17:12
is there a way to fix it

**Comment by BeansBeefBroccoli** [comment] 2021-01-15 13:07
I went to Windows 10 MC (Bedrock Edition) for an unrelated reason, and it said my graphics drivers had an update. Does that have anything to do with this?

**Comment by BeansBeefBroccoli** [comment] 2021-01-17 16:03
it sends me to [this site](https://www.amd.com/en/support)

**Comment by Username404-59** [comment] 2021-01-17 23:06
The issue here could effectively be your drivers, I think you should update them.

**Comment by BeansBeefBroccoli** [comment] 2021-01-18 15:17
ok, I will

**Comment by Meeni-mc** [comment] 2021-01-19 05:03
I have the same error with Optifine w/shaders. It's related to AMD drivers. Downgrading to driver 20.04 fixes the issue with OF.

**Comment by coderbot16** [comment] 2021-01-19 05:07
For me to know what's going on in this crash I'll need to see the `hs_err_pid_(whatever).txt` file. It's possible that this is a duplicate of https://github.com/IrisShaders/Iris/issues/51.

I've seen another variant of this crash related to the initialization of NoiseTexture, however, which I'm not sure how to work around.

**Comment by BeansBeefBroccoli** [comment] 2021-01-19 20:54
I'll test if updating worked look for that hs_err_pid_(whatever).txt file as soon as I can.

**Comment by BeansBeefBroccoli** [comment] 2021-01-19 23:46
idk wich one it is but here are all my hs_err_pid_(whatever).log files:
[hs_err_pid11868.log](https://github.com/IrisShaders/Iris/files/5839234/hs_err_pid11868.log)
[hs_err_pid15012.log](https://github.com/IrisShaders/Iris/files/5839235/hs_err_pid15012.log)
[hs_err_pid15136.log](https://github.com/IrisShaders/Iris/files/5839236/hs_err_pid15136.log)
[hs_err_pid20468.log](https://github.com/IrisShaders/Iris/files/5839237/hs_err_pid20468.log)
[hs_err_pid27000.log](https://github.com/IrisShaders/Iris/files/5839238/hs_err_pid27000.log)

**Comment by BeansBeefBroccoli** [comment] 2021-01-20 17:38
sorry I still haven't tried to use a shader yet I have a lot to do

**Comment by BeansBeefBroccoli** [comment] 2021-01-20 22:58
I can start minecraft, but it doesn't load
![image](https://user-images.githubusercontent.com/69123018/105251189-07691700-5b49-11eb-88be-ba12b468e2ac.png)

**Comment by BeansBeefBroccoli** [comment] 2021-01-24 02:31
I've been trying to do other stuff and a lot of minecraft, even vanilla 1.15 wont load, what should I do

**Comment by BeansBeefBroccoli** [comment] 2021-01-31 23:30
it might work now, I'll get back to you tomorrow if I can.

**Comment by stashymane** [comment] 2021-02-23 09:00
Also receiving access violation.
https://gist.github.com/stashymane/18617919adebff72da556f72350da7c8

Ryzen 5800X + 5700XT, Liberica JDK 11.
On JDK8 it crashes with this:
`The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
Exit Code: -1`
but I assume this is due to the fact that Java8 is not supported.
Only mods installed are `fabric-api-0.30.3+1.16`, `iris-0.1.0-sodium_compatibility`, `sodium-fabric-mc1.16.4-IRIS-SNAPSHOT` and `iris-explorer-0.1.0`
Running Iris sodium compat branch with commit `7e33aa4` and sodium iris branch commit `a37f01d`

**Comment by IMS212** [comment] 2021-02-23 09:01
The ByteBuffer error shows up if you compiled with JDK 9+ and are running MC with 8.

**Comment by stashymane** [comment] 2021-02-23 09:03
For additional info, my crash only happens once a shaderpack is being loaded - the game runs fine otherwise.

**Closed** 2021-03-05 03:48 UTC
Labels: bug

**Comment by coderbot16** [comment] 2021-03-05 03:50
This should be resolved now, the crashes in glShaderSource and glTexImage2D have been fixed in the latest commits.
