### ISSUE TITLE
SEUS PTGI HRR  not loading 

### ISSUE THREAD

**Issue by Ryan44444444444444444444444444444444444** [IrisShaders/Iris#1117] opened 2021-12-19 22:16 UTC
### What happened?

I tried to load the shader but when it was done loading, the vanilla graphics were still there, no shader.
I have an AMD 6700xt paired with a ryzen 5 3600

### Screenshots

![Screenshot 2021-12-19 171314](https://user-images.githubusercontent.com/72310706/146692684-c7040890-e07b-494e-9416-740aab22a7fd.png)

### Relevant log output

```shell
[16:39:05] [Render thread/INFO]: Using shaderpack: SEUS PTGI HRR Test 2.1.zip
[16:39:05] [Render thread/INFO]: Creating pipeline OVERWORLD
[16:39:07] [Render thread/WARN]: [Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[16:39:07] [Render thread/WARN]: Shader compilation log for composite5.fsh: Fragment shader failed to compile with the following errors:
ERROR: 0:1288: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:1288: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:1840: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:1840: error(#247) Function return does not match type
ERROR: 0:2975: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:2975: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:2976: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:2976: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:2977: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:2977: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:3019: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:3019: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:3020: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:3020: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:3028: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:3120: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:3120: error(#216) Vector field selection out of range "rgb"
ERROR: 0:4001: error(#101) Macro redefined: FxaaInt2
ERROR: 0:4003: error(#101) Macro redefined: FxaaTexTop
ERROR: 0:4004: error(#101) Macro redefined: FxaaTexOff
ERROR: 0:4015: error(#101) Macro redefined: FxaaInt2
ERROR: 0:4015: error(#132) Syntax error: "sampler2D" parse error
ERROR: error(#273) 22 compilation errors.  No code generated


[16:39:07] [Render thread/ERROR]: Couldn't load NewWorldRenderingPipeline, falling back to vanilla shaders.
java.lang.RuntimeException: Shader compilation failed!
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:195) ~[iris-mc1.18-pre8-1.1.3-starline+build.657.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:75) ~[iris-mc1.18-pre8-1.1.3-starline+build.657.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:222) ~[iris-mc1.18-pre8-1.1.3-starline+build.657.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:424) ~[iris-mc1.18-pre8-1.1.3-starline+build.657.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:32) [iris-mc1.18-pre8-1.1.3-starline+build.657.jar:?]
	at net.minecraft.class_761.handler$zoc000$iris$beginLevelRender(class_761.java:6450) [intermediary-1.18.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1240) [intermediary-1.18.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1026) [intermediary-1.18.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:810) [intermediary-1.18.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1117) [intermediary-1.18.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [intermediary-1.18.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [intermediary-1.18.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.8.jar:?]
Caused by: java.lang.RuntimeException: Failed to compile FRAGMENT shader for program composite5.fsh
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:98) ~[iris-mc1.18-pre8-1.1.3-starline+build.657.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:69) ~[iris-mc1.18-pre8-1.1.3-starline+build.657.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:191) ~[iris-mc1.18-pre8-1.1.3-starline+build.657.jar:?]
	... 18 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:44) ~[iris-mc1.18-pre8-1.1.3-starline+build.657.jar:?]
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:23) ~[iris-mc1.18-pre8-1.1.3-starline+build.657.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:96) ~[iris-mc1.18-pre8-1.1.3-starline+build.657.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:69) ~[iris-mc1.18-pre8-1.1.3-starline+build.657.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:191) ~[iris-mc1.18-pre8-1.1.3-starline+build.657.jar:?]
	... 18 more
[16:39:18] [Render thread/WARN]: Failed to set shaderpack profile  as it does not exist!
```

### Minecraft Version

Minecraft 1.18.1

### Iris Version

Iris 1.1.3

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Operating System

Windows 10

### What is your GPU?

AMD RX 6700XT

### Java Version

17

**Comment by AlsoSylv** [comment] 2021-12-19 22:21
Duplicate of #1071

**Comment by NoComment1105** [comment] 2021-12-19 22:21
You are also using starline, as to which is not supported, and deliberately not put in the issue report

**Closed by AlsoSylv** 2021-12-19 22:21 UTC
Labels: bug
