### ISSUE TITLE
Sildurs Vibrant Shaders crash game in the End (on M1 Mac)

### ISSUE THREAD

**Issue by DestinyTheGreat** [IrisShaders/Iris#404] opened 2021-06-18 03:05 UTC
Going into the End portal with Sildurs enabled or enabling Sildurs in the End causes a crash on M1

[latest.log](https://github.com/IrisShaders/Iris/files/6674341/latest.log)

[crash report](https://github.com/IrisShaders/Iris/files/6674344/crash-2021-06-17_19.57.24-client.txt)

Edit: This does not occur on the version of Iris/Sodium that is on Modrinth/Curseforge/GHReleases, and also doesn't happen on Niko's jar-in-jar of Sodium + Iris 1.0.1, only on latest commit Iris 1.0.2

**Comment by DestinyTheGreat** [comment] 2021-06-18 03:26
M1-only, not worth trying to solve

**Comment by DestinyTheGreat** [comment] 2021-06-18 03:29
Reopening for tracking

**Comment by AlsoNiko** [comment] 2021-06-18 03:30
Removing the high priority tag as this doesn't happen on Intel Macs, probably worth fixing at some point, but not needed right away.

**Comment by coderbot16** [comment] 2021-06-18 03:37
Relevant part of the error:

```
Shader compilation log for iris:sodium-terrain.fsh: ERROR: 0:289: '' : syntax error: #extension must always be before any non-preprocessor tokens
```

**Comment by AlsoNiko** [comment] 2021-06-21 04:12
Marking high prio because there are a lot of M1 users, broke between 1.0.1 and 1.0.2

**Comment by coderbot16** [comment] 2021-06-22 01:57
This is caused by https://github.com/IrisShaders/Iris/commit/c4f5a0d24b66abdd417af70c756a926fda6c36b5 exposing a shortcoming in the shader patching code.

**Comment by AlsoNiko** [comment] 2021-06-25 16:06
Should be fixed now

**Closed by AlsoNiko** 2021-06-25 16:06 UTC
Labels: bug, high priority
