### ISSUE TITLE
Please, make Iris support Sodium 0.5.8

### ISSUE THREAD

**Issue by J4k3v3** [IrisShaders/Iris#2245] opened 2024-02-09 16:49 UTC
### Minecraft Version

Minecraft 1.20.4

### Iris Version

iris-mc1.20.4-1.6.14.jar

### Sodium Version

sodium-fabric-0.5.8+mc1.20.4.jar

### Operating System

Windows 11

### What is your GPU?

Nvidia Quadro 2200M

### Java Version

Java 8

### Reproduction Steps

![image](https://github.com/IrisShaders/Iris/assets/111687331/da2b8d32-4b24-44ee-a070-6a5e875dab67)

### Crash Report file and latest.log

```shell
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Remove mod 'Reese's Sodium Options' (reeses-sodium-options) 1.7.2+mc1.20.4-build.102 (C:\Users\J4k3v3\AppData\Roaming\.tlauncher\legacy\Minecraft\game\mods\reeses_sodium_options-1.7.2+mc1.20.4-build.102.jar).
	 - Replace mod 'Sodium' (sodium) 0.5.8+mc1.20.4 with version 0.5.8 that is compatible with:
		 - iris, any version
	 - Replace mod 'Iris' (iris) 1.6.14 with any version that is compatible with:
		 - sodium, version 0.5.8
More details:
	 - Mod 'Sodium' (sodium) 0.5.8+mc1.20.4 is incompatible with version 1.6.14 or earlier of mod 'Iris' (iris), but a matching version is present: 1.6.14!
	 - Mod 'Iris' (iris) 1.6.14 requires version 0.5.5 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.8+mc1.20.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

### Additional context

Please, make Iris support Sodium 0.5.8!!!

**Comment by Lolothepro** [comment] 2024-02-09 16:49
duplicate of https://github.com/IrisShaders/Iris/issues/2241

**Closed** 2024-02-14 03:11 UTC
Labels: crash
