### ISSUE TITLE
Does not work with VanillaPlus_v3.0a

### ISSUE THREAD

**Issue by peasoft** [IrisShaders/Iris#1595] opened 2022-08-18 00:11 UTC
### Minecraft Version

Minecraft 1.17.1

### Iris Version

iris-mc1.17.1-1.2.6

### Sodium Version

sodium-fabric-mc1.17.1-0.3.4+build.13

### Operating System

Windows 11

### What is your GPU?

Intel(R) Iris(R) Xe Graphics

### Java Version

Java 17

### Reproduction Steps

1. Start a world or join a server
2. Game Crashes

### Crash Report file and latest.log

```shell
[07:44:22] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error'
- 55 times

==========================================================================================================

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2022/8/18 上午7:44
Description: Unexpected error

java.lang.RuntimeException: Shader program linking failed, see log for details
        at me.jellysquid.mods.sodium.client.gl.shader.GlProgram$Builder.link(GlProgram.java:113)
        at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShader(IrisChunkProgramOverrides.java:161)
        at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShaders(IrisChunkProgramOverrides.java:209)
        at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.getProgramOverride(IrisChunkProgramOverrides.java:233)
        at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.handler$bik000$iris$begin(ShaderChunkRenderer.java:548)
        at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java)
        at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:73)
        at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:303)
        at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:224)
        at net.minecraft.class_761.method_3251(class_761.java:12330)
        at net.minecraft.class_761.invokeRenderChunkLayer(class_761.java)
        at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:417)
        at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:629)
        at net.minecraft.class_761.handler$beg000$iris$renderTerrainShadows(class_761.java:7830)
        at net.minecraft.class_761.method_22710(class_761.java:1142)
        at net.minecraft.class_757.method_3188(class_757.java:1026)
        at net.minecraft.class_757.method_3192(class_757.java:810)
        at net.minecraft.class_310.method_1523(class_310.java:1112)
        at net.minecraft.class_310.method_1514(class_310.java:728)
        at net.minecraft.client.main.Main.main(Main.java:217)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
        at me.jellysquid.mods.sodium.client.gl.shader.GlProgram$Builder.link(GlProgram.java:113)
        at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShader(IrisChunkProgramOverrides.java:161)
        at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShaders(IrisChunkProgramOverrides.java:209)
        at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.getProgramOverride(IrisChunkProgramOverrides.java:233)
        at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.handler$bik000$iris$begin(ShaderChunkRenderer.java:548)
        at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java)
        at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:73)
        at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:303)
        at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:224)
        at net.minecraft.class_761.method_3251(class_761.java:12330)
        at net.minecraft.class_761.invokeRenderChunkLayer(class_761.java)
        at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:417)
        at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:629)
        at net.minecraft.class_761.handler$beg000$iris$renderTerrainShadows(class_761.java:7830)
        at net.minecraft.class_761.method_22710(class_761.java:1142)
        at net.minecraft.class_757.method_3188(class_757.java:1026)

==========================================================================================================

GL Caps: Using framebuffer using OpenGL 3.2
        GL debug messages: id=1, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='SHADER_ID_LINK error has been generated. GLSL link failed for program 342, "": Number of Fragment Outputs exceeds HW limits.

' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 342, "" is not linked' x 194
id=1, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='SHADER_ID_LINK error has been generated. GLSL link failed for program 354, "": Number of Fragment Outputs exceeds HW limits.

' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 354, "" is not linked' x 194
id=1, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='SHADER_ID_LINK error has been generated. GLSL link failed for program 357, "": Number of Fragment Outputs exceeds HW limits.

' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 357, "" is not linked' x 194
id=1, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='SHADER_ID_LINK error has been generated. GLSL link failed for program 360, "": Number of Fragment Outputs exceeds HW limits.

' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 360, "" is not linked' x 194
id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 321, "" is not linked' x 18
id=1, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='SHADER_ID_LINK error has been generated. GLSL link failed for program 366, "": Number of Fragment Outputs exceeds HW limits.
```

**Comment by coderbot16** [comment] 2022-09-06 00:17
This is a duplicate of https://github.com/IrisShaders/Iris/issues/937

**Closed by coderbot16** 2022-09-06 00:17 UTC
Labels: crash
