### ISSUE TITLE
Unable to disable shaders in menu

### ISSUE THREAD

**Issue by EsserGaming** [IrisShaders/Iris#367] opened 2021-06-11 05:29 UTC
Disabling shaders doesn't work, as in disabling the shaders and pressing apply and done does not apply and even a restart of the game does not fix it, the current workaround is to press **k** and that does fine.

**Comment by AlsoNiko** [comment] 2021-06-11 05:33
Dupe of #351 , closing as of right now

**Closed by AlsoNiko** 2021-06-11 05:33 UTC
